// Code generated by zi2go from account_http.zi. DO NOT EDIT.
package main

import (
	fmt "fmt"
	slog "log/slog"
	strings "strings"
)

// #import std_go_types
// #import protocol
type Accounts struct {
	Database      *Database
	Configuration *Config
	Counters      *ServerMetrics
	MissingUser   Error
}

type HeaderUserResult struct {
	Value string
	Error Error
}

func AccountHttp_HeaderUser(request *Request, bodyUser string) HeaderUserResult {
	var result HeaderUserResult = HeaderUserResult{}
	header := HttpAuth_UserHeader(request)
	if header.Value == "" {
		var value_0 Error = StdErrorsGo_New("missing X-Daochi-User")
		result.Error = value_0
		return result
	}
	if bodyUser == "" {
		result.Value = header.Value
		return result
	}
	var value_1 string = strings.ToLower(strings.TrimSpace(bodyUser))
	result.Value = value_1
	if result.Value != header.Value {
		var value_2 Error = StdErrorsGo_New(fmt.Sprintf("%s does not match user_id_hash", header.Name))
		result.Error = value_2
	}
	return result
}

func AccountHttp_Authenticate(accounts Accounts, writer ResponseWriter, request *Request, userID string) bool {
	token := HttpAuth_AuthenticateToken(accounts.Database, request, accounts.Configuration.TokenSecret)
	if token.Authentication.Error != nil || token.Authentication.Status != int(0) {
		HttpAuth_Respond(writer, accounts.Counters, token.Authentication)
		return false
	}
	if token.Value != userID {
		Response_Error(writer, int(401), "token user mismatch")
		return false
	}
	return true
}

func AccountHttp_NormalizeAlias(value string) string {
	return strings.TrimPrefix(strings.ToLower(strings.TrimSpace(value)), "@")
}

func AccountHttp_ValidIcon(value int) bool {
	return value >= int(0) && value <= int(11)
}

func AccountHttp_Alias(accounts Accounts, writer ResponseWriter, request *Request) {
	read := HttpBody_ReadJSON(writer, request, accounts.Configuration.MaxBodyBytes)
	if read.Error != nil {
		var value_0 ResponseWriter = writer
		Response_Error(value_0, int(400), StdErrorsGo_Message(read.Error))
		return
	}
	var decoded AliasRequest = AliasRequest{}
	var value_1 Error = StdJsonGo_Unmarshal(read.Value, &(decoded))
	if value_1 != nil {
		Response_Error(writer, int(400), "invalid json")
		return
	}
	var value_2 string = strings.ToLower(strings.TrimSpace(decoded.UserIDHash))
	decoded.UserIDHash = value_2
	var value_3 string = AccountHttp_NormalizeAlias(decoded.Alias)
	decoded.Alias = value_3
	user := AccountHttp_HeaderUser(request, decoded.UserIDHash)
	if user.Error != nil {
		var value_4 ResponseWriter = writer
		Response_Error(value_4, int(400), StdErrorsGo_Message(user.Error))
		return
	}
	var value_5 bool = AccountHttp_Authenticate(accounts, writer, request, user.Value)
	if !value_5 {
		return
	}
	alias := AccountHttp_NormalizeAlias(decoded.Alias)
	var value_6 bool = Identity_ValidAccountAlias(alias)
	if !value_6 {
		Response_Error(writer, int(400), "invalid alias")
		return
	}
	var value_7 *Database = accounts.Database
	var value_8 Context = StdHttpGo_Context(request)
	error := AccountProfile_SetAlias(value_7, value_8, user.Value, alias, accounts.MissingUser)
	if error != nil {
		if strings.Contains(StdErrorsGo_Message(error), "UNIQUE") {
			Response_Error(writer, int(409), "alias unavailable")
			return
		}
		if StdErrorsGo_Is(error, accounts.MissingUser) {
			Response_Error(writer, int(404), "sync account not found")
			return
		}
		var value_9 string = LogSafety_LogText(user.Value)
		slog.Error("set account alias", "user", value_9, "error", error)
		Response_Error(writer, int(500), "alias failed")
		return
	}
	var output AliasResponse = AliasResponse{}
	output.Status = "ok"
	output.Alias = alias
	Response_JSON(writer, int(200), output)
}

func AccountHttp_ProfileIcon(accounts Accounts, writer ResponseWriter, request *Request) {
	read := HttpBody_ReadJSON(writer, request, accounts.Configuration.MaxBodyBytes)
	if read.Error != nil {
		var value_0 ResponseWriter = writer
		Response_Error(value_0, int(400), StdErrorsGo_Message(read.Error))
		return
	}
	var decoded ProfileIconRequest = ProfileIconRequest{}
	var value_1 Error = StdJsonGo_Unmarshal(read.Value, &(decoded))
	if value_1 != nil {
		Response_Error(writer, int(400), "invalid json")
		return
	}
	var value_2 string = strings.ToLower(strings.TrimSpace(decoded.UserIDHash))
	decoded.UserIDHash = value_2
	user := AccountHttp_HeaderUser(request, decoded.UserIDHash)
	if user.Error != nil {
		var value_3 ResponseWriter = writer
		Response_Error(value_3, int(400), StdErrorsGo_Message(user.Error))
		return
	}
	var value_4 bool = AccountHttp_Authenticate(accounts, writer, request, user.Value)
	if !value_4 {
		return
	}
	var value_5 bool = AccountHttp_ValidIcon(decoded.ProfileIcon)
	if !value_5 {
		Response_Error(writer, int(400), "invalid profile_icon")
		return
	}
	var value_6 *Database = accounts.Database
	var value_7 Context = StdHttpGo_Context(request)
	error := AccountProfile_SetIcon(value_6, value_7, user.Value, decoded.ProfileIcon, accounts.MissingUser)
	if error != nil {
		if StdErrorsGo_Is(error, accounts.MissingUser) {
			Response_Error(writer, int(404), "sync account not found")
			return
		}
		var value_8 string = LogSafety_LogText(user.Value)
		slog.Error("set profile icon", "user", value_8, "error", error)
		Response_Error(writer, int(500), "profile icon failed")
		return
	}
	var output ProfileIconResponse = ProfileIconResponse{}
	output.Status = "ok"
	output.ProfileIcon = decoded.ProfileIcon
	Response_JSON(writer, int(200), output)
}

func AccountHttp_Export(accounts Accounts, writer ResponseWriter, request *Request) {
	user := HttpAuth_BearerUser(accounts.Database, request, accounts.Configuration.TokenSecret)
	if user.Authentication.Error != nil || user.Authentication.Status != 0 {
		HttpAuth_Respond(writer, accounts.Counters, user.Authentication)
		return
	}
	exported := AccountExport_Export(accounts.Database, StdHttpGo_Context(request), user.Value)
	if exported.Error != nil {
		if StdErrorsGo_Is(exported.Error, StdSqlGo_NoRows()) {
			Response_Error(writer, int(404), "sync account not found")
			return
		}
		slog.Error("export account", "user", LogSafety_LogText(user.Value), "error", exported.Error)
		Response_Error(writer, int(500), "export failed")
		return
	}
	Response_JSON(writer, int(200), exported.Value)
}
