// Code generated by zi2go from account_state.zi. DO NOT EDIT.
package main

import sql "database/sql"

// #import std_go_types
type zir_2688387c33a72186_ExecResult struct {
	Value Result
	Error Error
}

type TombstoneResult struct {
	Value bool
	Error Error
}

type zir_36dbc7eb84b27f76_VersionResult struct {
	Value int64
	Error Error
}

func AccountState_UpdateSeen(Transaction *Transaction, Context Context, Query string, UserID string, Seen string) zir_2688387c33a72186_ExecResult {
	var result zir_2688387c33a72186_ExecResult
	result.Value, result.Error = (*sql.Tx).ExecContext(Transaction, Context, Query, UserID, Seen)
	return result
}

func AccountState_EnsureSync(Transaction *Transaction, Context Context, Query string, UserID string) zir_2688387c33a72186_ExecResult {
	var result zir_2688387c33a72186_ExecResult
	result.Value, result.Error = (*sql.Tx).ExecContext(Transaction, Context, Query, UserID)
	return result
}

func AccountState_NextVersion(transaction *Transaction, context Context, userID string) zir_36dbc7eb84b27f76_VersionResult {
	var result zir_36dbc7eb84b27f76_VersionResult = zir_36dbc7eb84b27f76_VersionResult{}
	var value_0 zir_2688387c33a72186_ExecResult = AccountState_EnsureSync(transaction, context, "INSERT OR IGNORE INTO server_sync_state(user_id_hash,server_version) VALUES(?1,0)", userID)
	inserted := value_0
	result.Error = inserted.Error
	if result.Error != nil {
		return result
	}
	var value_1 zir_2688387c33a72186_ExecResult = AccountState_EnsureSync(transaction, context, "UPDATE server_sync_state SET server_version=server_version+1 WHERE user_id_hash=?1", userID)
	updated := value_1
	result.Error = updated.Error
	if result.Error != nil {
		return result
	}
	var value_2 *Row = (*sql.Tx).QueryRowContext(transaction, context, "SELECT server_version FROM server_sync_state WHERE user_id_hash=?1", userID)
	row := value_2
	var value_3 Error = (*sql.Row).Scan(row, &(result.Value))
	result.Error = value_3
	return result
}

func AccountState_Affected(value Result) int {
	affected := StdSqlGo_RowsAffected(value)
	if affected.Error != nil {
		return int(0)
	}
	return int(affected.Value)
}

func AccountState_Tombstoned(database *Database, context Context, userID string) TombstoneResult {
	var result TombstoneResult = TombstoneResult{}
	var count int = 0
	var value_0 *Row = (*sql.DB).QueryRowContext(database, context, "SELECT EXISTS(SELECT 1 FROM server_account_tombstones WHERE user_id_hash=?1)", userID)
	row := value_0
	var value_1 Error = (*sql.Row).Scan(row, &(count))
	result.Error = value_1
	result.Value = count != int(0)
	return result
}

func AccountState_Touch(transaction *Transaction, context Context, userID string, missingUser Error) Error {
	var value_0 zir_2688387c33a72186_ExecResult = AccountState_UpdateSeen(transaction, context, "UPDATE server_users SET last_seen_at=?2 WHERE user_id_hash=?1", userID, Timestamp_CanonicalNow())
	updated := value_0
	if updated.Error != nil {
		return updated.Error
	}
	affected := StdSqlGo_RowsAffected(updated.Value)
	if affected.Error != nil || int(affected.Value) == int(0) {
		return missingUser
	}
	var value_1 zir_2688387c33a72186_ExecResult = AccountState_EnsureSync(transaction, context, "INSERT OR IGNORE INTO server_sync_state(user_id_hash,server_version) VALUES(?1,0)", userID)
	inserted := value_1
	return inserted.Error
}

func AccountState_Upsert(transaction *Transaction, context Context, userID string, publicKey []uint8) Error {
	var arguments [3]Any
	arguments[0] = userID
	arguments[1] = publicKey
	var value_0 string = Timestamp_CanonicalNow()
	arguments[2] = value_0
	var value_1 string = "INSERT INTO server_users(user_id_hash,public_key) VALUES(?1,?2) ON CONFLICT(user_id_hash) DO UPDATE SET last_seen_at=?3"
	updated := StdSqlGo_ExecTx(transaction, context, value_1, arguments[0:3:3])
	if updated.Error != nil {
		return updated.Error
	}
	var value_2 zir_2688387c33a72186_ExecResult = AccountState_EnsureSync(transaction, context, "INSERT OR IGNORE INTO server_sync_state(user_id_hash,server_version) VALUES(?1,0)", userID)
	inserted := value_2
	return inserted.Error
}

func AccountState_Register(database *Database, context Context, userID string, publicKey []uint8) Error {
	opened := StdSqlGo_Begin(database, context, nil)
	if opened.Error != nil {
		return opened.Error
	}
	var arguments [1]Any
	arguments[0] = userID
	var value_0 zir_519e32da2199d006_ExecResult = StdSqlGo_ExecTx(opened.Value, context, "DELETE FROM server_account_tombstones WHERE user_id_hash=?1", arguments[0:1:1])
	removed := value_0
	if removed.Error != nil {
		cleanup_return_0 := removed.Error
		StdSqlGo_Rollback(opened.Value)
		return cleanup_return_0
	}
	error := AccountState_Upsert(opened.Value, context, userID, publicKey)
	if error != nil {
		cleanup_return_1 := error
		StdSqlGo_Rollback(opened.Value)
		return cleanup_return_1
	}
	cleanup_return_2 := StdSqlGo_Commit(opened.Value)
	StdSqlGo_Rollback(opened.Value)
	return cleanup_return_2
}
