// Code generated by zi2go from account_state.zi. DO NOT EDIT.
package main

import sql "database/sql"

// #import std_go_types
type zir_2688387c33a72186_ExecResult struct {
	Value Result
	Error Error
}

type TombstoneResult struct {
	Value bool
	Error Error
}

func AccountState_UpdateSeen(Transaction *Transaction, Context Context, Query string, UserID string, Seen string) zir_2688387c33a72186_ExecResult {
	var result zir_2688387c33a72186_ExecResult
	result.Value, result.Error = (*sql.Tx).ExecContext(Transaction, Context, Query, UserID, Seen)
	return result
}

func AccountState_EnsureSync(Transaction *Transaction, Context Context, Query string, UserID string) zir_2688387c33a72186_ExecResult {
	var result zir_2688387c33a72186_ExecResult
	result.Value, result.Error = (*sql.Tx).ExecContext(Transaction, Context, Query, UserID)
	return result
}

func AccountState_Tombstoned(database *Database, context Context, userID string) TombstoneResult {
	var result TombstoneResult = TombstoneResult{}
	var count int = 0
	var value_0 *Row = (*sql.DB).QueryRowContext(database, context, "SELECT EXISTS(SELECT 1 FROM server_account_tombstones WHERE user_id_hash=?1)", userID)
	row := value_0
	var value_1 Error = (*sql.Row).Scan(row, &(count))
	result.Error = value_1
	result.Value = count != int(0)
	return result
}

func AccountState_Touch(transaction *Transaction, context Context, userID string, missingUser Error) Error {
	var value_0 zir_2688387c33a72186_ExecResult = AccountState_UpdateSeen(transaction, context, "UPDATE server_users SET last_seen_at=?2 WHERE user_id_hash=?1", userID, Timestamp_CanonicalNow())
	updated := value_0
	if updated.Error != nil {
		return updated.Error
	}
	affected := StdSqlGo_RowsAffected(updated.Value)
	if affected.Error != nil || int(affected.Value) == int(0) {
		return missingUser
	}
	var value_1 zir_2688387c33a72186_ExecResult = AccountState_EnsureSync(transaction, context, "INSERT OR IGNORE INTO server_sync_state(user_id_hash,server_version) VALUES(?1,0)", userID)
	inserted := value_1
	return inserted.Error
}
