// Code generated by zi2go from account_keys.zi. DO NOT EDIT.
package main

import sql "database/sql"

// #import std_go_types
type AccountKeyResult struct {
	Value []uint8
	Found bool
	Error Error
}

func AccountKeys_PublicKey(database *Database, context Context, accountID string) AccountKeyResult {
	var result AccountKeyResult = AccountKeyResult{}
	var key []uint8 = nil
	var value_0 *Row = (*sql.DB).QueryRowContext(database, context, "SELECT public_key FROM server_users WHERE user_id_hash=?1", accountID)
	row := value_0
	error := (*sql.Row).Scan(row, &(key))
	var value_1 Error = error
	if StdErrorsGo_Is(value_1, StdSqlGo_NoRows()) {
		return result
	}
	if error != nil {
		result.Error = error
		return result
	}
	result.Value = key
	result.Found = true
	return result
}
