// Code generated by zi2go from account_lookup.zi. DO NOT EDIT.
package main

import strings "strings"

// #import std_go_types
type AccountResult struct {
	Value string
	Found bool
	Error Error
}

func AccountLookup_Resolve(database *Database, context Context, reference string) AccountResult {
	var result AccountResult = AccountResult{}
	reference = strings.ToLower(strings.TrimPrefix(strings.TrimSpace(reference), "@"))
	var arguments [1]Any
	arguments[0] = reference
	var destinations [1]Any
	if Identity_ValidUserID(reference) {
		result.Value = reference
		var exists int = 0
		destinations[0] = &(exists)
		var value_0 *Row = StdSqlGo_QueryRow(database, context, "SELECT EXISTS(SELECT 1 FROM server_users WHERE user_id_hash=?1)", arguments[0:1:1])
		row := value_0
		_ = row
		var value_1 Error = StdSqlGo_ScanRow(row, destinations[0:1:1])
		result.Error = value_1
		result.Found = exists != int(0)
		return result
	}
	var value_2 bool = Identity_ValidAccountAlias(reference)
	if !value_2 {
		return result
	}
	destinations[0] = &(result.Value)
	var value_3 *Row = StdSqlGo_QueryRow(database, context, "SELECT user_id_hash FROM server_users WHERE alias=?1", arguments[0:1:1])
	row := value_3
	_ = row
	var value_4 Error = StdSqlGo_ScanRow(row, destinations[0:1:1])
	result.Error = value_4
	var value_5 Error = result.Error
	if StdErrorsGo_Is(value_5, StdSqlGo_NoRows()) {
		result.Error = nil
		return result
	}
	result.Found = true
	return result
}
