// Code generated by zi2go from app_http.zi. DO NOT EDIT.
package main

import (
	slog "log/slog"
	strings "strings"
)

// #import std_go_types
// #import protocol
// #import manifest
type Registry struct {
	Database      *Database
	Configuration *Config
	Counters      *ServerMetrics
	Verify        VerifySignature
	ReplayError   Error
	MissingUser   Error
	ScopeNotOwned Error
}

type CollectionsResponse struct {
	Collections []AppCollection "json:\"collections\""
}

type StatusResponse struct {
	Status string "json:\"status\""
}

type zir_a9f2e3112734250a_ReplayCleanup func(*Database, Context, SignedTxEnvelope, *bool)

func AppHttp_CleanupAtReturn(Callback zir_a9f2e3112734250a_ReplayCleanup, Database *Database, Context Context, Transaction SignedTxEnvelope, Completed *bool) {
	Callback(Database, Context, Transaction, Completed)
}

func AppHttp_ForgetOnFailure(database *Database, context Context, transaction SignedTxEnvelope, completed *bool) {
	if !*(completed) {
		SignedTx_Forget(database, context, transaction)
	}
}

func AppHttp_Bearer(registry Registry, writer ResponseWriter, request *Request) UserAuthenticationResult {
	result := HttpAuth_BearerUser(registry.Database, request, registry.Configuration.TokenSecret)
	if result.Authentication.Error != nil || result.Authentication.Status != int(0) {
		HttpAuth_Respond(writer, registry.Counters, result.Authentication)
	}
	return result
}

func AppHttp_GrantFailure(writer ResponseWriter, user string, error Error, message string) {
	if StdErrorsGo_Is(error, StdSqlGo_NoRows()) {
		Response_Error(writer, int(404), "app not found")
		return
	}
	text := StdErrorsGo_Message(error)
	var value_0 bool = strings.Contains(text, "private")
	var value_1 bool = value_0
	if !value_1 {
		var value_2 bool = strings.Contains(text, "registered")
		value_1 = value_2
	}
	if value_1 {
		Response_Error(writer, int(400), text)
		return
	}
	slog.Error(message, "user", LogSafety_LogText(user), "error", error)
	Response_Error(writer, int(500), "app grant failed")
}

func AppHttp_ReadRegistration(writer ResponseWriter, request *Request, limit int64) AppDecodeResult {
	var result AppDecodeResult = AppDecodeResult{}
	body := HttpBody_ReadJSON(writer, request, limit)
	if body.Error != nil {
		result.Error = body.Error
		return result
	}
	return AppRegistration_Decode(body.Value)
}

func AppHttp_ReadSignedRegistration(writer ResponseWriter, request *Request, limit int64) SignedRegistrationResult {
	var result SignedRegistrationResult = SignedRegistrationResult{}
	body := HttpBody_ReadJSON(writer, request, limit)
	if body.Error != nil {
		result.Error = body.Error
		return result
	}
	return AppRegistration_DecodeSigned(body.Value)
}

func AppHttp_ReadGrant(writer ResponseWriter, request *Request, limit int64) GrantDecodeResult {
	var result GrantDecodeResult = GrantDecodeResult{}
	body := HttpBody_ReadJSON(writer, request, limit)
	if body.Error != nil {
		result.Error = body.Error
		return result
	}
	return AppRegistration_DecodeGrant(body.Value)
}

func AppHttp_ReadSignedGrant(writer ResponseWriter, request *Request, limit int64) SignedGrantDecodeResult {
	var result SignedGrantDecodeResult = SignedGrantDecodeResult{}
	body := HttpBody_ReadJSON(writer, request, limit)
	if body.Error != nil {
		result.Error = body.Error
		return result
	}
	return AppRegistration_DecodeSignedGrant(body.Value)
}

func AppHttp_AuthenticateAdmin(writer ResponseWriter, request *Request, expected string) bool {
	if expected == "" {
		Response_Error(writer, int(403), "admin registration disabled")
		return false
	}
	var value_0 [2]string
	value_0[0] = "X-Daochi-Admin"
	value_0[1] = "X-Ksync-Admin"
	names := value_0
	_ = names
	if HttpAuth_HeaderAlias(request, names[0:2:2]) != expected {
		Response_Error(writer, int(401), "admin token required")
		return false
	}
	return true
}

func AppHttp_List(registry Registry, writer ResponseWriter, request *Request) {
	if StdHttpGo_Method(request) == "POST" {
		AppHttp_Register(registry, writer, request)
		return
	}
	listed := AppStore_List(registry.Database, StdHttpGo_Context(request))
	if listed.Error != nil {
		slog.Error("list apps", "error", listed.Error)
		Response_Error(writer, int(500), "apps failed")
		return
	}
	var value AppRegistryResponse = AppRegistryResponse{}
	value.Apps = listed.Value
	Response_JSON(writer, int(200), value)
}

func AppHttp_Route(registry Registry, writer ResponseWriter, request *Request) {
	appID := strings.Trim(strings.TrimPrefix(StdUrlGo_Path(StdHttpGo_RequestURL(request)), "/api/v1/apps/"), "/")
	context := StdHttpGo_Context(request)
	if strings.HasSuffix(appID, "/collections") {
		appID = strings.Trim(strings.TrimSuffix(appID, "/collections"), "/")
		collections := AppStore_Collections(registry.Database, context, appID)
		if collections.Error != nil {
			slog.Error("app collections", "app", LogSafety_LogText(appID), "error", collections.Error)
			Response_Error(writer, int(500), "apps failed")
			return
		}
		if int64(len(collections.Value)) == 0 {
			exists := AppStore_Exists(registry.Database, context, appID)
			if exists.Error != nil {
				slog.Error("app exists", "app", LogSafety_LogText(appID), "error", exists.Error)
				Response_Error(writer, int(500), "apps failed")
				return
			}
			if !exists.Value {
				Response_Error(writer, int(404), "app not found")
				return
			}
		}
		var value CollectionsResponse = CollectionsResponse{}
		value.Collections = collections.Value
		Response_JSON(writer, int(200), value)
		return
	}
	if StdHttpGo_Method(request) == "PUT" {
		AppHttp_Register(registry, writer, request)
		return
	}
	var value_0 bool = Identity_ValidNamespace(appID)
	if !value_0 {
		Response_Error(writer, int(404), "app not found")
		return
	}
	app := AppStore_ByID(registry.Database, context, appID)
	if app.Error != nil {
		slog.Error("load app", "app", LogSafety_LogText(appID), "error", app.Error)
		Response_Error(writer, int(500), "apps failed")
		return
	}
	if !app.Found {
		Response_Error(writer, int(404), "app not found")
		return
	}
	Response_JSON(writer, int(200), app.Value)
}

func AppHttp_Register(registry Registry, writer ResponseWriter, request *Request) {
	var value_0 bool = AppHttp_AuthenticateAdmin(writer, request, registry.Configuration.AdminToken)
	if !value_0 {
		return
	}
	decoded := AppHttp_ReadRegistration(writer, request, registry.Configuration.MaxBodyBytes)
	if decoded.Error != nil {
		Response_Error(writer, int(400), StdErrorsGo_Message(decoded.Error))
		return
	}
	pathID := ""
	path := StdUrlGo_Path(StdHttpGo_RequestURL(request))
	if strings.HasPrefix(path, "/api/v1/apps/") {
		pathID = strings.Trim(strings.TrimPrefix(path, "/api/v1/apps/"), "/")
	}
	if pathID != "" && pathID != decoded.Value.AppID {
		Response_Error(writer, int(400), "app_id path mismatch")
		return
	}
	context := StdHttpGo_Context(request)
	error := AppStore_Upsert(registry.Database, context, decoded.Value)
	if error != nil {
		slog.Error("register app", "app", LogSafety_LogText(decoded.Value.AppID), "error", error)
		Response_Error(writer, int(500), "app registration failed")
		return
	}
	app := AppStore_ByID(registry.Database, context, decoded.Value.AppID)
	if app.Error != nil {
		slog.Error("load registered app", "app", LogSafety_LogText(decoded.Value.AppID), "error", app.Error)
		Response_Error(writer, int(500), "app registration failed")
		return
	}
	Response_JSON(writer, int(200), app.Value)
}

func AppHttp_RegisterSigned(registry Registry, writer ResponseWriter, request *Request) {
	decoded := AppHttp_ReadSignedRegistration(writer, request, registry.Configuration.MaxBodyBytes)
	if decoded.Error != nil {
		Response_Error(writer, int(400), StdErrorsGo_Message(decoded.Error))
		return
	}
	value := decoded.Value
	verified := AppRegistration_Verify(value, registry.Configuration.NodeRegistryPublicKey)
	if verified.Authentication.Error != nil || verified.Authentication.Status != int(0) {
		HttpAuth_Respond(writer, registry.Counters, verified.Authentication)
		return
	}
	context := StdHttpGo_Context(request)
	error := AppStore_UpsertSignedManifest(registry.Database, context, value.Manifest, verified.Value, verified.Hash, value.ManifestSignature, value.ApprovalSignature)
	if error != nil {
		slog.Error("register signed app manifest", "app", LogSafety_LogText(value.Manifest.AppID), "error", error)
		Response_Error(writer, int(500), "app registration failed")
		return
	}
	app := AppStore_ByID(registry.Database, context, value.Manifest.AppID)
	if app.Error != nil {
		slog.Error("load signed app manifest", "app", LogSafety_LogText(value.Manifest.AppID), "error", app.Error)
		Response_Error(writer, int(500), "app registration failed")
		return
	}
	Response_JSON(writer, int(200), app.Value)
}

func AppHttp_Grants(registry Registry, writer ResponseWriter, request *Request) {
	user := AppHttp_Bearer(registry, writer, request)
	if user.Authentication.Error != nil || user.Authentication.Status != int(0) {
		return
	}
	context := StdHttpGo_Context(request)
	if StdHttpGo_Method(request) == "POST" {
		decoded := AppHttp_ReadGrant(writer, request, registry.Configuration.MaxBodyBytes)
		if decoded.Error != nil {
			Response_Error(writer, int(400), StdErrorsGo_Message(decoded.Error))
			return
		}
		created := AppGrants_Create(registry.Database, context, user.Value, decoded.Value, registry.MissingUser)
		if created.Error != nil {
			AppHttp_GrantFailure(writer, user.Value, created.Error, "create app grant")
			return
		}
		Response_JSON(writer, int(201), created.Value)
		return
	}
	listed := AppGrants_List(registry.Database, context, user.Value)
	if listed.Error != nil {
		slog.Error("list app grants", "user", LogSafety_LogText(user.Value), "error", listed.Error)
		Response_Error(writer, int(500), "app grants failed")
		return
	}
	var value AppGrantsResponse = AppGrantsResponse{}
	value.Grants = listed.Value
	Response_JSON(writer, int(200), value)
}

func AppHttp_GrantSigned(registry Registry, writer ResponseWriter, request *Request) {
	user := AppHttp_Bearer(registry, writer, request)
	if user.Authentication.Error != nil || user.Authentication.Status != int(0) {
		return
	}
	decoded := AppHttp_ReadSignedGrant(writer, request, registry.Configuration.MaxBodyBytes)
	if decoded.Error != nil {
		Response_Error(writer, int(400), StdErrorsGo_Message(decoded.Error))
		return
	}
	value := decoded.Value
	encoded := StdJsonGo_Marshal(value.Grant)
	if encoded.Error != nil {
		Response_Error(writer, int(400), "invalid app grant")
		return
	}
	hash := Signing_SHA256Hex(encoded.Value)
	if value.Tx.BodySHA256 != "" && value.Tx.BodySHA256 != hash {
		Response_Error(writer, int(400), "signed transaction body hash must cover grant payload")
		return
	}
	if value.Tx.BodySHA256 == "" {
		value.Tx.BodySHA256 = hash
	}
	context := StdHttpGo_Context(request)
	verified := SignedTx_Verify(registry.Database, context, request, encoded.Value, value.Tx, user.Value, value.Grant.TargetAppID, registry.Verify, registry.ReplayError)
	if verified.Error != nil || verified.Status != int(0) {
		HttpAuth_Respond(writer, registry.Counters, verified)
		return
	}
	completed := false
	var value_4 zir_a9f2e3112734250a_ReplayCleanup = func(value_0 *Database, value_1 Context, value_2 SignedTxEnvelope, value_3 *bool) {
		AppHttp_ForgetOnFailure(value_0, value_1, value_2, value_3)
	}
	defer AppHttp_CleanupAtReturn(value_4, registry.Database, context, value.Tx, &(completed))
	created := AppGrants_Create(registry.Database, context, user.Value, value.Grant, registry.MissingUser)
	if created.Error != nil {
		AppHttp_GrantFailure(writer, user.Value, created.Error, "create signed app grant")
		return
	}
	completed = true
	Response_JSON(writer, int(201), created.Value)
}

func AppHttp_GrantRoute(registry Registry, writer ResponseWriter, request *Request) {
	user := AppHttp_Bearer(registry, writer, request)
	if user.Authentication.Error != nil || user.Authentication.Status != int(0) {
		return
	}
	id := strings.Trim(strings.TrimPrefix(StdUrlGo_Path(StdHttpGo_RequestURL(request)), "/api/v1/account/app-grants/"), "/")
	if id == "" {
		Response_Error(writer, int(404), "app grant not found")
		return
	}
	error := AppGrants_Revoke(registry.Database, StdHttpGo_Context(request), user.Value, id)
	if error != nil {
		if StdErrorsGo_Is(error, StdSqlGo_NoRows()) {
			Response_Error(writer, int(404), "app grant not found")
			return
		}
		slog.Error("revoke app grant", "user", LogSafety_LogText(user.Value), "grant", LogSafety_LogText(id), "error", error)
		Response_Error(writer, int(500), "app grant failed")
		return
	}
	var value StatusResponse = StatusResponse{}
	value.Status = "revoked"
	Response_JSON(writer, int(200), value)
}

func AppHttp_Records(registry Registry, writer ResponseWriter, request *Request) {
	user := AppHttp_Bearer(registry, writer, request)
	if user.Authentication.Error != nil || user.Authentication.Status != int(0) {
		return
	}
	query := StdUrlGo_Query(StdHttpGo_RequestURL(request))
	source := strings.TrimSpace(StdUrlGo_Value(query, "source_app_id"))
	target := strings.TrimSpace(StdUrlGo_Value(query, "target_app_id"))
	prefix := strings.TrimSpace(StdUrlGo_Value(query, "collection_prefix"))
	var value_0 bool = Identity_ValidNamespace(source)
	var value_1 bool = !value_0
	if !value_1 {
		var value_2 bool = Identity_ValidNamespace(target)
		value_1 = !value_2
	}
	var value_3 bool = value_1
	if !value_3 {
		var value_4 bool = Scope_ValidCollectionPrefix(prefix)
		value_3 = !value_4
	}
	if value_3 {
		Response_Error(writer, int(400), "invalid app records query")
		return
	}
	header := SignedTx_ReadHeader(request)
	if header.Authentication.Error != nil || header.Authentication.Status != int(0) {
		HttpAuth_Respond(writer, registry.Counters, header.Authentication)
		return
	}
	context := StdHttpGo_Context(request)
	var emptyBody []uint8 = nil
	verified := SignedTx_Verify(registry.Database, context, request, emptyBody, header.Value, user.Value, target, registry.Verify, registry.ReplayError)
	if verified.Error != nil || verified.Status != int(0) {
		HttpAuth_Respond(writer, registry.Counters, verified)
		return
	}
	completed := false
	var value_9 zir_a9f2e3112734250a_ReplayCleanup = func(value_5 *Database, value_6 Context, value_7 SignedTxEnvelope, value_8 *bool) {
		AppHttp_ForgetOnFailure(value_5, value_6, value_7, value_8)
	}
	defer AppHttp_CleanupAtReturn(value_9, registry.Database, context, header.Value, &(completed))
	records := AppGrants_AuthorizedRecords(registry.Database, context, user.Value, source, target, prefix, registry.ScopeNotOwned, registry.MissingUser)
	if records.Error != nil {
		if StdErrorsGo_Is(records.Error, registry.MissingUser) {
			Response_Error(writer, int(403), "app grant required")
			return
		}
		if StdErrorsGo_Is(records.Error, registry.ScopeNotOwned) {
			Response_Error(writer, int(400), "source app does not own collection scope")
			return
		}
		if StdErrorsGo_Is(records.Error, StdSqlGo_NoRows()) {
			Response_Error(writer, int(404), "app not found")
			return
		}
		slog.Error("read app records", "user", LogSafety_LogText(user.Value), "source_app", LogSafety_LogText(source), "target_app", LogSafety_LogText(target), "error", records.Error)
		Response_Error(writer, int(500), "app records failed")
		return
	}
	completed = true
	var value AppRecordsResponse = AppRecordsResponse{}
	value.Records = records.Value
	Response_JSON(writer, int(200), value)
}
