// Code generated by zi2go from atomic_go.zi. DO NOT EDIT.
package main

import atomic "sync/atomic"

type Uint64 = atomic.Uint64

func AtomicGo_Add(value *Uint64, delta uint64) uint64 {
	return (*atomic.Uint64).Add(value, uint64(delta))
}

func AtomicGo_Load(value *Uint64) uint64 {
	return (*atomic.Uint64).Load(value)
}
