// Code generated by zi2go from authentication.zi. DO NOT EDIT.
package main

// #import std_go_types
type VerifySignature func([]uint8, []uint8, []uint8) bool

type AuthenticationResult struct {
	Status  int
	Message string
	Error   Error
}

type ConvertError func(AuthenticationResult) Error

func Authentication_Failure(status int, message string) AuthenticationResult {
	var result AuthenticationResult = AuthenticationResult{}
	result.Status = status
	result.Message = message
	return result
}

func Authentication_NativeFailure(error Error) AuthenticationResult {
	var result AuthenticationResult = AuthenticationResult{}
	result.Error = error
	return result
}
