// Code generated by zi2go from challenge.zi. DO NOT EDIT.
package main

// #import map_go
// #import option
// #import sync_go
// #import go_types
// #import random_go
// #import text_go
// #import codec
type Challenge struct {
	Nonce     []uint8
	ExpiresAt Time
}

type __type_ad39223df1e08a9f = map[string]Challenge

type ChallengeStore struct {
	Mu     Mutex
	Ttl    Duration
	ByUser __type_ad39223df1e08a9f
}

type IssuedChallenge struct {
	Nonce []uint8
	Error Error
}

type ConsumedChallenge struct {
	Nonce []uint8
	Found bool
}

type ChallengePreview struct {
	Nonce string
	Found bool
}

type __type_baef8676c03ac025 struct {
	HasValue bool
	Value    Challenge
}

func Challenge_Prune(store *ChallengeStore, now Time) {
	var value_0 __type_ad39223df1e08a9f = store.ByUser
	var value_1 []string = make([]string, 0, len(value_0))
	for value_2 := range value_0 {
		value_1 = append(value_1, value_2)
	}
	keys := value_1
	for _, key := range keys {
		var value_3 __type_ad39223df1e08a9f = store.ByUser
		var value_4 string = key
		var value_5 Challenge = value_3[value_4]
		item := value_5
		if TimeGo_After(now, item.ExpiresAt) {
			var value_6 __type_ad39223df1e08a9f = store.ByUser
			var value_7 string = key
			delete(value_6, value_7)
		}
	}
}

func Challenge_Consumed(item Challenge, now Time) ConsumedChallenge {
	var result ConsumedChallenge = ConsumedChallenge{}
	if TimeGo_After(now, item.ExpiresAt) {
		return result
	}
	result.Nonce = item.Nonce
	result.Found = true
	return result
}

func Challenge_New(ttl Duration) *ChallengeStore {
	store := new(ChallengeStore)
	store.Ttl = ttl
	var value_0 *__type_ad39223df1e08a9f = &(store.ByUser)
	if (*value_0) == nil {
		(*value_0) = make(__type_ad39223df1e08a9f)
	}
	return store
}

func Challenge_Issue(store *ChallengeStore, userID string) IssuedChallenge {
	var result IssuedChallenge = IssuedChallenge{}
	nonce := make([]uint8, int(int(32)))
	random := RandomGo_Fill(nonce)
	if random.Error != nil {
		result.Error = random.Error
		return result
	}
	SyncGo_Lock(&(store.Mu))
	var value_0 *ChallengeStore = store
	Challenge_Prune(value_0, TimeGo_Now())
	var item Challenge = Challenge{}
	item.Nonce = nonce
	var value_1 Time = TimeGo_Now()
	var value_2 Time = TimeGo_Add(value_1, store.Ttl)
	item.ExpiresAt = value_2
	var value_3 *__type_ad39223df1e08a9f = &(store.ByUser)
	var value_4 string = userID
	var value_5 Challenge = item
	if (*value_3) == nil {
		(*value_3) = make(__type_ad39223df1e08a9f)
	}
	(*value_3)[value_4] = value_5
	result.Nonce = nonce
	cleanup_return_0 := result
	SyncGo_Unlock(&(store.Mu))
	return cleanup_return_0
}

func Challenge_Consume(store *ChallengeStore, userID string) ConsumedChallenge {
	SyncGo_Lock(&(store.Mu))
	var value_0 __type_ad39223df1e08a9f = store.ByUser
	var value_1 string = userID
	var value_2 __type_baef8676c03ac025 = __type_baef8676c03ac025{}
	value_2.Value, value_2.HasValue = value_0[value_1]
	item := value_2
	var result ConsumedChallenge = ConsumedChallenge{}
	if !item.HasValue {
		cleanup_return_0 := result
		SyncGo_Unlock(&(store.Mu))
		return cleanup_return_0
	}
	var value_3 __type_ad39223df1e08a9f = store.ByUser
	var value_4 string = userID
	delete(value_3, value_4)
	var value_5 Challenge = item.Value
	cleanup_return_1 := Challenge_Consumed(value_5, TimeGo_Now())
	SyncGo_Unlock(&(store.Mu))
	return cleanup_return_1
}

func Challenge_PeekBase64(store *ChallengeStore, userID string) ChallengePreview {
	SyncGo_Lock(&(store.Mu))
	var value_0 __type_ad39223df1e08a9f = store.ByUser
	var value_1 string = userID
	var value_2 __type_baef8676c03ac025 = __type_baef8676c03ac025{}
	value_2.Value, value_2.HasValue = value_0[value_1]
	item := value_2
	var result ChallengePreview = ChallengePreview{}
	var value_3 bool = !item.HasValue
	var value_4 bool = value_3
	if !value_4 {
		var value_5 Time = TimeGo_Now()
		var value_6 bool = TimeGo_After(value_5, item.Value.ExpiresAt)
		value_4 = value_6
	}
	if value_4 {
		cleanup_return_0 := result
		SyncGo_Unlock(&(store.Mu))
		return cleanup_return_0
	}
	var value_7 string = TextGo_FromBytes(item.Value.Nonce)
	encoded := Codec_EncodeBase64(value_7, false, true)
	result.Nonce = encoded.Value
	result.Found = true
	cleanup_return_1 := result
	SyncGo_Unlock(&(store.Mu))
	return cleanup_return_1
}
