// Code generated by zi2go from collection_scope.zi. DO NOT EDIT.
package main

import (
	sql "database/sql"
	strings "strings"
)

// #import std_go_types
type CollectionMatcher struct {
	AppID       string
	DisplayName string
	Prefix      string
	MatchPrefix string
	Wildcard    bool
	Specificity int
}

type MatchersResult struct {
	Value []CollectionMatcher
	Error Error
}

type zir_70d0ae44a4ff9ae6_RowsResult struct {
	Value *Rows
	Error Error
}

func CollectionScope_Query(Database *Database, Context Context, Query string) zir_70d0ae44a4ff9ae6_RowsResult {
	var result zir_70d0ae44a4ff9ae6_RowsResult
	result.Value, result.Error = (*sql.DB).QueryContext(Database, Context, Query)
	return result
}

const MatchersSQL = "SELECT a.app_id,a.display_name,c.collection_prefix\nFROM server_apps a\nJOIN server_app_collections c ON c.app_id=a.app_id\nORDER BY a.app_id,c.collection_prefix\n"

func CollectionScope_Load(database *Database, context Context) MatchersResult {
	var result MatchersResult = MatchersResult{}
	var value_0 string = "SELECT a.app_id,a.display_name,c.collection_prefix\nFROM server_apps a\nJOIN server_app_collections c ON c.app_id=a.app_id\nORDER BY a.app_id,c.collection_prefix\n"
	queried := CollectionScope_Query(database, context, value_0)
	result.Error = queried.Error
	if result.Error != nil {
		return result
	}
	rows := queried.Value
	defer (*sql.Rows).Close(rows)
	var values []CollectionMatcher = nil
	for StdSqlGo_Next(rows) {
		var matcher CollectionMatcher = CollectionMatcher{}
		var value_1 Error = (*sql.Rows).Scan(rows, &(matcher.AppID), &(matcher.DisplayName), &(matcher.Prefix))
		result.Error = value_1
		if result.Error != nil {
			return result
		}
		var value_2 string = strings.TrimSuffix(matcher.Prefix, "*")
		matcher.MatchPrefix = value_2
		matcher.Wildcard = matcher.MatchPrefix != matcher.Prefix
		matcher.Specificity = int(int64(len(matcher.MatchPrefix)))
		values = append(values, matcher)
	}
	var value_3 Error = StdSqlGo_RowsError(rows)
	result.Error = value_3
	if result.Error != nil {
		return result
	}
	result.Value = values
	return result
}

func CollectionScope_Best(collection string, matchers []CollectionMatcher) *CollectionMatcher {
	var best *CollectionMatcher = nil
	var index int64 = 0
	for index < int64(len(matchers)) {
		matcher := &(matchers[index])
		matches := collection == matcher.MatchPrefix
		if matcher.Wildcard {
			matches = strings.HasPrefix(collection, matcher.MatchPrefix)
		}
		if matches && (best == nil || matcher.Specificity > best.Specificity) {
			best = matcher
		}
		index++
	}
	return best
}
