// Code generated by zi2go from config_values.zi. DO NOT EDIT.
package main

import (
	strconv "strconv"
	strings "strings"
)

// #import protocol
// #import map_go
// #import go_types
type CutResult struct {
	Before string
	After  string
	Found  bool
}

type IntegerResult struct {
	Value int64
	Error Error
}

type __type_c922d3f56b74fd5a = map[string]bool

type __type_cd75cecb5feef7fa = map[string]TokenProduct

func ConfigValues_Cut(Value string, Separator string) CutResult {
	var result CutResult
	result.Before, result.After, result.Found = strings.Cut(Value, Separator)
	return result
}

func ConfigValues_ParseInt(Value string, Base int, Bits int) IntegerResult {
	var result IntegerResult
	result.Value, result.Error = strconv.ParseInt(Value, Base, Bits)
	return result
}

func ConfigValues_Bool(value string, fallback bool) bool {
	normalized := strings.ToLower(strings.TrimSpace(value))
	if normalized == "" {
		return fallback
	}
	return normalized == "1" || normalized == "true" || normalized == "yes" || normalized == "on"
}

func ConfigValues_SyncDirection(value string) string {
	normalized := strings.ToLower(strings.TrimSpace(value))
	var value_0 bool = normalized == "pull" || normalized == "receive" || normalized == "from_peer" || normalized == "from-peer"
	if value_0 {
		return "pull"
	}
	var value_1 bool = normalized == "push" || normalized == "send" || normalized == "to_peer" || normalized == "to-peer"
	if value_1 {
		return "push"
	}
	var value_2 bool = normalized == "bidirectional" || normalized == "both" || normalized == "mirror" || normalized == "readwrite"
	if value_2 || normalized == "read-write" {
		return "bidirectional"
	}
	var value_3 bool = normalized == "none" || normalized == "off" || normalized == "disabled" || normalized == "false" || normalized == "0"
	if value_3 || normalized == "no" {
		return "none"
	}
	return normalized
}

func ConfigValues_SyncList(value string) []string {
	normalized := strings.ReplaceAll(strings.ReplaceAll(value, "|", "+"), " ", "+")
	var seen __type_c922d3f56b74fd5a = *new(__type_c922d3f56b74fd5a)
	var result []string = nil
	items := strings.Split(normalized, "+")
	for _, item := range items {
		entry := strings.TrimSpace(item)
		var value_0 bool = entry == ""
		if !value_0 {
			var value_1 __type_c922d3f56b74fd5a = seen
			var value_2 string = entry
			var value_3 bool = value_1[value_2]
			value_0 = value_3
		}
		if value_0 {
			continue
		}
		var value_4 *__type_c922d3f56b74fd5a = &(seen)
		var value_5 string = entry
		var value_6 bool = true
		if (*value_4) == nil {
			(*value_4) = make(__type_c922d3f56b74fd5a)
		}
		(*value_4)[value_5] = value_6
		result = append(result, entry)
	}
	return result
}

func ConfigValues_SyncPolicy(fields []string) *NodeSyncPolicy {
	var policy NodeSyncPolicy = NodeSyncPolicy{}
	for _, field := range fields {
		parts := ConfigValues_Cut(strings.TrimSpace(field), "=")
		if !parts.Found {
			continue
		}
		key := strings.ToLower(strings.TrimSpace(parts.Before))
		value := strings.TrimSpace(parts.After)
		if key == "sync" || key == "mode" || key == "direction" {
			var value_0 string = ConfigValues_SyncDirection(value)
			policy.Direction = value_0
		} else if key == "app" || key == "apps" || key == "app_id" || key == "app_ids" {
			var value_1 []string = ConfigValues_SyncList(value)
			policy.Apps = value_1
		} else if key == "collection" || key == "collections" {
			var value_2 []string = ConfigValues_SyncList(value)
			policy.Collections = value_2
		} else if key == "space" || key == "spaces" || key == "space_id" || key == "space_ids" {
			var value_3 []string = ConfigValues_SyncList(value)
			policy.Spaces = value_3
		} else if key == "data" || key == "type" || key == "types" {
			var value_4 []string = ConfigValues_SyncList(value)
			policy.Data = value_4
		} else if key == "enabled" {
			var value_5 bool = ConfigValues_Bool(value, true)
			if !value_5 {
				policy.Direction = "none"
			}
		}
	}
	var value_6 bool = policy.Direction == "" && int64(len(policy.Apps)) == 0 && int64(len(policy.Collections)) == 0 && int64(len(policy.Spaces)) == 0
	if value_6 && int64(len(policy.Data)) == 0 {
		return nil
	}
	if policy.Direction == "" {
		policy.Direction = "bidirectional"
	}
	result := new(NodeSyncPolicy)
	*(result) = policy
	return result
}

func ConfigValues_Peers(raw string) []NodePeer {
	normalized := strings.TrimSpace(raw)
	var result []NodePeer = nil
	if normalized == "" {
		return result
	}
	var seen __type_c922d3f56b74fd5a = *new(__type_c922d3f56b74fd5a)
	items := strings.Split(normalized, ",")
	for it_index := int64(0); it_index < int64(len(items)); it_index++ {
		rawItem := items[it_index]
		item := strings.TrimSpace(rawItem)
		if item == "" {
			continue
		}
		name := ""
		url := item
		var policyFields []string = nil
		fields := strings.Split(item, ";")
		if int64(len(fields)) > 1 {
			url = strings.TrimSpace(fields[0])
			if 1 < 0 || int64(len(fields)) < 1 || int64(len(fields)) > int64(len(fields)) {
				panic("slice range out of bounds")
			}
			policyFields = fields[1:int64(len(fields)):int64(len(fields))]
		}
		named := ConfigValues_Cut(url, "=")
		if !named.Found {
			named = ConfigValues_Cut(url, "|")
		}
		if named.Found {
			name = strings.TrimSpace(named.Before)
			url = named.After
		}
		url = strings.TrimRight(strings.TrimSpace(url), "/")
		var value_1 bool = url == ""
		var value_2 bool = value_1
		if !value_2 {
			var value_3 __type_c922d3f56b74fd5a = seen
			var value_4 string = url
			var value_5 bool = value_3[value_4]
			value_2 = value_5
		}
		if value_2 {
			continue
		}
		var value_6 *__type_c922d3f56b74fd5a = &(seen)
		var value_7 string = url
		var value_8 bool = true
		if (*value_6) == nil {
			(*value_6) = make(__type_c922d3f56b74fd5a)
		}
		(*value_6)[value_7] = value_8
		var peer NodePeer = NodePeer{}
		peer.Name = name
		peer.URL = url
		var value_9 *NodeSyncPolicy = ConfigValues_SyncPolicy(policyFields)
		peer.Sync = value_9
		result = append(result, peer)
	}
	return result
}

func ConfigValues_Products(raw string) __type_cd75cecb5feef7fa {
	var result __type_cd75cecb5feef7fa = *new(__type_cd75cecb5feef7fa)
	var value_0 *__type_cd75cecb5feef7fa = &(result)
	if (*value_0) == nil {
		(*value_0) = make(__type_cd75cecb5feef7fa)
	}
	items := strings.Split(raw, ",")
	for _, item := range items {
		parts := strings.Split(strings.TrimSpace(item), ":")
		if int64(len(parts)) < 2 || int64(len(parts)) > 3 || parts[0] == "" {
			continue
		}
		units := ConfigValues_ParseInt(parts[1], int(int(10)), int(int(64)))
		if units.Error != nil || units.Value <= 0 {
			continue
		}
		var product TokenProduct = TokenProduct{}
		product.ProductID = parts[0]
		product.TokenUnits = units.Value
		if int64(len(parts)) == 3 {
			atomic := ConfigValues_ParseInt(parts[2], int(int(10)), int(int(64)))
			if atomic.Error == nil && atomic.Value > 0 {
				product.MoneroAtomicAmount = atomic.Value
			}
		}
		var value_1 *__type_cd75cecb5feef7fa = &(result)
		var value_2 string = product.ProductID
		var value_3 TokenProduct = product
		if (*value_1) == nil {
			(*value_1) = make(__type_cd75cecb5feef7fa)
		}
		(*value_1)[value_2] = value_3
	}
	return result
}
