// Code generated by zi2go from delegated_ws.zi. DO NOT EDIT.
package main

import (
	sql "database/sql"
	net "net"
	time "time"
)

// #import std_go_types
type CollectionEvent struct {
	Type       string "json:\"type\""
	Collection string "json:\"collection\""
	Version    int64  "json:\"version\""
}

type CollectionVersion struct {
	Value  int64
	Active bool
}

type zir_3ff5d436043035f5_ReaderWorker func(Connection, *BufferedReader, CancelFunc)

type zir_7deb62481a0eca37_CancelCallback func(CancelFunc)

func DelegatedWs_BufferedReaderFor(Buffer *BufferedConnection) *BufferedReader {
	return Buffer.Reader
}

func DelegatedWs_SpawnReader(Callback zir_3ff5d436043035f5_ReaderWorker, Connection Connection, Reader *BufferedReader, Cancel CancelFunc) {
	go Callback(Connection, Reader, Cancel)
}

func DelegatedWs_CancelAtReturn(Callback zir_7deb62481a0eca37_CancelCallback, Cancel CancelFunc) {
	Callback(Cancel)
}

func DelegatedWs_ReadLoop(connection Connection, reader *BufferedReader, cancel CancelFunc) {
	for true {
		(net.Conn).SetReadDeadline(connection, StdTimeGo_Add(StdTimeGo_Now(), Duration(90000000000)))
		var value_0 Frame = Websocket_ReadClientFrame(reader)
		if value_0.Error != nil {
			StdContextGo_Cancel(cancel)
			return
		}
	}
}

func DelegatedWs_Current(value Authorizations, context Context, sessionID string, grantID string, collection string) CollectionVersion {
	var result CollectionVersion = CollectionVersion{}
	opened := StdSqlGo_Begin(value.Database, context, nil)
	if opened.Error != nil {
		return result
	}
	transaction := opened.Value
	defer (*sql.Tx).Rollback(transaction)
	now := StdTimeGo_Unix(StdTimeGo_Now())
	var value_0 [3]Any
	value_0[0] = sessionID
	value_0[1] = grantID
	value_0[2] = now
	arguments := value_0
	var value_1 string = "UPDATE server_authorization_sessions SET session_id=session_id WHERE session_id=?1 AND grant_id=?2 AND expires_at>?3"
	locked := StdSqlGo_ExecTx(transaction, context, value_1, arguments[0:3:3])
	if locked.Error != nil {
		return result
	}
	changed := StdSqlGo_RowsAffected(locked.Value)
	if changed.Error != nil || changed.Value != 1 {
		return result
	}
	active := Authorization_ActiveGrant(transaction, context, grantID, value.NodeID, value.Configuration.BaseURL, now)
	var value_2 bool = active.Authentication.Error != nil || active.Authentication.Status != 0
	var value_3 bool = value_2
	if !value_3 {
		var value_4 bool = Authorization_Allowed(active.Value, collection, false)
		value_3 = !value_4
	}
	if value_3 {
		return result
	}
	arguments[0] = active.Value.AccountID
	arguments[1] = collection
	{
		value_5 := active.Value.Scopes[:]
		if int64(0) < 0 || int64(int64(len(value_5))) < int64(0) || int64(int64(len(value_5))) > int64(len(value_5)) {
			panic("slice range out of bounds")
		}
		loop_view_23 := value_5[0:int64(len(value_5)):int64(len(value_5))]
		loop_count_23 := int64(len(loop_view_23))
		var loop_cursor_23 int64 = 0
		for loop_cursor_23 < loop_count_23 {
			loop_index_23 := loop_cursor_23
			scope := loop_view_23[loop_index_23]
			if scope.Collection == collection {
				arguments[2] = scope.KeyID
			}
			loop_cursor_23++
		}
	}
	var value_6 [1]Any
	value_6[0] = &(result.Value)
	destinations := value_6
	_ = destinations
	var value_7 string = "SELECT COALESCE(MAX(server_version),0) FROM server_encrypted_records WHERE user_id_hash=?1 AND collection=?2 AND key_id=?3"
	row := StdSqlGo_QueryRowTx(transaction, context, value_7, arguments[0:3:3])
	var value_8 Error = StdSqlGo_ScanRow(row, destinations[0:1:1])
	var value_9 bool = value_8 != nil
	var value_10 bool = value_9
	if !value_10 {
		var value_11 Error = StdSqlGo_Commit(transaction)
		value_10 = (value_11 != nil)
	}
	if value_10 {
		return result
	}
	result.Active = true
	return result
}

func DelegatedWs_Handle(value Authorizations, writer ResponseWriter, request *Request) {
	var value_0 bool = AuthorizationHttp_Guard(value, writer, request)
	if !value_0 {
		return
	}
	var value_1 bool = Session_SocketHeaders(request)
	if !value_1 {
		Response_Error(writer, 401, "delegate socket proof required")
		return
	}
	context := StdHttpGo_Context(request)
	opened := StdSqlGo_Begin(value.Database, context, nil)
	if opened.Error != nil {
		Response_Error(writer, 503, "delegate socket unavailable")
		return
	}
	transaction := opened.Value
	defer (*sql.Tx).Rollback(transaction)
	var empty [0]uint8
	_ = empty
	var value_2 []uint8
	if int64(0) < 0 || int64(int64(len(value_2))) < int64(0) || int64(int64(len(value_2))) > int64(len(value_2)) {
		panic("slice range out of bounds")
	}
	principal := Session_AuthenticateTx(transaction, context, request, value_2[0:int64(len(value_2)):int64(len(value_2))], value.NodeID, value.Configuration.BaseURL)
	if principal.Authentication.Error != nil || principal.Authentication.Status != 0 {
		HttpAuth_Respond(writer, value.Counters, principal.Authentication)
		return
	}
	collection := StdUrlGo_Value(StdUrlGo_Query(StdHttpGo_RequestURL(request)), "collection")
	var value_3 bool = Authorization_Allowed(principal.Grant, collection, false)
	if !value_3 {
		Response_Error(writer, 403, "delegate socket scope mismatch")
		return
	}
	var proof RequestProof = RequestProof{}
	decoded := DelegatedWs_ReadProof(request, &(proof))
	var value_4 bool = !decoded
	if !value_4 {
		var value_5 Error = StdSqlGo_Commit(transaction)
		value_4 = (value_5 != nil)
	}
	if value_4 {
		Response_Error(writer, 503, "delegate socket unavailable")
		return
	}
	accepted := Websocket_Accept(writer, request)
	if accepted.Error != nil {
		return
	}
	defer (net.Conn).Close(accepted.Connection)
	child := StdContextGo_WithCancel(context)
	defer DelegatedWs_CancelAtReturn(func(value_6 CancelFunc) { StdContextGo_Cancel(value_6) }, child.Cancel)
	var value_10 zir_3ff5d436043035f5_ReaderWorker = func(value_7 Connection, value_8 *BufferedReader, value_9 CancelFunc) {
		DelegatedWs_ReadLoop(value_7, value_8, value_9)
	}
	DelegatedWs_SpawnReader(value_10, accepted.Connection, DelegatedWs_BufferedReaderFor(accepted.Buffer), child.Cancel)
	ticker := StdTimeGo_NewTicker(Duration(500000000))
	defer (*time.Ticker).Stop(ticker)
	var version int64 = -1
	var ticks int64 = 0
	for true {
		current := DelegatedWs_Current(value, child.Value, proof.SessionID, principal.Grant.GrantID, collection)
		if !current.Active {
			return
		}
		(net.Conn).SetWriteDeadline(accepted.Connection, StdTimeGo_Add(StdTimeGo_Now(), Duration(10000000000)))
		if current.Value != version {
			event := CollectionEvent{Type: "collection_changed", Collection: collection, Version: current.Value}
			var value_11 Error = Websocket_WriteJSON(accepted.Connection, event)
			if value_11 != nil {
				return
			}
			version = current.Value
		} else if ticks%60 == 0 {
			var value_12 []uint8
			if int64(0) < 0 || int64(int64(len(value_12))) < int64(0) || int64(int64(len(value_12))) > int64(len(value_12)) {
				panic("slice range out of bounds")
			}
			var value_13 Error = Websocket_WriteFrame(accepted.Connection, 9, value_12[0:int64(len(value_12)):int64(len(value_12))])
			if value_13 != nil {
				return
			}
		}
		var cases [2]Case
		var value_14 Case = StdSelectGo_Receive(StdContextGo_Done(child.Value))
		cases[0] = value_14
		var value_15 Case = StdSelectGo_Receive(StdTimeGo_TickerChannel(ticker))
		cases[1] = value_15
		var value_16 SelectResult = StdSelectGo_Select(cases[0:2:2])
		if value_16.Chosen == 0 {
			return
		}
		ticks++
	}
}

func DelegatedWs_ReadProof(request *Request, proof *RequestProof) bool {
	var value_0 Error = StrictJson_Decode(StdTextGo_ToBytes(StdHttpGo_HeaderValue(StdHttpGo_Headers(request), "X-Daochi-Delegate")), proof)
	return value_0 == nil
}

var DelegatedWs_ziranInitState uint8

func DelegatedWs_ziranInit() {
	if DelegatedWs_ziranInitState == 2 {
		return
	}
	if DelegatedWs_ziranInitState == 1 {
		panic("cyclic module startup")
	}
	DelegatedWs_ziranInitState = 1
	AuthorizationHttp_ziranInit()
	DelegatedWs_ziranInitState = 2
}
