// Code generated by zi2go from discovery.zi. DO NOT EDIT.
package main

import (
	zeroconf "github.com/grandcat/zeroconf"
	slog "log/slog"
	net "net"
	strconv "strconv"
	strings "strings"
)

// #import std_go_types
// #import node_identity
type Advertiser = zeroconf.Server

type Interface = net.Interface

type RegistrationResult struct {
	Value *Advertiser
	Error Error
}

type PortResult struct {
	Value int
	Error Error
}

type RegisterService func(string, string, string, int, []string, []Interface) RegistrationResult

type ShutdownService func(*Advertiser)

func Discovery_Atoi(Value string) PortResult {
	var result PortResult
	result.Value, result.Error = strconv.Atoi(Value)
	return result
}

func Discovery_RegisterRaw(Instance string, Service string, Domain string, Port int, Text []string, Interfaces []Interface) RegistrationResult {
	var result RegistrationResult
	result.Value, result.Error = zeroconf.Register(Instance, Service, Domain, Port, Text, Interfaces)
	return result
}

func Discovery_ShutdownAtReturn(Callback ShutdownService, Service *Advertiser) {
	Callback(Service)
}

const ServiceName = "_daochi._tcp"
const Domain = "local."

func Discovery_Register(instance string, service string, domain string, port int, text []string, interfaces []Interface) RegistrationResult {
	return Discovery_RegisterRaw(instance, service, domain, int(port), text, interfaces)
}

func Discovery_Shutdown(service *Advertiser) {
	(*zeroconf.Server).Shutdown(service)
}

func Discovery_Run(configuration *Config, identity *NodeIdentity, value Context, register RegisterService, shutdown ShutdownService) {
	if !configuration.LANDiscovery {
		return
	}
	port := Discovery_ListenerPort(configuration.Addr)
	if port.Error != nil {
		slog.Warn("LAN discovery disabled", "error", port.Error)
		return
	}
	var interfaces []Interface = nil
	var value_0 RegisterService = register
	var value_1 string = Discovery_InstanceName(configuration.NodeDisplayName, identity.ID)
	var value_2 int = port.Value
	var value_3 []string = Discovery_Text(identity.ID)
	registered := value_0(value_1, "_daochi._tcp", "local.", value_2, value_3, interfaces)
	if registered.Error != nil {
		slog.Warn("LAN discovery unavailable", "error", registered.Error)
		return
	}
	slog.Info("advertising Daochi node on LAN", "node_id", identity.ID, "port", int(port.Value))
	defer Discovery_ShutdownAtReturn(shutdown, registered.Value)
	var cases [1]Case
	var value_4 Case = StdSelectGo_Receive(StdContextGo_Done(value))
	cases[0] = value_4
	StdSelectGo_Select(cases[0:1:1])
}

func Discovery_ListenerPort(address string) PortResult {
	split := StdNetGo_SplitHostPort(address)
	if split.Error != nil {
		var result PortResult = PortResult{}
		result.Error = split.Error
		return result
	}
	return Discovery_Atoi(split.Port)
}

func Discovery_InstanceName(displayName string, nodeID string) string {
	name := strings.TrimSpace(displayName)
	if name == "" {
		name = "Daochi Node"
	}
	if int64(len(nodeID)) > 12 {
		nodeID = nodeID[:12]
	}
	parts := [3]string{name, " ", nodeID}
	_ = parts
	return strings.Join(parts[0:3:3], "")
}

func Discovery_Text(nodeID string) []string {
	value := make([]string, int(int(4)))
	parts := [2]string{"id=", nodeID}
	_ = parts
	var value_0 string = strings.Join(parts[0:2:2], "")
	value[0] = value_0
	value[1] = "protocol=6"
	value[2] = "trust=pairing-required"
	value[3] = "path=/api/v1/node"
	return value
}
