// Code generated by zi2go from encrypted_payloads.zi. DO NOT EDIT.
package main

import (
	sql "database/sql"
	strings "strings"
)

// #import std_go_types
// #import sync_types
type PayloadWriteResult struct {
	Version int64
	Error   Error
}

type PayloadsResult struct {
	Value     []EncryptedPayload
	Truncated bool
	Error     Error
}

type PayloadBytesResult struct {
	Value int64
	Error Error
}

type EncryptedPayloadPruneResult struct {
	Deleted int64
}

type PayloadPruneOutcome struct {
	Value EncryptedPayloadPruneResult
	Error Error
}

type PayloadByteTotal = sql.NullInt64

func EncryptedPayloads_TotalValid(Value PayloadByteTotal) bool {
	return Value.Valid
}

func EncryptedPayloads_TotalValue(Value PayloadByteTotal) int64 {
	return Value.Int64
}

func EncryptedPayloads_ReadPayloads(rows *Rows, failIncomplete bool) PayloadsResult {
	var result PayloadsResult = PayloadsResult{}
	values := make([]EncryptedPayload, int(int(0)))
	for StdSqlGo_Next(rows) {
		var item EncryptedPayload = EncryptedPayload{}
		var payload string = ""
		var value_0 [5]Any
		value_0[0] = &(item.ID)
		value_0[1] = &(item.ClientID)
		value_0[2] = &(payload)
		value_0[3] = &(item.CreatedAt)
		value_0[4] = &(item.ServerVersion)
		destinations := value_0
		_ = destinations
		result.Error = StdSqlGo_ScanRows(rows, destinations[0:5:5])
		if result.Error != nil {
			return result
		}
		var value_1 []uint8 = StdTextGo_ToBytes(payload)
		item.Payload = RawMessage(value_1)
		values = append(values, item)
	}
	result.Error = StdSqlGo_RowsError(rows)
	if failIncomplete && result.Error != nil {
		return result
	}
	result.Value = values
	return result
}

func EncryptedPayloads_Store(database *Database, context Context, userID string, clientID string, payload []uint8, missingUser Error) PayloadWriteResult {
	var result PayloadWriteResult = PayloadWriteResult{}
	opened := StdSqlGo_Begin(database, context, nil)
	result.Error = opened.Error
	if result.Error != nil {
		return result
	}
	transaction := opened.Value
	defer (*sql.Tx).Rollback(transaction)
	result.Error = AccountState_Touch(transaction, context, userID, missingUser)
	if result.Error != nil {
		return result
	}
	version := AccountState_NextVersion(transaction, context, userID)
	result.Error = version.Error
	if result.Error != nil {
		return result
	}
	var value_0 [5]Any
	value_0[0] = userID
	value_0[1] = clientID
	var value_1 string = StdTextGo_FromBytes(payload)
	value_0[2] = value_1
	value_0[3] = version.Value
	var value_2 string = Timestamp_CanonicalNow()
	value_0[4] = value_2
	arguments := value_0
	_ = arguments
	var value_3 string = "\nINSERT INTO server_encrypted_payloads(user_id_hash,client_id,payload_json,server_version,created_at)\nVALUES(?1,?2,?3,?4,?5)"
	written := StdSqlGo_ExecTx(transaction, context, value_3, arguments[0:5:5])
	result.Error = written.Error
	if result.Error != nil {
		return result
	}
	result.Version = version.Value
	result.Error = StdSqlGo_Commit(transaction)
	return result
}

func EncryptedPayloads_Since(database *Database, context Context, userID string, sinceVersion int64, limit int) PayloadsResult {
	var result PayloadsResult = PayloadsResult{}
	queryLimit := limit
	limitClause := ""
	if queryLimit > int(0) {
		queryLimit += int(1)
		limitClause = " LIMIT ?3"
	}
	var value_0 [2]string
	var value_1 string = "\nSELECT id,client_id,payload_json,created_at,server_version\nFROM server_encrypted_payloads\nWHERE user_id_hash=?1 AND server_version>?2\nORDER BY server_version,id"
	value_0[0] = value_1
	value_0[1] = limitClause
	parts := value_0
	_ = parts
	query := strings.Join(parts[0:2:2], "")
	var queried QueryResult = QueryResult{}
	if queryLimit > int(0) {
		var value_2 [3]Any
		value_2[0] = userID
		value_2[1] = sinceVersion
		value_2[2] = queryLimit
		arguments := value_2
		_ = arguments
		queried = StdSqlGo_Query(database, context, query, arguments[0:3:3])
	} else {
		var value_3 [2]Any
		value_3[0] = userID
		value_3[1] = sinceVersion
		arguments := value_3
		_ = arguments
		queried = StdSqlGo_Query(database, context, query, arguments[0:2:2])
	}
	result.Error = queried.Error
	if result.Error != nil {
		return result
	}
	rows := queried.Value
	defer (*sql.Rows).Close(rows)
	result = EncryptedPayloads_ReadPayloads(rows, true)
	if result.Error != nil {
		return result
	}
	if limit > int(0) && int64(len(result.Value)) > int64(limit) {
		result.Truncated = true
		value_4 := result.Value[:]
		if int64(0) < 0 || int64(limit) < int64(0) || int64(limit) > int64(len(value_4)) {
			panic("slice range out of bounds")
		}
		result.Value = value_4[0:limit:limit]
	}
	return result
}

func EncryptedPayloads_Recent(database *Database, context Context, userID string, limit int) PayloadsResult {
	var result PayloadsResult = PayloadsResult{}
	if limit <= int(0) || limit > int(50) {
		limit = int(10)
	}
	var value_0 [2]Any
	value_0[0] = userID
	value_0[1] = limit
	arguments := value_0
	_ = arguments
	var value_1 string = "\nSELECT id,client_id,payload_json,created_at,server_version\nFROM server_encrypted_payloads\nWHERE user_id_hash=?1\nORDER BY id DESC\nLIMIT ?2"
	queried := StdSqlGo_Query(database, context, value_1, arguments[0:2:2])
	result.Error = queried.Error
	if result.Error != nil {
		return result
	}
	rows := queried.Value
	defer (*sql.Rows).Close(rows)
	return EncryptedPayloads_ReadPayloads(rows, false)
}

func EncryptedPayloads_Bytes(database *Database, context Context, userID string) PayloadBytesResult {
	var result PayloadBytesResult = PayloadBytesResult{}
	var total PayloadByteTotal = *new(PayloadByteTotal)
	var value_0 [1]Any
	value_0[0] = userID
	arguments := value_0
	_ = arguments
	var value_1 [1]Any
	value_1[0] = &(total)
	destinations := value_1
	_ = destinations
	row := StdSqlGo_QueryRow(database, context, "\nSELECT SUM(LENGTH(payload_json))\nFROM server_encrypted_payloads\nWHERE user_id_hash=?1", arguments[0:1:1])
	result.Error = StdSqlGo_ScanRow(row, destinations[0:1:1])
	var value_2 bool = result.Error == nil
	var value_3 bool = value_2
	if value_3 {
		var value_4 bool = EncryptedPayloads_TotalValid(total)
		value_3 = value_4
	}
	if value_3 {
		result.Value = EncryptedPayloads_TotalValue(total)
	}
	return result
}

func EncryptedPayloads_Prune(database *Database, context Context, userID string, maxAge Duration, maxBytes int64) PayloadPruneOutcome {
	var result PayloadPruneOutcome = PayloadPruneOutcome{}
	if int64(maxAge) <= 0 && maxBytes <= 0 {
		return result
	}
	opened := StdSqlGo_Begin(database, context, nil)
	result.Error = opened.Error
	if result.Error != nil {
		return result
	}
	transaction := opened.Value
	defer (*sql.Tx).Rollback(transaction)
	if int64(maxAge) > 0 {
		cutoff := Timestamp_CanonicalTimestamp(StdTimeGo_Add(StdTimeGo_UTC(StdTimeGo_Now()), Duration(0-int64(maxAge))))
		var value_0 [2]Any
		value_0[0] = userID
		value_0[1] = cutoff
		arguments := value_0
		_ = arguments
		deleted := StdSqlGo_ExecTx(transaction, context, "\nDELETE FROM server_encrypted_payloads\nWHERE user_id_hash=?1 AND created_at<?2", arguments[0:2:2])
		_ = deleted
		result.Error = deleted.Error
		if result.Error != nil {
			return result
		}
		affected := StdSqlGo_RowsAffected(deleted.Value)
		_ = affected
		result.Value.Deleted += affected.Value
	}
	if maxBytes > 0 {
		var value_1 [1]Any
		value_1[0] = userID
		arguments := value_1
		_ = arguments
		for true {
			var total PayloadByteTotal = *new(PayloadByteTotal)
			var value_2 [1]Any
			value_2[0] = &(total)
			destinations := value_2
			_ = destinations
			row := StdSqlGo_QueryRowTx(transaction, context, "\nSELECT SUM(LENGTH(payload_json))\nFROM server_encrypted_payloads\nWHERE user_id_hash=?1", arguments[0:1:1])
			result.Error = StdSqlGo_ScanRow(row, destinations[0:1:1])
			if result.Error != nil {
				return result
			}
			var value_3 bool = EncryptedPayloads_TotalValid(total)
			var value_4 bool = !value_3
			if !value_4 {
				var value_5 bool = EncryptedPayloads_TotalValue(total) <= maxBytes
				value_4 = value_5
			}
			if value_4 {
				break
			}
			var value_6 string = "\nDELETE FROM server_encrypted_payloads\nWHERE id=(\n\tSELECT id\n\tFROM server_encrypted_payloads\n\tWHERE user_id_hash=?1\n\tORDER BY server_version,id\n\tLIMIT 1\n)"
			deleted := StdSqlGo_ExecTx(transaction, context, value_6, arguments[0:1:1])
			_ = deleted
			result.Error = deleted.Error
			if result.Error != nil {
				return result
			}
			affected := StdSqlGo_RowsAffected(deleted.Value)
			_ = affected
			if affected.Value == 0 {
				break
			}
			result.Value.Deleted += affected.Value
		}
	}
	result.Error = StdSqlGo_Commit(transaction)
	return result
}
