// Code generated by zi2go from google_play_http.zi. DO NOT EDIT.
package main

import slog "log/slog"

// #import protocol
// #import std_go_types
// #import std_map_go
// #import std_option
type zir_7973e71b215e8962_ReplayCleanup func(*Database, Context, TokenAuthorizationResult, *bool)

type __type_31c6478de00191c0 struct {
	HasValue bool
	Value    TokenProduct
}

func GooglePlayHttp_CleanupAtReturn(Callback zir_7973e71b215e8962_ReplayCleanup, Database *Database, Context Context, Authorization TokenAuthorizationResult, Completed *bool) {
	Callback(Database, Context, Authorization, Completed)
}

func GooglePlayHttp_ForgetOnFailure(database *Database, context Context, authorization TokenAuthorizationResult, completed *bool) {
	if authorization.Signed && !*(completed) {
		SignedTx_Forget(database, context, authorization.Value)
	}
}

func GooglePlayHttp_PaymentError(writer ResponseWriter, failure Error) {
	if StdErrorsGo_Is(failure, errPaymentUnavailable) {
		Response_Error(writer, int(503), "payment verifier unavailable")
		return
	}
	Response_Error(writer, int(400), StdErrorsGo_Message(failure))
}

func GooglePlayHttp_Verify(server Tokens, writer ResponseWriter, request *Request) {
	user := HttpAuth_BearerUser(server.Database, request, server.Configuration.TokenSecret)
	if user.Authentication.Error != nil || user.Authentication.Status != 0 {
		HttpAuth_Respond(writer, server.Counters, user.Authentication)
		return
	}
	decoded := PaymentRequest_ReadGoogle(writer, request, server.Configuration.MaxBodyBytes)
	if decoded.Error != nil {
		Response_Error(writer, int(400), StdErrorsGo_Message(decoded.Error))
		return
	}
	issuer := TokenPolicy_Issuer(*(server.Configuration), server.IssuerUnavailable)
	if issuer.Error != nil {
		Response_Error(writer, int(503), "token issuer unavailable")
		return
	}
	var value_0 __type_cd75cecb5feef7fa = server.Configuration.TokenProducts
	var value_1 string = decoded.Value.ProductID
	var value_2 __type_31c6478de00191c0 = __type_31c6478de00191c0{}
	value_2.Value, value_2.HasValue = value_0[value_1]
	product := value_2
	if !product.HasValue {
		Response_Error(writer, int(400), "unknown product_id")
		return
	}
	existence := AppStore_Exists(server.Database, StdHttpGo_Context(request), decoded.Value.AppID)
	if existence.Error != nil {
		slog.Error("google token purchase app lookup", "app", LogSafety_LogText(decoded.Value.AppID), "error", existence.Error)
		Response_Error(writer, int(500), "token purchase failed")
		return
	}
	if !existence.Value {
		Response_Error(writer, int(400), "unknown app_id")
		return
	}
	authorization := TokenPolicy_Authorize(server.Database, StdHttpGo_Context(request), request, decoded.Body, user.Value, decoded.Value.AppID, "waozi:token", "purchase", server.Verify, server.ReplayError)
	if authorization.Authentication.Error != nil || authorization.Authentication.Status != 0 {
		if authorization.Signed {
			SignedTx_Forget(server.Database, StdHttpGo_Context(request), authorization.Value)
		}
		HttpAuth_Respond(writer, server.Counters, authorization.Authentication)
		return
	}
	completed := false
	var value_7 zir_7973e71b215e8962_ReplayCleanup = func(value_3 *Database, value_4 Context, value_5 TokenAuthorizationResult, value_6 *bool) {
		GooglePlayHttp_ForgetOnFailure(value_3, value_4, value_5, value_6)
	}
	defer GooglePlayHttp_CleanupAtReturn(value_7, server.Database, StdHttpGo_Context(request), authorization, &(completed))
	var value_8 __type_c922d3f56b74fd5a = server.Configuration.GooglePackageNames
	var value_9 int64 = int64(len(value_8))
	var value_10 bool = value_9 > 0
	if value_10 {
		var value_11 __type_c922d3f56b74fd5a = server.Configuration.GooglePackageNames
		var value_12 string = decoded.Value.PackageName
		var value_13 bool = value_11[value_12]
		value_10 = !value_13
	}
	if value_10 {
		Response_Error(writer, int(400), "package not allowed")
		return
	}
	var value_14 Context = StdHttpGo_Context(request)
	verified := GooglePlay_VerifyPurchase(value_14, *(server.Configuration), decoded.Value)
	if verified.Error != nil {
		GooglePlayHttp_PaymentError(writer, verified.Error)
		return
	}
	var event TokenEventInput = TokenEventInput{}
	event.AccountID = user.Value
	event.AppID = decoded.Value.AppID
	event.EventType = "credit"
	event.AmountDelta = product.Value.TokenUnits
	event.SourceType = "google_play"
	event.SourceRef = verified.Value
	credited := TokenLedger_CreditPayment(server.Database, StdHttpGo_Context(request), issuer.Value, "google_play", verified.Value, event, server.IssuerUnavailable)
	if credited.Error != nil {
		slog.Error("google token credit", "user", LogSafety_LogText(user.Value), "payment", LogSafety_LogText(verified.Value), "error", credited.Error)
		Response_Error(writer, int(500), "token credit failed")
		return
	}
	var value_15 Context = StdHttpGo_Context(request)
	consumed := GooglePlay_ConsumePurchase(value_15, *(server.Configuration), decoded.Value)
	if consumed != nil {
		slog.Warn("google purchase consume failed after token credit", "user", LogSafety_LogText(user.Value), "payment", LogSafety_LogText(verified.Value), "error", consumed)
	}
	balance := TokenLedger_Balance(server.Database, StdHttpGo_Context(request), user.Value, "waozi:token")
	if balance.Error != nil {
		Response_Error(writer, int(500), "token balance failed")
		return
	}
	completed = true
	var purchase TokenPurchaseResponse = TokenPurchaseResponse{}
	purchase.Status = "ok"
	purchase.Balance = balance.Value
	purchase.Receipt = credited.Value
	Response_JSON(writer, int(200), purchase)
}

var GooglePlayHttp_ziranInitState uint8

func GooglePlayHttp_ziranInit() {
	if GooglePlayHttp_ziranInitState == 2 {
		return
	}
	if GooglePlayHttp_ziranInitState == 1 {
		panic("cyclic module startup")
	}
	GooglePlayHttp_ziranInitState = 1
	GooglePlay_ziranInit()
	PaymentState_ziranInit()
	GooglePlayHttp_ziranInitState = 2
}
