// Code generated by zi2go from http_body.zi. DO NOT EDIT.
package main

import io "io"

// #import std_go_types
func HttpBody_ReadJSON(writer ResponseWriter, request *Request, limit int64) JSONResult {
	var result JSONResult = JSONResult{}
	body := StdHttpGo_Body(request)
	defer (io.ReadCloser).Close(body)
	var value_0 ReadCloser = StdHttpGo_MaxBytesReader(writer, body, limit)
	read := StdIoGo_ReadAll(Reader(value_0))
	if read.Error != nil {
		result.Error = StdErrorsGo_New("request body too large")
		return result
	}
	var value_1 bool = StdJsonGo_Valid(read.Value)
	if !value_1 {
		result.Error = StdErrorsGo_New("invalid json")
		return result
	}
	result.Value = read.Value
	return result
}
