// Code generated by zi2go from inspect.zi. DO NOT EDIT.
package main

import (
	sql "database/sql"
	flag "flag"
	fmt "fmt"
	os "os"
	strings "strings"
)

// #import std_go_types
type InspectOptions struct {
	DBPath string
	Full   bool
	Out    Writer
}

type DatabaseResult struct {
	Value *Database
	Error Error
}

type CountResult struct {
	Value int
	Error Error
}

type FlagSet = flag.FlagSet

type ErrorHandling = flag.ErrorHandling

type zir_0732531d6612aaed_NullInteger = sql.NullInt64

type zir_242d5027da75102e_RowsResult struct {
	Value *Rows
	Error Error
}

func Inspect_StandardOutput() Writer {
	return os.Stdout
}

func Inspect_ContinueOnError() ErrorHandling {
	return flag.ContinueOnError
}

func Inspect_OpenDatabase(Driver string, Source string) DatabaseResult {
	var result DatabaseResult
	result.Value, result.Error = sql.Open(Driver, Source)
	return result
}

func Inspect_QueryAll(Database *Database, Context Context, Query string) zir_242d5027da75102e_RowsResult {
	var result zir_242d5027da75102e_RowsResult
	result.Value, result.Error = (*sql.DB).QueryContext(Database, Context, Query)
	return result
}

func Inspect_QueryUser(Database *Database, Context Context, Query string, UserID string) zir_242d5027da75102e_RowsResult {
	var result zir_242d5027da75102e_RowsResult
	result.Value, result.Error = (*sql.DB).QueryContext(Database, Context, Query, UserID)
	return result
}

func Inspect_IntegerValid(Value zir_0732531d6612aaed_NullInteger) bool {
	return Value.Valid
}

func Inspect_IntegerValue(Value zir_0732531d6612aaed_NullInteger) int64 {
	return Value.Int64
}

const UsersQuery = "\nSELECT user_id_hash, hex(public_key), created_at, last_seen_at\nFROM server_users\nORDER BY last_seen_at DESC\n"
const UserQuery = "\nSELECT hex(public_key), created_at, last_seen_at\nFROM server_users\nWHERE user_id_hash=?1\n"
const DoctorQuery = "\nSELECT created_at,last_seen_at\nFROM server_users\nWHERE user_id_hash=?1\n"
const VersionQuery = "\nSELECT server_version\nFROM server_sync_state\nWHERE user_id_hash=?1\n"
const CompactionQuery = "\nSELECT compacted_through_version\nFROM server_sync_compaction\nWHERE user_id_hash=?1\n"
const LegacyClientsQuery = "\nSELECT COUNT(*)\nFROM server_clients\nWHERE user_id_hash=?1 AND protocol_version>0 AND protocol_version<5\n"
const PayloadsQuery = "\nSELECT COUNT(*),SUM(LENGTH(payload_json))\nFROM server_encrypted_payloads\nWHERE user_id_hash=?1\n"
const FullSnapshotsQuery = "\nSELECT COUNT(*)\nFROM (\n\tSELECT full_snapshot_required\n\tFROM server_sync_audit\n\tWHERE user_id_hash=?1\n\tORDER BY id DESC\n\tLIMIT 8\n)\nWHERE full_snapshot_required!=0\n"
const ClientsQuery = "\nSELECT client_id,protocol_version,last_login_at,last_sync_at,last_seen_server_version,last_client_clock\nFROM server_clients\nWHERE user_id_hash=?1\nORDER BY last_seen_at DESC,client_id\nLIMIT 12\n"
const AuditQuery = "\nSELECT client_id,protocol_version,server_version,remote_ops,full_snapshot_required,\n       snapshot_reason,encrypted_payload,encrypted_payload_bytes,created_at\nFROM server_sync_audit\nWHERE user_id_hash=?1\nORDER BY id DESC\nLIMIT 8\n"
const HabitsQuery = "\nSELECT id, name, sync_mode, sync_activity, deleted_at, updated_at\nFROM server_habits\nWHERE user_id_hash=?1\nORDER BY sort_order, id\nLIMIT 50\n"
const SessionsQuery = "\nSELECT id, started_at, local_date, topic, activity, deleted_at, updated_at\nFROM server_sessions\nWHERE user_id_hash=?1\nORDER BY started_at DESC\nLIMIT 25\n"

var SummaryTables [9]string = [9]string{"server_users", "server_habits", "server_habit_days", "server_sessions", "server_session_rounds", "server_meditation_logs", "server_encrypted_records", "server_encrypted_payloads", "server_sync_audit"}
var UserTables [6]string = [6]string{"server_habits", "server_habit_days", "server_sessions", "server_session_rounds", "server_meditation_logs", "server_encrypted_records"}
var DoctorTables [9]string = [9]string{"server_habits", "server_habit_days", "server_sessions", "server_meditation_logs", "server_encrypted_records", "server_encrypted_payloads", "server_sync_ops", "server_clients", "server_sync_audit"}

func Inspect_Run(context Context, arguments []string, options InspectOptions) Error {
	if Any(options.Out) == nil {
		var value_0 Writer = Inspect_StandardOutput()
		options.Out = value_0
	}
	flags := flag.NewFlagSet("inspect", Inspect_ContinueOnError())
	(*flag.FlagSet).SetOutput(flags, options.Out)
	(*flag.FlagSet).StringVar(flags, &(options.DBPath), "db", options.DBPath, "SQLite database path")
	(*flag.FlagSet).BoolVar(flags, &(options.Full), "full", options.Full, "show full user IDs and public keys")
	error := (*flag.FlagSet).Parse(flags, arguments)
	if error != nil {
		return error
	}
	if options.DBPath == "" {
		var value_1 string = Config_EnvString("DAOCHI_DB", "daochi.db")
		options.DBPath = value_1
	}
	remaining := (*flag.FlagSet).Args(flags)
	if int64(len(remaining)) == 0 {
		remaining = make([]string, int(int(1)))
		remaining[0] = "summary"
	}
	opened := Inspect_Open(options.DBPath)
	if opened.Error != nil {
		return opened.Error
	}
	database := opened.Value
	defer (*sql.DB).Close(database)
	command := remaining[0]
	if command == "summary" {
		return Inspect_Summary(context, database, options.Out)
	}
	if command == "users" {
		return Inspect_Users(context, database, options.Out, options.Full)
	}
	if command == "doctor" {
		if int64(len(remaining)) != 2 {
			return StdErrorsGo_New("usage: daochi inspect doctor <user_id_hash>")
		}
		return Inspect_Doctor(context, database, options.Out, remaining[1], options.Full)
	}
	if command == "user" {
		if int64(len(remaining)) != 2 {
			return StdErrorsGo_New("usage: daochi inspect user <user_id_hash>")
		}
		return Inspect_User(context, database, options.Out, remaining[1], options.Full)
	}
	return fmt.Errorf("unknown inspect command %q", command)
}

func Inspect_Open(path string) DatabaseResult {
	SqliteDriver_Initialize()
	result := Inspect_OpenDatabase("sqlite3", fmt.Sprintf("file:%s?mode=ro&_query_only=1", path))
	if result.Error != nil {
		result.Value = nil
		return result
	}
	(*sql.DB).SetMaxOpenConns(result.Value, int(int(1)))
	error := (*sql.DB).Ping(result.Value)
	if error != nil {
		(*sql.DB).Close(result.Value)
		result.Value = nil
		result.Error = error
	}
	return result
}

func Inspect_Summary(context Context, database *Database, out Writer) Error {
	fmt.Fprintln(out, "Daochi data summary")
	for it_index := int64(0); it_index < 9; it_index++ {
		table := SummaryTables[it_index]
		count := Inspect_Count(context, database, table, "", "")
		if count.Error != nil {
			return count.Error
		}
		fmt.Fprintf(out, "%-24s %d\n", table, count.Value)
	}
	return nil
}

func Inspect_Users(context Context, database *Database, out Writer, full bool) Error {
	queried := Inspect_QueryAll(database, context, "\nSELECT user_id_hash, hex(public_key), created_at, last_seen_at\nFROM server_users\nORDER BY last_seen_at DESC\n")
	if queried.Error != nil {
		return queried.Error
	}
	rows := queried.Value
	defer (*sql.Rows).Close(rows)
	fmt.Fprintln(out, "Users")
	for StdSqlGo_Next(rows) {
		var userID string = ""
		var publicKey string = ""
		var createdAt string = ""
		var lastSeenAt string = ""
		error := (*sql.Rows).Scan(rows, &(userID), &(publicKey), &(createdAt), &(lastSeenAt))
		if error != nil {
			return error
		}
		var value_0 string = Inspect_RedactID(userID, full)
		var value_1 string = Inspect_RedactID(strings.ToLower(publicKey), full)
		fmt.Fprintf(out, "%s  key=%s  created=%s  last_seen=%s\n", value_0, value_1, createdAt, lastSeenAt)
	}
	return StdSqlGo_RowsError(rows)
}

func Inspect_User(context Context, database *Database, out Writer, userID string, full bool) Error {
	userID = strings.ToLower(strings.TrimSpace(userID))
	var value_0 bool = Identity_ValidUserID(userID)
	if !value_0 {
		return StdErrorsGo_New("invalid user_id_hash")
	}
	var publicKey string = ""
	var createdAt string = ""
	var lastSeenAt string = ""
	var value_1 *Row = (*sql.DB).QueryRowContext(database, context, "\nSELECT hex(public_key), created_at, last_seen_at\nFROM server_users\nWHERE user_id_hash=?1\n", userID)
	error := (*sql.Row).Scan(value_1, &(publicKey), &(createdAt), &(lastSeenAt))
	if error == StdSqlGo_NoRows() {
		return StdErrorsGo_New("user not found")
	}
	if error != nil {
		return error
	}
	fmt.Fprintf(out, "User %s\n", Inspect_RedactID(userID, full))
	fmt.Fprintf(out, "public_key=%s\n", Inspect_RedactID(strings.ToLower(publicKey), full))
	fmt.Fprintf(out, "created=%s\nlast_seen=%s\n", createdAt, lastSeenAt)
	for it_index := int64(0); it_index < 6; it_index++ {
		table := UserTables[it_index]
		count := Inspect_Count(context, database, table, "WHERE user_id_hash=?1", userID)
		if count.Error != nil {
			return count.Error
		}
		fmt.Fprintf(out, "%-24s %d\n", table, count.Value)
	}
	error = Inspect_UserHabits(context, database, out, userID)
	if error != nil {
		return error
	}
	return Inspect_UserSessions(context, database, out, userID)
}

func Inspect_Doctor(context Context, database *Database, out Writer, userID string, full bool) Error {
	userID = strings.ToLower(strings.TrimSpace(userID))
	var value_0 bool = Identity_ValidUserID(userID)
	if !value_0 {
		return StdErrorsGo_New("invalid user_id_hash")
	}
	var createdAt string = ""
	var lastSeenAt string = ""
	var value_1 *Row = (*sql.DB).QueryRowContext(database, context, "\nSELECT created_at,last_seen_at\nFROM server_users\nWHERE user_id_hash=?1\n", userID)
	error := (*sql.Row).Scan(value_1, &(createdAt), &(lastSeenAt))
	if error == StdSqlGo_NoRows() {
		return StdErrorsGo_New("user not found")
	}
	if error != nil {
		return error
	}
	var version int64 = 0
	var value_2 *Row = (*sql.DB).QueryRowContext(database, context, "\nSELECT server_version\nFROM server_sync_state\nWHERE user_id_hash=?1\n", userID)
	(*sql.Row).Scan(value_2, &(version))
	var compactedThrough int64 = 0
	var value_3 *Row = (*sql.DB).QueryRowContext(database, context, "\nSELECT compacted_through_version\nFROM server_sync_compaction\nWHERE user_id_hash=?1\n", userID)
	(*sql.Row).Scan(value_3, &(compactedThrough))
	fmt.Fprintf(out, "Daochi doctor %s\n", Inspect_RedactID(userID, full))
	fmt.Fprintf(out, "status=ok server_version=%d compacted_through=%d\n", version, compactedThrough)
	fmt.Fprintf(out, "created=%s last_seen=%s\n", createdAt, lastSeenAt)
	for it_index := int64(0); it_index < 9; it_index++ {
		table := DoctorTables[it_index]
		count := Inspect_Count(context, database, table, "WHERE user_id_hash=?1", userID)
		if count.Error != nil {
			return count.Error
		}
		fmt.Fprintf(out, "%-28s %d\n", table, count.Value)
	}
	error = Inspect_DoctorWarnings(context, database, out, userID)
	if error != nil {
		return error
	}
	error = Inspect_DoctorClients(context, database, out, userID)
	if error != nil {
		return error
	}
	return Inspect_DoctorAudit(context, database, out, userID)
}

func Inspect_DoctorWarnings(context Context, database *Database, out Writer, userID string) Error {
	warnings := make([]string, int(int(0)))
	var legacyClients int = 0
	var value_0 *Row = (*sql.DB).QueryRowContext(database, context, "\nSELECT COUNT(*)\nFROM server_clients\nWHERE user_id_hash=?1 AND protocol_version>0 AND protocol_version<5\n", userID)
	error := (*sql.Row).Scan(value_0, &(legacyClients))
	if error != nil {
		return error
	}
	if legacyClients > 0 {
		warnings = append(warnings, fmt.Sprintf("%d legacy clients below protocol 5 seen recently", int64(int64(legacyClients))))
	}
	var payloadCount int = 0
	var payloadBytes zir_0732531d6612aaed_NullInteger = *new(zir_0732531d6612aaed_NullInteger)
	var value_1 *Row = (*sql.DB).QueryRowContext(database, context, "\nSELECT COUNT(*),SUM(LENGTH(payload_json))\nFROM server_encrypted_payloads\nWHERE user_id_hash=?1\n", userID)
	error = (*sql.Row).Scan(value_1, &(payloadCount), &(payloadBytes))
	if error != nil {
		return error
	}
	if payloadCount > 1000 {
		warnings = append(warnings, fmt.Sprintf("%d encrypted payloads queued; consider pagination/retention tuning", int64(int64(payloadCount))))
	}
	var value_2 bool = Inspect_IntegerValid(payloadBytes)
	var value_3 bool = value_2
	if value_3 {
		var value_4 bool = Inspect_IntegerValue(payloadBytes) > 67108864
		value_3 = value_4
	}
	if value_3 {
		warnings = append(warnings, fmt.Sprintf("%d encrypted payload bytes stored; check account quota/retention", int64(Inspect_IntegerValue(payloadBytes))))
	}
	var fullSnapshots int = 0
	var value_5 string = "\nSELECT COUNT(*)\nFROM (\n\tSELECT full_snapshot_required\n\tFROM server_sync_audit\n\tWHERE user_id_hash=?1\n\tORDER BY id DESC\n\tLIMIT 8\n)\nWHERE full_snapshot_required!=0\n"
	error = (*sql.Row).Scan((*sql.DB).QueryRowContext(database, context, value_5, userID), &(fullSnapshots))
	if error != nil {
		return error
	}
	if fullSnapshots >= 3 {
		warnings = append(warnings, fmt.Sprintf("%d recent syncs required full snapshots", int64(int64(fullSnapshots))))
	}
	fmt.Fprintln(out, "\nWarnings")
	if int64(len(warnings)) == 0 {
		fmt.Fprintln(out, "- none")
		return nil
	}
	for _, warning := range warnings {
		fmt.Fprintf(out, "- %s\n", warning)
	}
	return nil
}

func Inspect_DoctorClients(context Context, database *Database, out Writer, userID string) Error {
	var value_0 string = "\nSELECT client_id,protocol_version,last_login_at,last_sync_at,last_seen_server_version,last_client_clock\nFROM server_clients\nWHERE user_id_hash=?1\nORDER BY last_seen_at DESC,client_id\nLIMIT 12\n"
	queried := Inspect_QueryUser(database, context, value_0, userID)
	if queried.Error != nil {
		return queried.Error
	}
	rows := queried.Value
	defer (*sql.Rows).Close(rows)
	fmt.Fprintln(out, "\nClients")
	for StdSqlGo_Next(rows) {
		var clientID string = ""
		var loginAt NullString = *new(NullString)
		var syncAt NullString = *new(NullString)
		var protocol int = 0
		var seenVersion int64 = 0
		var clientClock int64 = 0
		error := (*sql.Rows).Scan(rows, &(clientID), &(protocol), &(loginAt), &(syncAt), &(seenVersion), &(clientClock))
		if error != nil {
			return error
		}
		status := "current"
		if protocol > 0 && protocol < 5 {
			status = "legacy"
		}
		var value_1 string = clientID
		var value_2 int = protocol
		var value_3 string = Inspect_NullText(loginAt)
		var value_4 string = Inspect_NullText(syncAt)
		fmt.Fprintf(out, "%s protocol=%d status=%s last_login=%s last_sync=%s seen=%d clock=%d\n", value_1, value_2, status, value_3, value_4, seenVersion, clientClock)
	}
	return StdSqlGo_RowsError(rows)
}

func Inspect_DoctorAudit(context Context, database *Database, out Writer, userID string) Error {
	var value_0 string = "\nSELECT client_id,protocol_version,server_version,remote_ops,full_snapshot_required,\n       snapshot_reason,encrypted_payload,encrypted_payload_bytes,created_at\nFROM server_sync_audit\nWHERE user_id_hash=?1\nORDER BY id DESC\nLIMIT 8\n"
	queried := Inspect_QueryUser(database, context, value_0, userID)
	if queried.Error != nil {
		return queried.Error
	}
	rows := queried.Value
	defer (*sql.Rows).Close(rows)
	fmt.Fprintln(out, "\nRecent sync audit")
	for StdSqlGo_Next(rows) {
		var clientID string = ""
		var snapshotReason string = ""
		var createdAt string = ""
		var protocol int = 0
		var remoteOps int = 0
		var fullSnapshot int = 0
		var encryptedPayload int = 0
		var version int64 = 0
		var encryptedBytes int64 = 0
		error := (*sql.Rows).Scan(rows, &(clientID), &(protocol), &(version), &(remoteOps), &(fullSnapshot), &(snapshotReason), &(encryptedPayload), &(encryptedBytes), &(createdAt))
		if error != nil {
			return error
		}
		var value_1 string = "%s protocol=%d version=%d remote_ops=%d full_snapshot=%t reason=%s encrypted_payload=%t bytes=%d at=%s\n"
		var value_2 string = clientID
		var value_3 int = protocol
		var value_4 int64 = version
		var value_5 int = remoteOps
		var value_6 bool = fullSnapshot != 0
		var value_7 string = Inspect_EmptyText(snapshotReason, "-")
		fmt.Fprintf(out, value_1, value_2, value_3, value_4, value_5, value_6, value_7, encryptedPayload != 0, encryptedBytes, createdAt)
	}
	return StdSqlGo_RowsError(rows)
}

func Inspect_UserHabits(context Context, database *Database, out Writer, userID string) Error {
	var value_0 string = "\nSELECT id, name, sync_mode, sync_activity, deleted_at, updated_at\nFROM server_habits\nWHERE user_id_hash=?1\nORDER BY sort_order, id\nLIMIT 50\n"
	queried := Inspect_QueryUser(database, context, value_0, userID)
	if queried.Error != nil {
		return queried.Error
	}
	rows := queried.Value
	defer (*sql.Rows).Close(rows)
	fmt.Fprintln(out, "\nHabits")
	for StdSqlGo_Next(rows) {
		var id string = ""
		var name string = ""
		var updatedAt string = ""
		var syncMode int = 0
		var syncActivity int = 0
		var deletedAt int = 0
		error := (*sql.Rows).Scan(rows, &(id), &(name), &(syncMode), &(syncActivity), &(deletedAt), &(updatedAt))
		if error != nil {
			return error
		}
		fmt.Fprintf(out, "%s  %q  sync=%d/%d  deleted=%d  updated=%s\n", id, name, syncMode, syncActivity, deletedAt, updatedAt)
	}
	return StdSqlGo_RowsError(rows)
}

func Inspect_UserSessions(context Context, database *Database, out Writer, userID string) Error {
	var value_0 string = "\nSELECT id, started_at, local_date, topic, activity, deleted_at, updated_at\nFROM server_sessions\nWHERE user_id_hash=?1\nORDER BY started_at DESC\nLIMIT 25\n"
	queried := Inspect_QueryUser(database, context, value_0, userID)
	if queried.Error != nil {
		return queried.Error
	}
	rows := queried.Value
	defer (*sql.Rows).Close(rows)
	fmt.Fprintln(out, "\nRecent sessions")
	for StdSqlGo_Next(rows) {
		var id string = ""
		var startedAt string = ""
		var topic string = ""
		var updatedAt string = ""
		var localDate int = 0
		var activity int = 0
		var deletedAt int = 0
		error := (*sql.Rows).Scan(rows, &(id), &(startedAt), &(localDate), &(topic), &(activity), &(deletedAt), &(updatedAt))
		if error != nil {
			return error
		}
		fmt.Fprintf(out, "%s  started=%s  local_date=%d  topic=%s  activity=%d  deleted=%d  updated=%s\n", id, startedAt, localDate, topic, activity, deletedAt, updatedAt)
	}
	return StdSqlGo_RowsError(rows)
}

func Inspect_Count(context Context, database *Database, table string, where string, userID string) CountResult {
	var result CountResult = CountResult{}
	query := fmt.Sprintf("SELECT COUNT(*) FROM %s", table)
	if where != "" {
		var value_0 [3]string
		value_0[0] = query
		value_0[1] = " "
		value_0[2] = where
		parts := value_0
		_ = parts
		query = strings.Join(parts[0:3:3], "")
		var value_1 Error = (*sql.Row).Scan((*sql.DB).QueryRowContext(database, context, query, userID), &(result.Value))
		result.Error = value_1
	} else {
		var value_2 Error = (*sql.Row).Scan((*sql.DB).QueryRowContext(database, context, query), &(result.Value))
		result.Error = value_2
	}
	return result
}

func Inspect_RedactID(value string, full bool) string {
	if full || int64(len(value)) <= 16 {
		return value
	}
	var value_0 [3]string
	value_0[0] = value[:12]
	value_0[1] = "..."
	value_0[2] = value[(int64(len(value)) - 8):]
	parts := value_0
	_ = parts
	return strings.Join(parts[0:3:3], "")
}

func Inspect_NullText(value NullString) string {
	var value_0 bool = StdSqlGo_NullStringValid(value)
	var value_1 bool = !value_0
	if !value_1 {
		var value_2 bool = StdSqlGo_NullStringValue(value) == ""
		value_1 = value_2
	}
	if value_1 {
		return "-"
	}
	return StdSqlGo_NullStringValue(value)
}

func Inspect_EmptyText(value string, fallback string) string {
	if value == "" {
		return fallback
	}
	return value
}
