// Code generated by zi2go from io_go.zi. DO NOT EDIT.
package main

import io "io"

// #import go_types
type Reader = io.Reader

type ReadCloser = io.ReadCloser

type Writer = io.Writer

type ReadAllResult struct {
	Value []uint8
	Error Error
}

func IoGo_ReadAllRaw(Reader Reader) ReadAllResult {
	var result ReadAllResult
	result.Value, result.Error = io.ReadAll(Reader)
	return result
}

func IoGo_ReadAll(reader Reader) ReadAllResult {
	return IoGo_ReadAllRaw(reader)
}

func IoGo_Close(reader ReadCloser) Error {
	return (io.ReadCloser).Close(reader)
}
