// Code generated by zi2go from io_go.zi. DO NOT EDIT.
package main

import (
	bytes "bytes"
	io "io"
)

// #import go_types
type Reader = io.Reader

type ReadCloser = io.ReadCloser

type Writer = io.Writer

type BytesReader = bytes.Reader

type ReadAllResult struct {
	Value []uint8
	Error Error
}

func IoGo_ReadAllRaw(Reader Reader) ReadAllResult {
	var result ReadAllResult
	result.Value, result.Error = io.ReadAll(Reader)
	return result
}

func IoGo_ReadAll(reader Reader) ReadAllResult {
	return IoGo_ReadAllRaw(reader)
}

func IoGo_Close(reader ReadCloser) Error {
	return (io.ReadCloser).Close(reader)
}

func IoGo_LimitReader(reader Reader, count int64) Reader {
	return io.LimitReader(reader, int64(count))
}

func IoGo_FromBytes(data []uint8) Reader {
	var value_0 *BytesReader = bytes.NewReader(data)
	return Reader(value_0)
}
