// Code generated by zi2go from json_go.zi. DO NOT EDIT.
package main

import json "encoding/json"

// #import go_types
type Encoder = json.Encoder

type JSONResult struct {
	Value []uint8
	Error Error
}

func JsonGo_MarshalRaw(Value Any) JSONResult {
	var result JSONResult
	result.Value, result.Error = json.Marshal(Value)
	return result
}

func JsonGo_Marshal(value Any) JSONResult {
	return JsonGo_MarshalRaw(value)
}

func JsonGo_Unmarshal(data []uint8, value Any) Error {
	return json.Unmarshal(data, value)
}

func JsonGo_Valid(data []uint8) bool {
	return json.Valid(data)
}

func JsonGo_NewEncoder(writer Writer) *Encoder {
	return json.NewEncoder(writer)
}

func JsonGo_Encode(encoder *Encoder, value Any) Error {
	return (*json.Encoder).Encode(encoder, value)
}
