// Code generated by zi2go from manifest.zi. DO NOT EDIT.
package main

import (
	ed25519 "crypto/ed25519"
	strings "strings"
)

// #import protocol
// #import identity
// #import codec
// #import scope
type AppKey struct {
	KeyID     string "json:\"key_id\""
	Algorithm string "json:\"algorithm\""
	PublicKey string "json:\"public_key\""
	Purpose   string "json:\"purpose,omitempty\""
	Status    string "json:\"status,omitempty\""
	ExpiresAt int64  "json:\"expires_at,omitempty\""
	CreatedAt string "json:\"created_at,omitempty\""
}

type TokenPolicy struct {
	AssetID             string "json:\"asset_id\""
	Permission          string "json:\"permission\""
	Status              string "json:\"status,omitempty\""
	LegacyUnsignedUntil int64  "json:\"legacy_unsigned_until,omitempty\""
}

type AppManifest struct {
	ManifestVersion    int              "json:\"manifest_version\""
	AppID              string           "json:\"app_id\""
	DisplayName        string           "json:\"display_name\""
	Description        string           "json:\"description,omitempty\""
	HomepageURL        string           "json:\"homepage_url,omitempty\""
	SourceURL          string           "json:\"source_url,omitempty\""
	Status             string           "json:\"status,omitempty\""
	ExpiresAt          int64            "json:\"expires_at,omitempty\""
	AppSchemaVersion   int              "json:\"app_schema_version,omitempty\""
	MinClientVersion   string           "json:\"min_supported_client_version,omitempty\""
	CurrentVersion     string           "json:\"current_client_version,omitempty\""
	CompatibilityUntil string           "json:\"compatibility_until,omitempty\""
	Keys               []AppKey         "json:\"keys\""
	Collections        []AppCollection  "json:\"collections,omitempty\""
	Capabilities       []string         "json:\"capabilities,omitempty\""
	Features           []AppFeature     "json:\"features,omitempty\""
	LegacyProtocols    []LegacyProtocol "json:\"legacy_protocols,omitempty\""
	TokenPolicies      []TokenPolicy    "json:\"token_policies,omitempty\""
}

type SignedAppRegistrationRequest struct {
	Manifest          AppManifest "json:\"manifest\""
	ManifestSignature string      "json:\"manifest_signature\""
	ApprovalSignature string      "json:\"approval_signature\""
}

type AppRegistration struct {
	AppID              string           "json:\"app_id\""
	DisplayName        string           "json:\"display_name\""
	Description        string           "json:\"description,omitempty\""
	HomepageURL        string           "json:\"homepage_url,omitempty\""
	SourceURL          string           "json:\"source_url,omitempty\""
	PublicKey          string           "json:\"public_key,omitempty\""
	Status             string           "json:\"status\""
	AppSchemaVersion   int              "json:\"app_schema_version,omitempty\""
	MinClientVersion   string           "json:\"min_supported_client_version,omitempty\""
	CurrentVersion     string           "json:\"current_client_version,omitempty\""
	CompatibilityUntil string           "json:\"compatibility_until,omitempty\""
	CreatedAt          string           "json:\"created_at,omitempty\""
	UpdatedAt          string           "json:\"updated_at,omitempty\""
	ManifestVersion    int              "json:\"manifest_version,omitempty\""
	ManifestHash       string           "json:\"manifest_hash,omitempty\""
	ManifestSignature  string           "json:\"manifest_signature,omitempty\""
	ApprovalSignature  string           "json:\"approval_signature,omitempty\""
	ManifestExpiresAt  int64            "json:\"manifest_expires_at,omitempty\""
	Collections        []AppCollection  "json:\"collections,omitempty\""
	Capabilities       []string         "json:\"capabilities,omitempty\""
	Features           []AppFeature     "json:\"features,omitempty\""
	LegacyProtocols    []LegacyProtocol "json:\"legacy_protocols,omitempty\""
	Keys               []AppKey         "json:\"keys,omitempty\""
	TokenPolicies      []TokenPolicy    "json:\"token_policies,omitempty\""
}

type AppRegistryResponse struct {
	Apps []AppRegistration "json:\"apps\""
}

func Manifest_Normalize(manifest *AppManifest) {
	var value_0 string = strings.TrimSpace(manifest.AppID)
	manifest.AppID = value_0
	var value_1 string = strings.TrimSpace(manifest.DisplayName)
	manifest.DisplayName = value_1
	var value_2 string = strings.TrimSpace(manifest.Description)
	manifest.Description = value_2
	var value_3 string = strings.TrimSpace(manifest.HomepageURL)
	manifest.HomepageURL = value_3
	var value_4 string = strings.TrimSpace(manifest.SourceURL)
	manifest.SourceURL = value_4
	var value_5 string = strings.TrimSpace(manifest.Status)
	manifest.Status = value_5
	if manifest.Status == "" {
		manifest.Status = "active"
	}
	var index int64 = 0
	var inner int64 = 0
	index = 0
	for index < int64(len(manifest.Keys)) {
		var value_6 string = strings.TrimSpace((manifest.Keys[index]).KeyID)
		(manifest.Keys[index]).KeyID = value_6
		var value_7 string = strings.TrimSpace((manifest.Keys[index]).Algorithm)
		(manifest.Keys[index]).Algorithm = value_7
		var value_8 string = strings.TrimSpace((manifest.Keys[index]).PublicKey)
		(manifest.Keys[index]).PublicKey = value_8
		var value_9 string = strings.TrimSpace((manifest.Keys[index]).Purpose)
		(manifest.Keys[index]).Purpose = value_9
		var value_10 string = strings.TrimSpace((manifest.Keys[index]).Status)
		(manifest.Keys[index]).Status = value_10
		index++
	}
	index = 0
	for index < int64(len(manifest.Collections)) {
		(manifest.Collections[index]).AppID = manifest.AppID
		var value_11 string = strings.TrimSpace((manifest.Collections[index]).CollectionPrefix)
		(manifest.Collections[index]).CollectionPrefix = value_11
		var value_12 string = strings.TrimSpace((manifest.Collections[index]).Visibility)
		(manifest.Collections[index]).Visibility = value_12
		var value_13 string = strings.TrimSpace((manifest.Collections[index]).Description)
		(manifest.Collections[index]).Description = value_13
		index++
	}
	index = 0
	for index < int64(len(manifest.Capabilities)) {
		var value_14 string = strings.TrimSpace(manifest.Capabilities[index])
		manifest.Capabilities[index] = value_14
		index++
	}
	index = 0
	for index < int64(len(manifest.Features)) {
		var value_15 string = strings.TrimSpace((manifest.Features[index]).ID)
		(manifest.Features[index]).ID = value_15
		var value_16 string = strings.TrimSpace((manifest.Features[index]).Description)
		(manifest.Features[index]).Description = value_16
		inner = 0
		for inner < int64(len((manifest.Features[index]).Collections)) {
			var value_17 string = strings.TrimSpace((manifest.Features[index]).Collections[inner])
			(manifest.Features[index]).Collections[inner] = value_17
			inner++
		}
		index++
	}
	index = 0
	for index < int64(len(manifest.LegacyProtocols)) {
		var value_18 string = strings.TrimSpace((manifest.LegacyProtocols[index]).Name)
		(manifest.LegacyProtocols[index]).Name = value_18
		var value_19 string = strings.TrimSpace((manifest.LegacyProtocols[index]).Status)
		(manifest.LegacyProtocols[index]).Status = value_19
		var value_20 string = strings.TrimSpace((manifest.LegacyProtocols[index]).ValidUntil)
		(manifest.LegacyProtocols[index]).ValidUntil = value_20
		index++
	}
	var value_21 string = strings.TrimSpace(manifest.MinClientVersion)
	manifest.MinClientVersion = value_21
	var value_22 string = strings.TrimSpace(manifest.CurrentVersion)
	manifest.CurrentVersion = value_22
	var value_23 string = strings.TrimSpace(manifest.CompatibilityUntil)
	manifest.CompatibilityUntil = value_23
	index = 0
	for index < int64(len(manifest.TokenPolicies)) {
		var value_24 string = strings.TrimSpace((manifest.TokenPolicies[index]).AssetID)
		(manifest.TokenPolicies[index]).AssetID = value_24
		var value_25 string = strings.TrimSpace((manifest.TokenPolicies[index]).Permission)
		(manifest.TokenPolicies[index]).Permission = value_25
		var value_26 string = strings.TrimSpace((manifest.TokenPolicies[index]).Status)
		(manifest.TokenPolicies[index]).Status = value_26
		if (manifest.TokenPolicies[index]).Status == "" {
			(manifest.TokenPolicies[index]).Status = "active"
		}
		index++
	}
}

func Manifest_ValidDate(value string) bool {
	if int64(len(value)) != 10 || value[4] != 45 || value[7] != 45 {
		return false
	}
	var index int64 = 0
	for index < 10 {
		if index != 4 && index != 7 {
			if value[index] < 48 || value[index] > 57 {
				return false
			}
		}
		index++
	}
	var year int64 = 0
	index = 0
	for index < 4 {
		year = ((year * 10) + int64(value[index])) - 48
		index++
	}
	month := (((int64(value[5]) - 48) * 10) + int64(value[6])) - 48
	day := (((int64(value[8]) - 48) * 10) + int64(value[9])) - 48
	if month < 1 || month > 12 || day < 1 {
		return false
	}
	var days int64 = 31
	if month == 4 || month == 6 || month == 9 || month == 11 {
		days = 30
	}
	if month == 2 {
		days = 28
		if year%4 == 0 && (year%100 != 0 || year%400 == 0) {
			days = 29
		}
	}
	return day <= days
}

func Manifest_DefaultString(value string, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func Manifest_Validate(manifest AppManifest, now int64) string {
	if manifest.ManifestVersion != int(1) {
		return "unsupported manifest_version"
	}
	var value_0 bool = Identity_ValidNamespace(manifest.AppID)
	if !value_0 {
		return "invalid app_id"
	}
	if manifest.DisplayName == "" || int64(len(manifest.DisplayName)) > 80 {
		return "invalid display_name"
	}
	if manifest.Status != "active" && manifest.Status != "suspended" {
		return "invalid status"
	}
	if int64(len(manifest.Keys)) == 0 || int64(len(manifest.Keys)) > 16 {
		return "invalid app keys"
	}
	if manifest.AppSchemaVersion < int(0) || manifest.AppSchemaVersion > int(65535) {
		return "invalid app_schema_version"
	}
	var value_1 bool = manifest.CompatibilityUntil != ""
	if value_1 {
		var value_2 bool = Manifest_ValidDate(manifest.CompatibilityUntil)
		value_1 = !value_2
	}
	if value_1 {
		return "invalid compatibility_until"
	}
	var value_3 bool = int64(len(manifest.Collections)) > 64 || int64(len(manifest.Capabilities)) > 64 || int64(len(manifest.Features)) > 128
	if value_3 || int64(len(manifest.LegacyProtocols)) > 64 || int64(len(manifest.TokenPolicies)) > 64 {
		return "too many manifest fields"
	}
	var index int64 = 0
	for index < int64(len(manifest.Keys)) {
		key := manifest.Keys[index]
		var value_4 bool = Identity_ValidClientID(key.KeyID)
		var value_5 bool = !value_4
		if !value_5 {
			var value_6 bool = strings.EqualFold(key.Algorithm, "Ed25519")
			value_5 = !value_6
		}
		if value_5 {
			return "invalid app key"
		}
		publicKey := Codec_DecodeBinaryField(key.PublicKey)
		if publicKey.Error != "" || int64(len(publicKey.Value)) != 32 {
			return "invalid app public key"
		}
		if key.Status != "" && key.Status != "active" && key.Status != "suspended" {
			return "invalid app key status"
		}
		index++
	}
	index = 0
	for index < int64(len(manifest.Collections)) {
		collection := manifest.Collections[index]
		var value_7 bool = Scope_ValidCollectionPrefix(collection.CollectionPrefix)
		var value_8 bool = !value_7
		if !value_8 {
			var value_9 bool = Scope_ValidAppVisibility(collection.Visibility)
			value_8 = !value_9
		}
		var value_10 bool = value_8
		if !value_10 {
			var value_11 bool = Scope_AppOwnsDeclaredScope(manifest.AppID, collection)
			value_10 = !value_11
		}
		if value_10 {
			return "invalid app collection"
		}
		index++
	}
	index = 0
	for index < int64(len(manifest.Capabilities)) {
		var value_12 bool = Identity_ValidNamespace(manifest.Capabilities[index])
		if !value_12 {
			return "invalid capability"
		}
		index++
	}
	index = 0
	for index < int64(len(manifest.Features)) {
		feature := manifest.Features[index]
		var value_13 bool = Identity_ValidNamespace(feature.ID)
		if !value_13 || int64(len(feature.Collections)) > 16 {
			return "invalid app feature"
		}
		var inner int64 = 0
		for inner < int64(len(feature.Collections)) {
			var value_14 bool = Scope_DeclaresCollection(manifest.Collections, feature.Collections[inner])
			if !value_14 {
				return "invalid app feature collection"
			}
			inner++
		}
		index++
	}
	index = 0
	for index < int64(len(manifest.LegacyProtocols)) {
		legacy := manifest.LegacyProtocols[index]
		var value_15 bool = Identity_ValidNamespace(legacy.Name)
		var value_16 bool = !value_15 || legacy.Version < int(0)
		if !value_16 {
			var value_17 bool = Scope_ValidLegacyProtocolStatus(legacy.Status)
			value_16 = !value_17
		}
		var value_18 bool = value_16
		if !value_18 {
			var value_19 bool = Manifest_ValidDate(legacy.ValidUntil)
			value_18 = !value_19
		}
		if value_18 {
			return "invalid legacy protocol"
		}
		index++
	}
	index = 0
	for index < int64(len(manifest.TokenPolicies)) {
		policy := manifest.TokenPolicies[index]
		var value_20 bool = Scope_ValidTokenPolicyPermission(policy.Permission)
		var value_21 bool = !value_20
		if !value_21 {
			var value_22 bool = strings.TrimSpace(policy.AssetID) == ""
			value_21 = value_22
		}
		if value_21 {
			return "invalid token policy"
		}
		if policy.Status != "" && policy.Status != "active" && policy.Status != "suspended" {
			return "invalid token policy status"
		}
		var value_23 bool = policy.LegacyUnsignedUntil < 0 || (policy.LegacyUnsignedUntil > now && uint64(policy.LegacyUnsignedUntil)-uint64(now) > 31536000)
		if value_23 {
			return "invalid legacy_unsigned_until"
		}
		index++
	}
	if manifest.ExpiresAt > 0 && now > manifest.ExpiresAt {
		return "manifest expired"
	}
	return ""
}

func Manifest_SignedByActiveKey(manifest AppManifest, message []uint8, signature []uint8, now int64) bool {
	var index int64 = 0
	for index < int64(len(manifest.Keys)) {
		key := manifest.Keys[index]
		index++
		if Manifest_DefaultString(key.Status, "active") != "active" {
			continue
		}
		if key.ExpiresAt > 0 && now > key.ExpiresAt {
			continue
		}
		var value_0 bool = strings.EqualFold(key.Algorithm, "Ed25519")
		if !value_0 {
			continue
		}
		decoded := Codec_DecodeBinaryField(key.PublicKey)
		if decoded.Error != "" || int64(len(decoded.Value)) != 32 {
			continue
		}
		var publicKey [32]uint8
		var byteIndex int64 = 0
		for byteIndex < 32 {
			publicKey[byteIndex] = decoded.Value[byteIndex]
			byteIndex++
		}
		if ed25519.Verify(publicKey[0:32:32], message, signature) {
			return true
		}
	}
	return false
}
