// Code generated by zi2go from mesh_cursor.zi. DO NOT EDIT.
package main

import (
	base64 "encoding/base64"
	strings "strings"
)

// #import std_go_types
// #import protocol
// #import mesh_types
type CursorResult struct {
	Value MeshCursor
	Error Error
}

type CursorTextResult struct {
	Value string
	Error Error
}

type Encoding = base64.Encoding

type BytesResult struct {
	Value []uint8
	Error Error
}

func MeshCursor_RawURL() *Encoding {
	return base64.RawURLEncoding
}

func MeshCursor_DecodeRaw(Encoding *Encoding, Value string) BytesResult {
	var result BytesResult
	result.Value, result.Error = (*base64.Encoding).DecodeString(Encoding, Value)
	return result
}

func MeshCursor_Encode(cursor MeshCursor) CursorTextResult {
	var result CursorTextResult = CursorTextResult{}
	encoded := StdJsonGo_Marshal(cursor)
	result.Error = encoded.Error
	if result.Error != nil {
		return result
	}
	var value_0 string = (*base64.Encoding).EncodeToString(MeshCursor_RawURL(), encoded.Value)
	result.Value = value_0
	return result
}

func MeshCursor_Decode(raw string) CursorResult {
	var result CursorResult = CursorResult{}
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return result
	}
	var value_0 *Encoding = MeshCursor_RawURL()
	decoded := MeshCursor_DecodeRaw(value_0, raw)
	if decoded.Error != nil {
		var value_1 Error = StdErrorsGo_New("invalid mesh cursor")
		result.Error = value_1
		return result
	}
	var cursor MeshCursor = MeshCursor{}
	var value_2 Error = StdJsonGo_Unmarshal(decoded.Value, &(cursor))
	if value_2 != nil {
		var value_3 Error = StdErrorsGo_New("invalid mesh cursor")
		result.Error = value_3
		return result
	}
	result.Value = cursor
	return result
}

func MeshCursor_PeerKey(baseURL string, policy NodeSyncPolicy) string {
	encoded := StdJsonGo_Marshal(policy)
	var value_0 string = strings.TrimRight(baseURL, "/")
	var value_1 string = StdTextGo_FromBytes(encoded.Value)
	parts := [3]string{value_0, "\x00", value_1}
	_ = parts
	return Signing_SHA256Hex(StdTextGo_ToBytes(strings.Join(parts[0:3:3], "")))
}

func MeshCursor_BatchLimit(requested int, configured int) int {
	limit := configured
	if limit <= int(0) {
		limit = int(500)
	}
	if requested > int(0) && requested < limit {
		limit = requested
	}
	if limit > int(2000) {
		return int(2000)
	}
	return limit
}
