// Code generated by zi2go from mesh.zi. DO NOT EDIT.
package main

import (
	bytes "bytes"
	fmt "fmt"
	io "io"
	slog "log/slog"
	strings "strings"
	time "time"
)

// #import std_go_types
// #import protocol
// #import mesh_types
// #import node_identity
type Mesh struct {
	Database      *Database
	Configuration *Config
	Identity      *NodeIdentity
	ConvertError  ConvertError
}

type HeaderParts struct {
	Before string
	After  string
	Found  bool
}

func Mesh_Cut(Value string, Separator string) HeaderParts {
	var result HeaderParts
	result.Before, result.After, result.Found = strings.Cut(Value, Separator)
	return result
}

func Mesh_Run(mesh Mesh, context Context) {
	if int64(mesh.Configuration.NodeSyncInterval) <= 0 {
		return
	}
	ticker := StdTimeGo_NewTicker(mesh.Configuration.NodeSyncInterval)
	defer (*time.Ticker).Stop(ticker)
	Mesh_PullPeers(mesh, context)
	for true {
		var cases [2]Case
		var value_0 Case = StdSelectGo_Receive(StdContextGo_Done(context))
		cases[0] = value_0
		var value_1 Case = StdSelectGo_Receive(StdTimeGo_TickerChannel(ticker))
		cases[1] = value_1
		var value_2 SelectResult = StdSelectGo_Select(cases[0:2:2])
		if value_2.Chosen == int(0) {
			return
		}
		Mesh_PullPeers(mesh, context)
	}
}

func Mesh_Export(mesh Mesh, writer ResponseWriter, request *Request) {
	body := HttpBody_ReadJSON(writer, request, mesh.Configuration.MaxBodyBytes)
	if body.Error != nil {
		Response_Error(writer, int(400), StdErrorsGo_Message(body.Error))
		return
	}
	var value_0 bool = Mesh_Authorize(mesh, writer, request, body.Value)
	if !value_0 {
		return
	}
	var input NodeMeshExportRequest = NodeMeshExportRequest{}
	var value_1 []uint8 = bytes.TrimSpace(body.Value)
	if int64(len(value_1)) > 0 {
		var value_2 Error = StdJsonGo_Unmarshal(body.Value, &(input))
		if value_2 != nil {
			Response_Error(writer, int(400), "invalid mesh export request")
			return
		}
	}
	var value_3 bool = MeshPolicy_ValidInbound(input.Policy)
	if !value_3 {
		Response_Error(writer, int(400), "explicit mesh policy required")
		return
	}
	var value_4 bool = Mesh_AuthorizePolicy(mesh, writer, request, input.Policy, "export")
	if !value_4 {
		return
	}
	context := StdHttpGo_Context(request)
	exportedApps := MeshApps_Export(mesh.Database, context, input.Policy)
	if exportedApps.Error != nil {
		slog.Error("mesh app registry export", "error", exportedApps.Error)
		Response_Error(writer, int(500), "mesh app registry export failed")
		return
	}
	limit := MeshCursor_BatchLimit(input.Limit, mesh.Configuration.NodeSyncBatchLimit)
	exportedRecords := MeshStore_ExportEncryptedRecords(mesh.Database, context, input.Policy, input.Cursor, limit)
	if exportedRecords.Error != nil {
		slog.Error("mesh export", "error", exportedRecords.Error)
		Response_Error(writer, int(500), "mesh export failed")
		return
	}
	exportedNames := TrustStore_ExportMeshNames(mesh.Database, context, input.Policy)
	if exportedNames.Error != nil {
		slog.Error("mesh name export", "error", exportedNames.Error)
		Response_Error(writer, int(500), "mesh name export failed")
		return
	}
	var value NodeMeshExportResponse = NodeMeshExportResponse{}
	value.Status = "ok"
	value.Apps = exportedApps.Value
	value.Records = exportedRecords.Records
	value.Deletions = exportedRecords.Deletions
	value.Spaces = exportedNames.Spaces
	value.Names = exportedNames.Names
	value.NextCursor = exportedRecords.NextCursor
	value.Truncated = exportedRecords.Truncated
	Response_JSON(writer, int(200), value)
}

func Mesh_Import(mesh Mesh, writer ResponseWriter, request *Request) {
	body := HttpBody_ReadJSON(writer, request, mesh.Configuration.MaxBodyBytes)
	if body.Error != nil {
		Response_Error(writer, int(400), StdErrorsGo_Message(body.Error))
		return
	}
	var value_0 bool = Mesh_Authorize(mesh, writer, request, body.Value)
	if !value_0 {
		return
	}
	var input NodeMeshImportRequest = NodeMeshImportRequest{}
	var value_1 Error = StdJsonGo_Unmarshal(body.Value, &(input))
	if value_1 != nil {
		Response_Error(writer, int(400), "invalid mesh import request")
		return
	}
	var value_2 bool = MeshPolicy_ValidInbound(input.Policy)
	if !value_2 {
		Response_Error(writer, int(400), "explicit mesh policy required")
		return
	}
	var value_3 bool = Mesh_AuthorizePolicy(mesh, writer, request, input.Policy, "import")
	if !value_3 {
		return
	}
	context := StdHttpGo_Context(request)
	importedApps := MeshApps_Import(mesh.Database, context, mesh.Configuration.NodeRegistryPublicKey, input.Policy, input.Apps, mesh.ConvertError)
	if importedApps.Error != nil {
		slog.Error("mesh app registry import", "error", importedApps.Error)
		Response_Error(writer, int(400), StdErrorsGo_Message(importedApps.Error))
		return
	}
	importedRecords := MeshStore_ImportEncryptedBatch(mesh.Database, context, input.Policy, input.Records, input.Deletions)
	if importedRecords.Error != nil {
		slog.Error("mesh import", "error", importedRecords.Error)
		Response_Error(writer, int(400), StdErrorsGo_Message(importedRecords.Error))
		return
	}
	importedNames := TrustStore_ImportMeshNames(mesh.Database, context, input.Policy, input.Spaces, input.Names)
	if importedNames.Error != nil {
		slog.Error("mesh name import", "error", importedNames.Error)
		Response_Error(writer, int(400), StdErrorsGo_Message(importedNames.Error))
		return
	}
	var value NodeMeshImportResponse = NodeMeshImportResponse{}
	value.Status = "ok"
	var value_4 int64 = ((int64(len(input.Apps)) + int64(len(input.Records))) + int64(len(input.Deletions))) + int64(len(input.Names))
	value.Records = int(value_4)
	value.Applied = (importedApps.Value + importedRecords.Value) + importedNames.Value
	Response_JSON(writer, int(200), value)
}

func Mesh_Authorize(mesh Mesh, writer ResponseWriter, request *Request, body []uint8) bool {
	headers := StdHttpGo_Headers(request)
	if strings.TrimSpace(StdHttpGo_HeaderValue(headers, "X-Daochi-Node-ID")) != "" {
		error := NodeAuth_Verify(mesh.Database, StdHttpGo_Context(request), request, body)
		if error != nil {
			Response_Error(writer, int(401), StdErrorsGo_Message(error))
			return false
		}
		return true
	}
	token := strings.TrimSpace(mesh.Configuration.NodeSyncToken)
	if token == "" {
		Response_Error(writer, int(503), "node sync disabled")
		return false
	}
	var value_0 [2]string
	value_0[0] = "X-Daochi-Node-Token"
	value_0[1] = "X-Ksync-Node-Token"
	names := value_0
	_ = names
	provided := strings.TrimSpace(HttpAuth_HeaderAlias(request, names[0:2:2]))
	if provided == "" {
		provided = Mesh_BearerToken(StdHttpGo_HeaderValue(headers, "Authorization"))
	}
	var value_1 bool = provided == ""
	if !value_1 {
		var value_2 bool = StdConstantTime_ConstantTimeTextEqual(provided, token)
		value_1 = !value_2
	}
	if value_1 {
		Response_Error(writer, int(401), "invalid node token")
		return false
	}
	return true
}

func Mesh_AuthorizePolicy(mesh Mesh, writer ResponseWriter, request *Request, requested NodeSyncPolicy, operation string) bool {
	nodeID := strings.TrimSpace(StdHttpGo_HeaderValue(StdHttpGo_Headers(request), "X-Daochi-Node-ID"))
	if nodeID == "" {
		return true
	}
	approved := TrustStore_TrustedPeerPolicy(mesh.Database, StdHttpGo_Context(request), nodeID)
	if approved.Error != nil {
		Response_Error(writer, int(500), "peer policy lookup failed")
		return false
	}
	var value_0 bool = !approved.Found
	if !value_0 {
		var value_1 bool = MeshPolicy_AllowsOperation(approved.Value, requested, operation)
		value_0 = !value_1
	}
	if value_0 {
		Response_Error(writer, int(403), "requested mesh policy exceeds paired scope")
		return false
	}
	return true
}

func Mesh_BearerToken(header string) string {
	cut := Mesh_Cut(strings.TrimSpace(header), " ")
	var value_0 bool = cut.Found
	if value_0 {
		var value_1 bool = strings.EqualFold(cut.Before, "Bearer")
		value_0 = value_1
	}
	if value_0 {
		return strings.TrimSpace(cut.After)
	}
	return ""
}

func Mesh_PullPeers(mesh Mesh, context Context) {
	peers := make([]NodePeer, int(int(int64(len(mesh.Configuration.KnownNodes)))))
	{
		value_0 := mesh.Configuration.KnownNodes[:]
		if int64(0) < 0 || int64(int64(len(value_0))) < int64(0) || int64(int64(len(value_0))) > int64(len(value_0)) {
			panic("slice range out of bounds")
		}
		loop_view_1 := value_0[0:int64(len(value_0)):int64(len(value_0))]
		loop_count_1 := int64(len(loop_view_1))
		var loop_cursor_1 int64 = 0
		for loop_cursor_1 < loop_count_1 {
			loop_index_1 := loop_cursor_1
			peer := loop_view_1[loop_index_1]
			_ = peer
			index := loop_index_1
			peers[index] = peer
			loop_cursor_1++
		}
	}
	listed := TrustStore_ListTrustedPeers(mesh.Database, context)
	if listed.Error != nil {
		slog.Warn("load paired mesh peers", "error", listed.Error)
	}
	{
		value_1 := listed.Value[:]
		if int64(0) < 0 || int64(int64(len(value_1))) < int64(0) || int64(int64(len(value_1))) > int64(len(value_1)) {
			panic("slice range out of bounds")
		}
		loop_view_8 := value_1[0:int64(len(value_1)):int64(len(value_1))]
		loop_count_8 := int64(len(loop_view_8))
		var loop_cursor_8 int64 = 0
		for loop_cursor_8 < loop_count_8 {
			loop_index_8 := loop_cursor_8
			item := loop_view_8[loop_index_8]
			if int64(len(item.Addresses)) > 0 {
				sync := item.Policy
				var peer NodePeer = NodePeer{}
				_ = peer
				peer.Name = item.DisplayName
				peer.URL = item.Addresses[0]
				peer.NodeID = item.NodeID
				peer.Sync = &(sync)
				peers = append(peers, peer)
			}
			loop_cursor_8++
		}
	}
	for it_index := int64(0); it_index < int64(len(peers)); it_index++ {
		peer := peers[it_index]
		_ = peer
		var value_2 bool = MeshPolicy_AllowsPull(peer.Sync)
		if !value_2 {
			continue
		}
		error := Mesh_PullPeer(mesh, context, peer)
		if error != nil {
			slog.Warn("mesh peer pull failed", "peer", peer.Name, "url", peer.URL, "error", error)
		}
	}
}

func Mesh_PullPeer(mesh Mesh, context Context, peer NodePeer) Error {
	baseURL := strings.TrimRight(strings.TrimSpace(peer.URL), "/")
	if baseURL == "" {
		return nil
	}
	var sync NodeSyncPolicy = NodeSyncPolicy{}
	if peer.Sync != nil {
		sync = *(peer.Sync)
	}
	peerKey := MeshCursor_PeerKey(baseURL, sync)
	loaded := MeshStore_LoadCursor(mesh.Database, context, peerKey)
	if loaded.Error != nil {
		return loaded.Error
	}
	currentCursor := loaded.Value
	for true {
		var request NodeMeshExportRequest = NodeMeshExportRequest{}
		request.Cursor = currentCursor
		request.Limit = MeshCursor_BatchLimit(int(0), mesh.Configuration.NodeSyncBatchLimit)
		request.Policy = sync
		var exported NodeMeshExportResponse = NodeMeshExportResponse{}
		var value_0 [2]string
		value_0[0] = baseURL
		value_0[1] = "/api/v1/node/mesh/export"
		target := value_0
		_ = target
		error := Mesh_PostJSON(mesh, context, peer.NodeID, strings.Join(target[0:2:2], ""), request, &(exported))
		if error != nil {
			return error
		}
		var value_1 bool = int64(len(exported.Apps)) == 0 && int64(len(exported.Records)) == 0 && int64(len(exported.Deletions)) == 0
		if value_1 && int64(len(exported.Names)) == 0 {
			return nil
		}
		importedApps := MeshApps_Import(mesh.Database, context, mesh.Configuration.NodeRegistryPublicKey, sync, exported.Apps, mesh.ConvertError)
		if importedApps.Error != nil {
			return importedApps.Error
		}
		importedRecords := MeshStore_ImportEncryptedBatch(mesh.Database, context, sync, exported.Records, exported.Deletions)
		if importedRecords.Error != nil {
			return importedRecords.Error
		}
		importedNames := TrustStore_ImportMeshNames(mesh.Database, context, sync, exported.Spaces, exported.Names)
		if importedNames.Error != nil {
			return importedNames.Error
		}
		slog.Info("mesh peer pull applied changes", "peer", peer.Name, "url", baseURL, "apps", int(int(int64(len(exported.Apps)))), "records", int(int(int64(len(exported.Records)))), "deletions", int(int(int64(len(exported.Deletions)))), "names", int(int(int64(len(exported.Names)))), "applied", int((importedApps.Value+importedRecords.Value)+importedNames.Value))
		lastCursor := exported.NextCursor
		if lastCursor == "" {
			var lastSequence int64 = 0
			{
				value_2 := exported.Records[:]
				if int64(0) < 0 || int64(int64(len(value_2))) < int64(0) || int64(int64(len(value_2))) > int64(len(value_2)) {
					panic("slice range out of bounds")
				}
				loop_view_44 := value_2[0:int64(len(value_2)):int64(len(value_2))]
				loop_count_44 := int64(len(loop_view_44))
				var loop_cursor_44 int64 = 0
				for loop_cursor_44 < loop_count_44 {
					loop_index_44 := loop_cursor_44
					record := loop_view_44[loop_index_44]
					if record.MeshVersion > lastSequence {
						lastSequence = record.MeshVersion
					}
					loop_cursor_44++
				}
			}
			{
				value_3 := exported.Deletions[:]
				if int64(0) < 0 || int64(int64(len(value_3))) < int64(0) || int64(int64(len(value_3))) > int64(len(value_3)) {
					panic("slice range out of bounds")
				}
				loop_view_49 := value_3[0:int64(len(value_3)):int64(len(value_3))]
				loop_count_49 := int64(len(loop_view_49))
				var loop_cursor_49 int64 = 0
				for loop_cursor_49 < loop_count_49 {
					loop_index_49 := loop_cursor_49
					deletion := loop_view_49[loop_index_49]
					if deletion.MeshVersion > lastSequence {
						lastSequence = deletion.MeshVersion
					}
					loop_cursor_49++
				}
			}
			var value MeshCursor = MeshCursor{}
			value.Seq = lastSequence
			encoded := MeshCursor_Encode(value)
			if encoded.Error != nil {
				return encoded.Error
			}
			lastCursor = encoded.Value
		}
		cursorError := MeshStore_SaveCursor(mesh.Database, context, peerKey, lastCursor)
		if cursorError != nil {
			return cursorError
		}
		if !exported.Truncated || exported.NextCursor == "" {
			return nil
		}
		currentCursor = exported.NextCursor
	}
	return nil
}

func Mesh_PostJSON(mesh Mesh, context Context, peerNodeID string, target string, request Any, reply Any) Error {
	encoded := StdJsonGo_Marshal(request)
	if encoded.Error != nil {
		return encoded.Error
	}
	outbound := StdHttpGo_NewRequest(context, "POST", target, StdIoGo_FromBytes(encoded.Value))
	if outbound.Error != nil {
		return outbound.Error
	}
	headers := StdHttpGo_Headers(outbound.Value)
	StdHttpGo_SetHeader(headers, "Content-Type", "application/json")
	if peerNodeID != "" {
		NodeAuth_Sign(mesh.Identity.ID, mesh.Identity.PrivateKey, outbound.Value, encoded.Value)
	} else {
		var value_0 [2]string
		value_0[0] = "Bearer "
		value_0[1] = mesh.Configuration.NodeSyncToken
		token := value_0
		_ = token
		StdHttpGo_SetHeader(headers, "Authorization", strings.Join(token[0:2:2], ""))
	}
	client := StdHttpGo_NewClient(Duration(20000000000))
	result := StdHttpGo_Do(client, outbound.Value)
	if result.Error != nil {
		return result.Error
	}
	body := StdHttpGo_ResponseBody(result.Value)
	defer (io.ReadCloser).Close(body)
	status := StdHttpGo_StatusCode(result.Value)
	if status < int(200) || status >= int(300) {
		data := StdIoGo_ReadAll(StdIoGo_LimitReader(Reader(body), 2048))
		return fmt.Errorf("node mesh request failed: %s %s", StdHttpGo_Status(result.Value), strings.TrimSpace(StdTextGo_FromBytes(data.Value)))
	}
	return StdJsonGo_Decode(StdJsonGo_NewDecoder(Reader(body)), reply)
}
