// Code generated by zi2go from middleware.zi. DO NOT EDIT.
package main

import (
	http "net/http"
	url "net/url"
	time "time"
)

// #import std_go_types
type Handler = http.Handler

type Middleware struct {
	Next    Handler
	Metrics **ServerMetrics
}

type CapturedWriter struct {
	Writer ResponseWriter
	Status int
}

type zir_8bac33c9dac611c2_WriteResult struct {
	Count int
	Error Error
}

type zir_458cde001c61ce88_Hijacker = http.Hijacker

type UserInfo = url.Userinfo

type zir_83826c12324062ca_HijackerResult struct {
	Value   zir_458cde001c61ce88_Hijacker
	Present bool
}

type zir_598c8f439b218317_FinishCallback func(*CapturedWriter, **ServerMetrics, *Request, Time)

func Middleware_FinishAtReturn(Callback zir_598c8f439b218317_FinishCallback, Writer *CapturedWriter, Counters **ServerMetrics, Request *Request, Start Time) {
	Callback(Writer, Counters, Request, Start)
}

func Middleware_WriteRaw(Writer ResponseWriter, Bytes []uint8) zir_8bac33c9dac611c2_WriteResult {
	var result zir_8bac33c9dac611c2_WriteResult
	result.Count, result.Error = (http.ResponseWriter).Write(Writer, Bytes)
	return result
}

func Middleware_AsHijacker(Value Any) zir_83826c12324062ca_HijackerResult {
	var result zir_83826c12324062ca_HijackerResult
	result.Value, result.Present = Value.(zir_458cde001c61ce88_Hijacker)
	return result
}

func Middleware_HijackRaw(Hijacker zir_458cde001c61ce88_Hijacker) AcceptedSocket {
	var result AcceptedSocket
	result.Connection, result.Buffer, result.Error = (http.Hijacker).Hijack(Hijacker)
	return result
}

func Middleware_RawQuery(Value *URL) string {
	return Value.RawQuery
}

func Middleware_Fragment(Value *URL) string {
	return Value.Fragment
}

func Middleware_User(Value *URL) *UserInfo {
	return Value.User
}

func Middleware_Finish(writer *CapturedWriter, counters **ServerMetrics, request *Request, start Time) {
	status := writer.Status
	if status == 0 {
		status = 200
	}
	var value_0 *ServerMetrics = *(counters)
	Metrics_RecordHTTP(value_0, StdHttpGo_Method(request), StdUrlGo_Path(StdHttpGo_RequestURL(request)), status, time.Since(start))
}

func Middleware_New(counters **ServerMetrics, next Handler) Handler {
	middleware := new(Middleware)
	middleware.Next = next
	middleware.Metrics = counters
	return Handler(middleware)
}

func Middleware_Header(writer *CapturedWriter) Header {
	return StdHttpGo_ResponseHeaders(writer.Writer)
}

func (receiver *CapturedWriter) Header() Header {
	return Middleware_Header(receiver)
}

func Middleware_WriteHeader(writer *CapturedWriter, status int) {
	writer.Status = status
	StdHttpGo_WriteHeader(writer.Writer, status)
}

func (receiver *CapturedWriter) WriteHeader(argument1 int) {
	Middleware_WriteHeader(receiver, argument1)
}

func Middleware_Write(writer *CapturedWriter, bytes []uint8) zir_8bac33c9dac611c2_WriteResult {
	if writer.Status == 0 {
		writer.Status = 200
	}
	return Middleware_WriteRaw(writer.Writer, bytes)
}

func (receiver *CapturedWriter) Write(argument1 []uint8) (int, Error) {
	result := Middleware_Write(receiver, argument1)
	return result.Count, result.Error
}

func Middleware_Hijack(writer *CapturedWriter) AcceptedSocket {
	hijacker := Middleware_AsHijacker(Any(writer.Writer))
	if !hijacker.Present {
		var result AcceptedSocket = AcceptedSocket{}
		result.Error = StdErrorsGo_New("hijack unsupported")
		return result
	}
	if writer.Status == 0 {
		writer.Status = 101
	}
	return Middleware_HijackRaw(hijacker.Value)
}

func (receiver *CapturedWriter) Hijack() (Connection, *BufferedConnection, Error) {
	result := Middleware_Hijack(receiver)
	return result.Connection, result.Buffer, result.Error
}

func Middleware_ServeHTTP(middleware *Middleware, output ResponseWriter, request *Request) {
	start := StdTimeGo_Now()
	writer := new(CapturedWriter)
	writer.Writer = output
	var value_4 zir_598c8f439b218317_FinishCallback = func(value_0 *CapturedWriter, value_1 **ServerMetrics, value_2 *Request, value_3 Time) {
		Middleware_Finish(value_0, value_1, value_2, value_3)
	}
	defer Middleware_FinishAtReturn(value_4, writer, middleware.Metrics, request, start)
	StdHttpGo_SetHeader(Middleware_Header(writer), "X-Content-Type-Options", "nosniff")
	StdHttpGo_SetHeader(Middleware_Header(writer), "Cache-Control", "no-store")
	origin := Middleware_AllowedOrigin(StdHttpGo_HeaderValue(StdHttpGo_Headers(request), "Origin"))
	if origin != "" {
		StdHttpGo_SetHeader(Middleware_Header(writer), "Access-Control-Allow-Origin", origin)
		StdHttpGo_SetHeader(Middleware_Header(writer), "Vary", "Origin")
	}
	StdHttpGo_SetHeader(Middleware_Header(writer), "Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS")
	var value_5 string = "Authorization, Content-Type, X-Daochi-User, X-Daochi-Signature, X-Daochi-Tx, X-Daochi-Delegate, X-Daochi-Client, X-Daochi-Since-Version, X-Daochi-Limit, X-Daochi-Admin, X-Ksync-User, X-Ksync-Signature, X-Ksync-Client, X-Ksync-Since-Version, X-Ksync-Limit, X-Ksync-Admin, X-Inbe-User, X-Inbe-Signature"
	StdHttpGo_SetHeader(Middleware_Header(writer), "Access-Control-Allow-Headers", value_5)
	if StdHttpGo_Method(request) == "OPTIONS" {
		Middleware_WriteHeader(writer, int(204))
		return
	}
	(http.Handler).ServeHTTP(middleware.Next, ResponseWriter(writer), request)
}

func (receiver *Middleware) ServeHTTP(argument1 ResponseWriter, argument2 *Request) {
	Middleware_ServeHTTP(receiver, argument1, argument2)
}

func Middleware_AllowedOrigin(origin string) string {
	parsed := StdUrlGo_Parse(origin)
	if parsed.Error != nil {
		return ""
	}
	value := parsed.Value
	var value_0 bool = StdUrlGo_Scheme(value) == ""
	var value_1 bool = value_0
	if !value_1 {
		var value_2 bool = StdUrlGo_Host(value) == ""
		value_1 = value_2
	}
	var value_3 bool = value_1
	if !value_3 {
		var value_4 bool = StdUrlGo_Path(value) != ""
		value_3 = value_4
	}
	var value_5 bool = value_3
	if !value_5 {
		var value_6 bool = Middleware_RawQuery(value) != ""
		value_5 = value_6
	}
	var value_7 bool = value_5
	if !value_7 {
		var value_8 bool = Middleware_Fragment(value) != ""
		value_7 = value_8
	}
	var value_9 bool = value_7
	if !value_9 {
		var value_10 *UserInfo = Middleware_User(value)
		value_9 = (value_10 != nil)
	}
	if value_9 {
		return ""
	}
	var value_11 bool = origin == "https://daochi.pages.dev" || origin == "https://daochi.kryonlabs.com" || origin == "https://daochi.net"
	if value_11 || origin == "https://www.daochi.net" || origin == "https://inbe.waozi.xyz" || origin == "https://uku.waozi.xyz" {
		return origin
	}
	var value_12 bool = StdUrlGo_Scheme(value) == "chrome-extension"
	var value_13 bool = value_12
	if value_13 {
		var value_14 bool = Middleware_ValidExtensionID(StdUrlGo_Host(value))
		value_13 = value_14
	}
	if value_13 {
		return origin
	}
	if StdUrlGo_Scheme(value) != "http" {
		return ""
	}
	host := (*url.URL).Hostname(value)
	if host == "localhost" || host == "127.0.0.1" || host == "0.0.0.0" || host == "::1" {
		return origin
	}
	return ""
}

func Middleware_ValidExtensionID(value string) bool {
	if int64(len(value)) != 32 {
		return false
	}
	for it_index := int64(0); it_index < int64(len(value)); it_index++ {
		byte := value[it_index]
		if byte < 97 || byte > 112 {
			return false
		}
	}
	return true
}
