// Code generated by zi2go from monero_deposits.zi. DO NOT EDIT.
package main

import (
	fmt "fmt"
	slog "log/slog"
	url "net/url"
	strings "strings"
)

// #import protocol
// #import std_go_types
// #import std_map_go
// #import std_option
type Monero struct {
	Database          *Database
	Configuration     *Config
	Counters          *ServerMetrics
	Limiter           *RateLimiter
	AddressLocks      *ConcurrentMap
	StuckNotified     *ConcurrentMap
	Verify            VerifySignature
	ReplayError       Error
	Unavailable       Error
	IssuerUnavailable Error
	MissingUser       Error
}

type TransfersResult struct {
	Value []WalletTransfer
	Error Error
}

type ConfirmedTransfers = struct {
	Incoming []WalletTransfer "json:\"in\""
	Pending  []WalletTransfer "json:\"pending\""
}

type PoolTransfers = struct {
	Pool []WalletTransfer "json:\"pool\""
}

type WalletHeight = struct {
	Height int64 "json:\"height\""
}

type __type_79590c567c780445 = map[string]WalletTransfer

type __type_3ed04d94244870e7 struct {
	HasValue bool
	Value    WalletTransfer
}

type __type_d25bb5a1407496f5 struct {
	HasValue bool
	Value    string
}

func MoneroDeposits_AssertMutex(Value Any) *Mutex {
	return Value.(*Mutex)
}

func MoneroDeposits_CollectTransfers(payments __type_79590c567c780445, transfers []WalletTransfer) {
	for _, transfer := range transfers {
		var value_0 string = fmt.Sprintf("%s:%d:%d", transfer.TxID, int(transfer.SubaddrIndex.Major), int(transfer.SubaddrIndex.Minor))
		key := value_0
		var value_1 __type_79590c567c780445 = payments
		var value_2 string = key
		var value_3 __type_3ed04d94244870e7 = __type_3ed04d94244870e7{}
		value_3.Value, value_3.HasValue = value_1[value_2]
		previous := value_3
		if !previous.HasValue || transfer.Confirmations >= previous.Value.Confirmations {
			var value_4 *__type_79590c567c780445 = &(payments)
			var value_5 string = key
			var value_6 WalletTransfer = transfer
			if (*value_4) == nil {
				(*value_4) = make(__type_79590c567c780445)
			}
			(*value_4)[value_5] = value_6
		}
	}
}

func MoneroDeposits_Address(monero Monero, writer ResponseWriter, request *Request) {
	var value_0 bool = !monero.Configuration.TokenDirectPurchasesEnabled
	var value_1 bool = value_0
	if !value_1 {
		var value_2 bool = MoneroWallet_ValidRate(*(monero.Configuration))
		value_1 = !value_2
	}
	var value_3 bool = value_1
	var value_4 bool = value_3
	if !value_4 {
		var value_5 bool = strings.TrimSpace(monero.Configuration.MoneroWalletRPCURL) == ""
		value_4 = value_5
	}
	if value_4 {
		Response_Error(writer, int(503), "monero purchases disabled")
		return
	}
	var parts [2]string
	parts[0] = "monero-address:"
	var value_6 string = ClientAddress_FromRequest(request)
	parts[1] = value_6
	var value_7 *RateLimiter = monero.Limiter
	var value_8 bool = RateLimit_Allow(value_7, strings.Join(parts[0:2:2], ""), int(60), Duration(3600000000000))
	if !value_8 {
		Response_Error(writer, int(429), "too many address requests")
		return
	}
	path := StdUrlGo_Path(StdHttpGo_RequestURL(request))
	reference := strings.TrimSpace(strings.TrimPrefix(path, "/api/v1/tokens/purchases/monero/address/"))
	var accountID string = ""
	if path == "/api/v1/tokens/purchases/monero/address" || reference == "" {
		user := HttpAuth_BearerUser(monero.Database, request, monero.Configuration.TokenSecret)
		if user.Authentication.Error != nil || user.Authentication.Status != 0 {
			HttpAuth_Respond(writer, monero.Counters, user.Authentication)
			return
		}
		accountID = user.Value
	} else {
		var value_9 *Database = monero.Database
		var value_10 Context = StdHttpGo_Context(request)
		recipient := AccountLookup_Resolve(value_9, value_10, reference)
		if recipient.Error != nil {
			slog.Error("resolve monero recipient", "error", recipient.Error)
			Response_Error(writer, int(500), "recipient lookup failed")
			return
		}
		if !recipient.Found {
			Response_Error(writer, int(404), "recipient not found")
			return
		}
		accountID = recipient.Value
	}
	var value_11 *ConcurrentMap = monero.AddressLocks
	var value_12 string = accountID
	loaded := StdSyncGo_LoadOrStore(value_11, value_12, new(Mutex))
	lock := MoneroDeposits_AssertMutex(loaded.Value)
	StdSyncGo_Lock(lock)
	var value_13 *Database = monero.Database
	var value_14 Context = StdHttpGo_Context(request)
	allocated := MoneroDepositStore_AccountAddress(value_13, value_14, accountID)
	if allocated.Error == nil && !allocated.Found {
		var value_15 *Database = monero.Database
		var value_16 Context = StdHttpGo_Context(request)
		var value_17 AddressResult = MoneroDepositStore_CreateAccountAddress(value_15, value_16, accountID, *(monero.Configuration), monero.MissingUser, monero.Unavailable)
		allocated = value_17
	}
	StdSyncGo_Unlock(lock)
	if allocated.Error != nil {
		var value_18 string = LogSafety_LogText(accountID)
		slog.Error("allocate monero account address", "account", value_18, "error", allocated.Error)
		Response_Error(writer, int(500), "monero address unavailable")
		return
	}
	network := strings.ToLower(strings.TrimSpace(monero.Configuration.MoneroNetwork))
	if network != "mainnet" && network != "stagenet" && network != "testnet" {
		network = "mainnet"
	}
	var value MoneroAddressResponse = MoneroAddressResponse{}
	value.AccountID = allocated.Value.AccountID
	value.Alias = allocated.Value.Alias
	value.ProfileIcon = allocated.Value.ProfileIcon
	value.AssetID = "waozi:token"
	value.Address = allocated.Value.Address
	parts[0] = "monero:"
	var value_19 string = url.PathEscape(allocated.Value.Address)
	parts[1] = value_19
	var value_20 string = strings.Join(parts[0:2:2], "")
	value.URI = value_20
	value.Network = network
	var value_21 int64 = MoneroWallet_ConfirmationsRequired(*(monero.Configuration))
	value.ConfirmationsRequired = value_21
	var value_22 int64 = MoneroWallet_MinimumAtomicAmount(*(monero.Configuration))
	value.MinimumAtomicAmount = value_22
	value.Rate.AtomicAmount = monero.Configuration.MoneroRateAtomicAmount
	value.Rate.TokenUnits = monero.Configuration.MoneroRateTokenUnits
	Response_JSON(writer, int(200), value)
}

func MoneroDeposits_Deposits(monero Monero, writer ResponseWriter, request *Request) {
	user := HttpAuth_BearerUser(monero.Database, request, monero.Configuration.TokenSecret)
	if user.Authentication.Error != nil || user.Authentication.Status != 0 {
		HttpAuth_Respond(writer, monero.Counters, user.Authentication)
		return
	}
	deposits := MoneroDepositStore_Deposits(monero.Database, StdHttpGo_Context(request), user.Value, int(100))
	if deposits.Error != nil {
		slog.Error("list monero deposits", "account", LogSafety_LogText(user.Value), "error", deposits.Error)
		Response_Error(writer, int(500), "monero deposits unavailable")
		return
	}
	var value MoneroDepositsResponse = MoneroDepositsResponse{}
	value.Deposits = deposits.Value
	Response_JSON(writer, int(200), value)
}

func MoneroDeposits_Transfers(monero Monero, context Context) TransfersResult {
	var result TransfersResult = TransfersResult{}
	bookmark := MoneroDepositStore_ScanHeight(monero.Database, context)
	result.Error = bookmark.Error
	if result.Error != nil {
		return result
	}
	var parameters __type_7d6cc8a85f09fc88 = *new(__type_7d6cc8a85f09fc88)
	var value_0 *__type_7d6cc8a85f09fc88 = &(parameters)
	if (*value_0) == nil {
		(*value_0) = make(__type_7d6cc8a85f09fc88)
	}
	var value_1 *__type_7d6cc8a85f09fc88 = &(parameters)
	var value_2 string = "in"
	var value_3 Any = true
	if (*value_1) == nil {
		(*value_1) = make(__type_7d6cc8a85f09fc88)
	}
	(*value_1)[value_2] = value_3
	var value_4 *__type_7d6cc8a85f09fc88 = &(parameters)
	var value_5 string = "pending"
	var value_6 Any = true
	if (*value_4) == nil {
		(*value_4) = make(__type_7d6cc8a85f09fc88)
	}
	(*value_4)[value_5] = value_6
	var value_7 *__type_7d6cc8a85f09fc88 = &(parameters)
	var value_8 string = "failed"
	var value_9 Any = false
	if (*value_7) == nil {
		(*value_7) = make(__type_7d6cc8a85f09fc88)
	}
	(*value_7)[value_8] = value_9
	var value_10 *__type_7d6cc8a85f09fc88 = &(parameters)
	var value_11 string = "account_index"
	var value_12 Any = int(0)
	if (*value_10) == nil {
		(*value_10) = make(__type_7d6cc8a85f09fc88)
	}
	(*value_10)[value_11] = value_12
	var value_13 *__type_7d6cc8a85f09fc88 = &(parameters)
	var value_14 string = "min_height"
	var value_15 Any = bookmark.Value
	if (*value_13) == nil {
		(*value_13) = make(__type_7d6cc8a85f09fc88)
	}
	(*value_13)[value_14] = value_15
	var confirmed ConfirmedTransfers = ConfirmedTransfers{}
	var value_16 Error = MoneroWallet_Request(context, *(monero.Configuration), "get_transfers", parameters, &(confirmed), monero.Unavailable)
	result.Error = value_16
	if result.Error != nil {
		return result
	}
	var value_17 __type_7d6cc8a85f09fc88 = parameters
	clear(value_17)
	var value_18 *__type_7d6cc8a85f09fc88 = &(parameters)
	var value_19 string = "pool"
	var value_20 Any = true
	if (*value_18) == nil {
		(*value_18) = make(__type_7d6cc8a85f09fc88)
	}
	(*value_18)[value_19] = value_20
	var value_21 *__type_7d6cc8a85f09fc88 = &(parameters)
	var value_22 string = "account_index"
	var value_23 Any = int(0)
	if (*value_21) == nil {
		(*value_21) = make(__type_7d6cc8a85f09fc88)
	}
	(*value_21)[value_22] = value_23
	var pool PoolTransfers = PoolTransfers{}
	var value_24 Error = MoneroWallet_Request(context, *(monero.Configuration), "get_transfers", parameters, &(pool), monero.Unavailable)
	result.Error = value_24
	if result.Error != nil {
		return result
	}
	maximum := bookmark.Value
	var value_25 __type_7d6cc8a85f09fc88 = parameters
	clear(value_25)
	var height WalletHeight = WalletHeight{}
	var value_26 Error = MoneroWallet_Request(context, *(monero.Configuration), "get_height", parameters, &(height), monero.Unavailable)
	heightError := value_26
	if heightError == nil && height.Height > maximum {
		maximum = height.Height
	}
	{
		value_27 := confirmed.Incoming[:]
		if int64(0) < 0 || int64(int64(len(value_27))) < int64(0) || int64(int64(len(value_27))) > int64(len(value_27)) {
			panic("slice range out of bounds")
		}
		loop_view_33 := value_27[0:int64(len(value_27)):int64(len(value_27))]
		loop_count_33 := int64(len(loop_view_33))
		var loop_cursor_33 int64 = 0
		for loop_cursor_33 < loop_count_33 {
			loop_index_33 := loop_cursor_33
			transfer := loop_view_33[loop_index_33]
			if transfer.Height > maximum {
				maximum = transfer.Height
			}
			loop_cursor_33++
		}
	}
	if maximum > bookmark.Value {
		var value_28 Error = MoneroDepositStore_SaveScanHeight(monero.Database, context, maximum)
		result.Error = value_28
		if result.Error != nil {
			return result
		}
	}
	var payments __type_79590c567c780445 = *new(__type_79590c567c780445)
	var value_29 *__type_79590c567c780445 = &(payments)
	if (*value_29) == nil {
		(*value_29) = make(__type_79590c567c780445)
	}
	MoneroDeposits_CollectTransfers(payments, pool.Pool)
	MoneroDeposits_CollectTransfers(payments, confirmed.Incoming)
	MoneroDeposits_CollectTransfers(payments, confirmed.Pending)
	var value_30 __type_79590c567c780445 = payments
	var value_31 int64 = int64(len(value_30))
	transfers := make([]WalletTransfer, int(int(0)), int(int(value_31)))
	{
		var value_32 __type_79590c567c780445 = payments
		var value_33 []string = make([]string, 0, len(value_32))
		for value_34 := range value_32 {
			value_33 = append(value_33, value_34)
		}
		if int64(0) < 0 || int64(int64(len(value_33))) < int64(0) || int64(int64(len(value_33))) > int64(len(value_33)) {
			panic("slice range out of bounds")
		}
		loop_view_50 := value_33[0:int64(len(value_33)):int64(len(value_33))]
		loop_count_50 := int64(len(loop_view_50))
		var loop_cursor_50 int64 = 0
		for loop_cursor_50 < loop_count_50 {
			loop_index_50 := loop_cursor_50
			key := loop_view_50[loop_index_50]
			var value_36 []WalletTransfer = transfers
			var value_37 __type_79590c567c780445 = payments
			var value_38 string = key
			var value_39 WalletTransfer = value_37[value_38]
			transfers = append(value_36, value_39)
			loop_cursor_50++
		}
	}
	result.Value = transfers
	return result
}

func MoneroDeposits_SettleDeposit(monero Monero, context Context, accountID string, transfer WalletTransfer) Error {
	var value_0 TokenUnitsResult = MoneroWallet_TokenUnits(transfer.Amount, monero.Configuration.MoneroRateAtomicAmount, monero.Configuration.MoneroRateTokenUnits)
	conversion := value_0
	status := "confirming"
	if transfer.DoubleSpendSeen {
		status = "double_spend"
	} else {
		var value_1 bool = transfer.Amount < MoneroWallet_MinimumAtomicAmount(*(monero.Configuration))
		if value_1 || conversion.Error != nil || conversion.Value <= 0 {
			status = "below_minimum"
		} else {
			var value_2 bool = transfer.Confirmations >= MoneroWallet_ConfirmationsRequired(*(monero.Configuration))
			if value_2 && !transfer.Locked && transfer.UnlockTime == 0 {
				status = "confirmed"
			}
		}
	}
	var value_3 DepositResult = MoneroDepositStore_UpsertDeposit(monero.Database, context, accountID, transfer, status, *(monero.Configuration))
	deposit := value_3
	if deposit.Error != nil || status != "confirmed" || deposit.Value.Receipt != nil {
		return deposit.Error
	}
	issuer := TokenPolicy_Issuer(*(monero.Configuration), monero.IssuerUnavailable)
	if issuer.Error != nil {
		return issuer.Error
	}
	var value_4 CreditResult = MoneroDepositStore_CreditDeposit(monero.Database, context, issuer.Value, transfer.TxID, transfer.SubaddrIndex.Major, transfer.SubaddrIndex.Minor, monero.IssuerUnavailable)
	credited := value_4
	return credited.Error
}

func MoneroDeposits_Reconcile(monero Monero, context Context) Error {
	var value_0 bool = MoneroWallet_ValidRate(*(monero.Configuration))
	if !value_0 {
		return nil
	}
	owners := MoneroDepositStore_AddressOwners(monero.Database, context)
	if owners.Error != nil {
		return owners.Error
	}
	var value_1 __type_e628f0f93f788fda = owners.Value
	var value_2 int64 = int64(len(value_1))
	if value_2 == 0 {
		return nil
	}
	transfers := MoneroDeposits_Transfers(monero, context)
	if transfers.Error != nil {
		return transfers.Error
	}
	{
		value_3 := transfers.Value[:]
		if int64(0) < 0 || int64(int64(len(value_3))) < int64(0) || int64(int64(len(value_3))) > int64(len(value_3)) {
			panic("slice range out of bounds")
		}
		loop_view_14 := value_3[0:int64(len(value_3)):int64(len(value_3))]
		loop_count_14 := int64(len(loop_view_14))
		var loop_cursor_14 int64 = 0
		for loop_cursor_14 < loop_count_14 {
			loop_index_14 := loop_cursor_14
			transfer := loop_view_14[loop_index_14]
			if transfer.TxID == "" || transfer.Amount <= 0 {
				loop_cursor_14++
				continue
			}
			var indices [2]int
			indices[0] = transfer.SubaddrIndex.Major
			indices[1] = transfer.SubaddrIndex.Minor
			var value_4 __type_e628f0f93f788fda = owners.Value
			var value_5 [2]int = indices
			var value_6 __type_d25bb5a1407496f5 = __type_d25bb5a1407496f5{}
			value_6.Value, value_6.HasValue = value_4[value_5]
			owner := value_6
			if !owner.HasValue {
				loop_cursor_14++
				continue
			}
			settled := MoneroDeposits_SettleDeposit(monero, context, owner.Value, transfer)
			if settled != nil {
				var value_7 string = LogSafety_LogText(owner.Value)
				var value_8 string = LogSafety_LogText(transfer.TxID)
				slog.Warn("monero account deposit settlement failed", "account", value_7, "tx", value_8, "error", settled)
			}
			loop_cursor_14++
		}
	}
	return nil
}
