// Code generated by zi2go from net_go.zi. DO NOT EDIT.
package main

import net "net"

// #import go_types
type IP = net.IP

type HostPort struct {
	Host  string
	Port  string
	Error Error
}

func NetGo_SplitRaw(Address string) HostPort {
	var result HostPort
	result.Host, result.Port, result.Error = net.SplitHostPort(Address)
	return result
}

func NetGo_SplitHostPort(address string) HostPort {
	return NetGo_SplitRaw(address)
}

func NetGo_ParseIP(address string) IP {
	return net.ParseIP(address)
}

func NetGo_ValidIP(value IP) bool {
	return len(value) != 0
}

func NetGo_FormatIP(value IP) string {
	return (net.IP).String(value)
}

func NetGo_IsLoopback(value IP) bool {
	return (net.IP).IsLoopback(value)
}
