// Code generated by zi2go from node_auth.zi. DO NOT EDIT.
package main

import (
	hex "encoding/hex"
	strconv "strconv"
	strings "strings"
)

// #import std_go_types
type ParsedTimestamp struct {
	Value int64
	Error Error
}

func NodeAuth_ParseInteger(Value string, Base int, Bits int) ParsedTimestamp {
	var result ParsedTimestamp
	result.Value, result.Error = strconv.ParseInt(Value, Base, Bits)
	return result
}

const NodeRequestContext = "daochi-node-request-v1"
const NodeAuthenticationWindowSeconds = 300

func NodeAuth_RandomHex(count int) string {
	bytes := make([]uint8, int(count))
	filled := StdRandomGo_Fill(bytes)
	if filled.Error != nil {
		panic(filled.Error)
	}
	return hex.EncodeToString(bytes)
}

func NodeAuth_Sign(nodeID string, key PrivateKey, request *Request, body []uint8) {
	timestamp := strconv.FormatInt(int64(StdTimeGo_Unix(StdTimeGo_Now())), int(int(10)))
	nonce := NodeAuth_RandomHex(int(16))
	message := Signing_NodeRequestMessage("daochi-node-request-v1", nodeID, timestamp, nonce, StdHttpGo_Method(request), StdUrlGo_EscapedPath(StdHttpGo_RequestURL(request)), body)
	signature := StdEd25519Go_Sign(key, StdTextGo_ToBytes(message))
	var value_0 string = StdTextGo_FromBytes(signature)
	encoded := Codec_EncodeBase64(value_0, true, false)
	header := StdHttpGo_Headers(request)
	StdHttpGo_SetHeader(header, "X-Daochi-Node-ID", nodeID)
	StdHttpGo_SetHeader(header, "X-Daochi-Node-Time", timestamp)
	StdHttpGo_SetHeader(header, "X-Daochi-Node-Nonce", nonce)
	StdHttpGo_SetHeader(header, "X-Daochi-Node-Signature", encoded.Value)
}

func NodeAuth_Verify(database *Database, context Context, request *Request, body []uint8) Error {
	header := StdHttpGo_Headers(request)
	nodeID := strings.TrimSpace(StdHttpGo_HeaderValue(header, "X-Daochi-Node-ID"))
	timestampText := strings.TrimSpace(StdHttpGo_HeaderValue(header, "X-Daochi-Node-Time"))
	nonce := strings.TrimSpace(StdHttpGo_HeaderValue(header, "X-Daochi-Node-Nonce"))
	var value_0 bool = Identity_ValidUserID(nodeID)
	if !value_0 || nonce == "" || int64(len(nonce)) > 128 {
		return StdErrorsGo_New("invalid node authentication")
	}
	timestamp := NodeAuth_ParseInteger(timestampText, int(int(10)), int(int(64)))
	if timestamp.Error != nil {
		return StdErrorsGo_New("invalid node authentication time")
	}
	now := StdTimeGo_Unix(StdTimeGo_Now())
	if timestamp.Value < now-300 || timestamp.Value > now+300 {
		return StdErrorsGo_New("expired node authentication")
	}
	peer := PeerTrust_PublicKey(database, context, nodeID)
	if peer.Error != nil {
		return peer.Error
	}
	if !peer.Found {
		return StdErrorsGo_New("node is not paired")
	}
	var value_1 string = StdHttpGo_HeaderValue(header, "X-Daochi-Node-Signature")
	signature := Codec_DecodeBase64(value_1, true, false)
	if signature.Error != "" || int64(len(signature.Value)) != 64 {
		return StdErrorsGo_New("invalid node signature")
	}
	message := Signing_NodeRequestMessage("daochi-node-request-v1", nodeID, timestampText, nonce, StdHttpGo_Method(request), StdUrlGo_EscapedPath(StdHttpGo_RequestURL(request)), body)
	var value_2 bool = StdEd25519Go_Verify(peer.Value, StdTextGo_ToBytes(message), StdTextGo_ToBytes(signature.Value))
	if !value_2 {
		return StdErrorsGo_New("invalid node signature")
	}
	return NodeNonce_Consume(database, context, nodeID, nonce, timestamp.Value+300)
}
