// Code generated by zi2go from package_release.zi. DO NOT EDIT.
package main

import (
	hex "encoding/hex"
	fmt "fmt"
	strings "strings"
)

// #import std_go_types
type Artifact struct {
	Variant string "json:\"variant\""
	SHA256  string "json:\"sha256\""
	Size    int64  "json:\"size\""
}

type Dependency struct {
	AppID   string "json:\"app_id\""
	Version string "json:\"version\""
	SHA256  string "json:\"sha256\""
	Size    int64  "json:\"size\""
}

type ReleaseV2 struct {
	AppID        string       "json:\"app_id\""
	Sequence     int64        "json:\"sequence\""
	Version      string       "json:\"version\""
	Runtime      string       "json:\"runtime\""
	HostAPI      int64        "json:\"host_api\""
	ModuleAPI    int64        "json:\"module_api\""
	DataSchema   int64        "json:\"data_schema\""
	KeyID        string       "json:\"key_id\""
	Artifacts    []Artifact   "json:\"artifacts\""
	Dependencies []Dependency "json:\"dependencies\""
	Signature    string       "json:\"signature\""
}

type zir_b8622117a5354859_Decoded struct {
	Value []uint8
	Error Error
}

func PackageRelease_Decode(Value string) zir_b8622117a5354859_Decoded {
	var result zir_b8622117a5354859_Decoded
	result.Value, result.Error = hex.DecodeString(Value)
	return result
}

func PackageRelease_VersionValid(value string) bool {
	parts := strings.Split(value, ".")
	if int64(len(parts)) != 3 {
		return false
	}
	{
		if int64(0) < 0 || int64(int64(len(parts))) < int64(0) || int64(int64(len(parts))) > int64(len(parts)) {
			panic("slice range out of bounds")
		}
		loop_view_4 := parts[0:int64(len(parts)):int64(len(parts))]
		loop_count_4 := int64(len(loop_view_4))
		var loop_cursor_4 int64 = 0
		for loop_cursor_4 < loop_count_4 {
			loop_index_4 := loop_cursor_4
			part := loop_view_4[loop_index_4]
			it_index := loop_index_4
			_ = it_index
			if int64(len(part)) == 0 || int64(len(part)) > 9 || (int64(len(part)) > 1 && part[0] == 48) {
				return false
			}
			for it_index := int64(0); it_index < int64(len(part)); it_index++ {
				byte := part[it_index]
				if byte < 48 || byte > 57 {
					return false
				}
			}
			loop_cursor_4++
		}
	}
	return true
}

func PackageRelease_HashValid(value string) bool {
	decoded := PackageRelease_Decode(value)
	var value_0 bool = int64(len(value)) == 64 && decoded.Error == nil && int64(len(decoded.Value)) == 32
	var value_1 bool = value_0
	if value_1 {
		var value_2 bool = hex.EncodeToString(decoded.Value) == value
		value_1 = value_2
	}
	return value_1
}

func PackageRelease_Valid(release ReleaseV2, appID string) bool {
	var value_0 bool = release.AppID != appID
	if !value_0 {
		var value_1 bool = Identity_ValidNamespace(appID)
		value_0 = !value_1
	}
	var value_2 bool = value_0 || release.Sequence <= 0
	if !value_2 {
		var value_3 bool = PackageRelease_VersionValid(release.Version)
		value_2 = !value_3
	}
	var value_4 bool = value_2 || release.Runtime != "kryon-app-v1" || release.HostAPI <= 0 || release.ModuleAPI <= 0 || release.DataSchema < 0
	var value_5 bool = value_4
	if !value_5 {
		var value_6 bool = Identity_ValidNamespace(release.KeyID)
		value_5 = !value_6
	}
	if value_5 || int64(len(release.Artifacts)) < 1 || int64(len(release.Artifacts)) > 2 || int64(len(release.Dependencies)) > 64 {
		return false
	}
	var index int64 = 0
	for index < int64(len(release.Artifacts)) {
		artifact := release.Artifacts[index]
		var value_7 string = ""
		if index == 0 {
			value_7 = "module"
		} else {
			value_7 = "standalone"
		}
		expected := value_7
		var value_8 bool = artifact.Variant != expected || artifact.Size < 8
		if !value_8 {
			var value_9 bool = PackageRelease_HashValid(artifact.SHA256)
			value_8 = !value_9
		}
		if value_8 {
			return false
		}
		index++
	}
	index = 0
	for index < int64(len(release.Dependencies)) {
		dependency := release.Dependencies[index]
		var value_10 bool = Identity_ValidNamespace(dependency.AppID)
		var value_11 bool = !value_10 || dependency.AppID == appID
		if !value_11 {
			var value_12 bool = PackageRelease_VersionValid(dependency.Version)
			value_11 = !value_12
		}
		var value_13 bool = value_11 || dependency.Size < 8
		if !value_13 {
			var value_14 bool = PackageRelease_HashValid(dependency.SHA256)
			value_13 = !value_14
		}
		if value_13 {
			return false
		}
		var value_15 bool = index > 0
		if value_15 {
			var value_16 bool = strings.Compare((release.Dependencies[(index-1)]).AppID, dependency.AppID) >= 0
			value_15 = value_16
		}
		if value_15 {
			return false
		}
		index++
	}
	return true
}

func PackageRelease_SigningMessage(release ReleaseV2) string {
	result := fmt.Sprintf("daochi-zib-release-v2\n%s\n%d\n%s\n%s\n%d\n%d\n%d\n%s\n%d\n", release.AppID, int64(release.Sequence), release.Version, release.Runtime, int64(release.HostAPI), int64(release.ModuleAPI), int64(release.DataSchema), release.KeyID, int64(int64(len(release.Artifacts))))
	{
		value_0 := release.Artifacts[:]
		if int64(0) < 0 || int64(int64(len(value_0))) < int64(0) || int64(int64(len(value_0))) > int64(len(value_0)) {
			panic("slice range out of bounds")
		}
		loop_view_1 := value_0[0:int64(len(value_0)):int64(len(value_0))]
		loop_count_1 := int64(len(loop_view_1))
		var loop_cursor_1 int64 = 0
		for loop_cursor_1 < loop_count_1 {
			loop_index_1 := loop_cursor_1
			artifact := loop_view_1[loop_index_1]
			result = fmt.Sprintf("%s%s\n%s\n%d\n", result, artifact.Variant, artifact.SHA256, int64(artifact.Size))
			loop_cursor_1++
		}
	}
	result = fmt.Sprintf("%s%d\n", result, int64(int64(len(release.Dependencies))))
	{
		value_1 := release.Dependencies[:]
		if int64(0) < 0 || int64(int64(len(value_1))) < int64(0) || int64(int64(len(value_1))) > int64(len(value_1)) {
			panic("slice range out of bounds")
		}
		loop_view_5 := value_1[0:int64(len(value_1)):int64(len(value_1))]
		loop_count_5 := int64(len(loop_view_5))
		var loop_cursor_5 int64 = 0
		for loop_cursor_5 < loop_count_5 {
			loop_index_5 := loop_cursor_5
			dependency := loop_view_5[loop_index_5]
			result = fmt.Sprintf("%s%s\n%s\n%s\n%d\n", result, dependency.AppID, dependency.Version, dependency.SHA256, int64(dependency.Size))
			loop_cursor_5++
		}
	}
	return result
}

func PackageRelease_ContainsArtifact(release ReleaseV2, hash string) bool {
	{
		value_0 := release.Artifacts[:]
		if int64(0) < 0 || int64(int64(len(value_0))) < int64(0) || int64(int64(len(value_0))) > int64(len(value_0)) {
			panic("slice range out of bounds")
		}
		loop_view_0 := value_0[0:int64(len(value_0)):int64(len(value_0))]
		loop_count_0 := int64(len(loop_view_0))
		var loop_cursor_0 int64 = 0
		for loop_cursor_0 < loop_count_0 {
			loop_index_0 := loop_cursor_0
			artifact := loop_view_0[loop_index_0]
			if artifact.SHA256 == hash {
				return true
			}
			loop_cursor_0++
		}
	}
	return false
}
