// Code generated by zi2go from package_http.zi. DO NOT EDIT.
package main

import (
	hex "encoding/hex"
	fmt "fmt"
	http "net/http"
	strings "strings"
)

// #import std_go_types
type zir_c2c2166dca1099f2_Decoded struct {
	Value []uint8
	Error Error
}

type zir_36836ada4d48137e_WriteResult struct {
	Count int
	Error Error
}

func PackageHttp_Decode(Value string) zir_c2c2166dca1099f2_Decoded {
	var result zir_c2c2166dca1099f2_Decoded
	result.Value, result.Error = hex.DecodeString(Value)
	return result
}

func PackageHttp_Write(Writer ResponseWriter, Bytes []uint8) zir_36836ada4d48137e_WriteResult {
	var result zir_36836ada4d48137e_WriteResult
	result.Count, result.Error = (http.ResponseWriter).Write(Writer, Bytes)
	return result
}

func PackageHttp_Route(context Registry, writer ResponseWriter, request *Request) {
	path := strings.TrimPrefix(StdUrlGo_Path(StdHttpGo_RequestURL(request)), "/api/v2/packages/")
	parts := strings.Split(path, "/")
	var value_0 bool = int64(len(parts)) != 2
	if !value_0 {
		var value_1 bool = Identity_ValidNamespace(parts[0])
		value_0 = !value_1
	}
	if value_0 {
		Response_Error(writer, 404, "package not found")
		return
	}
	appID := parts[0]
	app := AppStore_ByID(context.Database, StdHttpGo_Context(request), appID)
	if app.Error != nil {
		Response_Error(writer, 500, "package registry unavailable")
		return
	}
	var value_2 bool = !app.Found || app.Value.Status != "active"
	if !value_2 {
		var value_3 bool = app.Value.ManifestExpiresAt > 0
		if value_3 {
			var value_4 bool = app.Value.ManifestExpiresAt <= StdTimeGo_Unix(StdTimeGo_Now())
			value_3 = value_4
		}
		value_2 = value_3
	}
	if value_2 {
		Response_Error(writer, 404, "package not found")
		return
	}
	root := fmt.Sprint(fmt.Sprint(context.Configuration.DBPath, ".packages/"), fmt.Sprint(appID, "/"))
	filename := "latest-v2.json"
	hash := ""
	if parts[1] != "latest" {
		hash = strings.TrimSuffix(parts[1], ".zib")
		var value_5 string = parts[1]
		var value_6 bool = value_5 != fmt.Sprint(hash, ".zib")
		var value_7 bool = value_6
		var value_8 bool = value_7
		if !value_8 {
			var value_9 bool = PackageRelease_HashValid(hash)
			value_8 = !value_9
		}
		if value_8 {
			Response_Error(writer, 404, "package not found")
			return
		}
		filename = fmt.Sprint(parts[1], ".release-v2.json")
	}
	metadata := StdFileGo_ReadFile(fmt.Sprint(root, filename))
	if metadata.Error != nil {
		Response_Error(writer, 404, "portable release unavailable")
		return
	}
	var value ReleaseV2 = ReleaseV2{}
	var value_10 bool = int64(len(metadata.Value)) > 65536
	if !value_10 {
		var value_11 Error = StdJsonGo_Unmarshal(metadata.Value, &(value))
		value_10 = (value_11 != nil)
	}
	var value_12 bool = value_10
	var value_13 bool = value_12
	if !value_13 {
		var value_14 bool = PackageRelease_Valid(value, appID)
		value_13 = !value_14
	}
	if value_13 {
		Response_Error(writer, 503, "invalid portable release")
		return
	}
	var value_15 Context = StdHttpGo_Context(request)
	key := AppStore_ActiveKey(context.Database, value_15, appID, value.KeyID)
	public := PackageHttp_Decode(key.Value.PublicKey)
	signature := PackageHttp_Decode(value.Signature)
	var value_16 bool = key.Error != nil || !key.Found || key.Value.Algorithm != "ed25519"
	var value_17 bool = value_16
	if !value_17 {
		var value_18 bool = key.Value.ExpiresAt > 0
		if value_18 {
			var value_19 bool = key.Value.ExpiresAt <= StdTimeGo_Unix(StdTimeGo_Now())
			value_18 = value_19
		}
		value_17 = value_18
	}
	var value_20 bool = value_17 || public.Error != nil || int64(len(public.Value)) != 32 || signature.Error != nil || int64(len(signature.Value)) != 64
	var value_21 bool = value_20
	var value_22 bool = value_21
	if !value_22 {
		var value_23 bool = StdEd25519Go_Verify(PublicKey(public.Value), StdTextGo_ToBytes(PackageRelease_SigningMessage(value)), signature.Value)
		value_22 = !value_23
	}
	if value_22 {
		Response_Error(writer, 503, "untrusted portable release")
		return
	}
	if parts[1] == "latest" {
		StdHttpGo_SetHeader(StdHttpGo_ResponseHeaders(writer), "Cache-Control", "no-store")
		Response_JSON(writer, 200, value)
		return
	}
	var expected int64 = 0
	{
		value_24 := value.Artifacts[:]
		if int64(0) < 0 || int64(int64(len(value_24))) < int64(0) || int64(int64(len(value_24))) > int64(len(value_24)) {
			panic("slice range out of bounds")
		}
		loop_view_50 := value_24[0:int64(len(value_24)):int64(len(value_24))]
		loop_count_50 := int64(len(loop_view_50))
		var loop_cursor_50 int64 = 0
		for loop_cursor_50 < loop_count_50 {
			loop_index_50 := loop_cursor_50
			artifact := loop_view_50[loop_index_50]
			if artifact.SHA256 == hash {
				expected = artifact.Size
			}
			loop_cursor_50++
		}
	}
	if expected == 0 {
		Response_Error(writer, 404, "package not found")
		return
	}
	bundle := StdFileGo_ReadFile(fmt.Sprint(root, parts[1]))
	var value_25 bool = bundle.Error != nil || int64(len(bundle.Value)) != expected
	var value_26 bool = value_25
	if !value_26 {
		var value_27 bool = Signing_SHA256Hex(bundle.Value) != hash
		value_26 = value_27
	}
	if value_26 {
		Response_Error(writer, 503, "portable release bytes do not match")
		return
	}
	StdHttpGo_SetHeader(StdHttpGo_ResponseHeaders(writer), "Content-Type", "application/octet-stream")
	StdHttpGo_SetHeader(StdHttpGo_ResponseHeaders(writer), "Cache-Control", "public, max-age=31536000, immutable")
	StdHttpGo_SetHeader(StdHttpGo_ResponseHeaders(writer), "ETag", fmt.Sprint("\"", fmt.Sprint(hash, "\"")))
	PackageHttp_Write(writer, bundle.Value)
}
