// Code generated by zi2go from peer_trust.zi. DO NOT EDIT.
package main

import sql "database/sql"

// #import std_go_types
type PeerKeyResult struct {
	Value PublicKey
	Found bool
	Error Error
}

func PeerTrust_PublicKey(database *Database, context Context, nodeID string) PeerKeyResult {
	var result PeerKeyResult = PeerKeyResult{}
	var key []uint8 = nil
	row := (*sql.DB).QueryRowContext(database, context, "SELECT public_key FROM trusted_node_peers WHERE node_id=?1 AND revoked_at=''", nodeID)
	error := (*sql.Row).Scan(row, &(key))
	if StdErrorsGo_Is(error, StdSqlGo_NoRows()) {
		return result
	}
	if error != nil {
		result.Error = error
		return result
	}
	if int64(len(key)) != 32 {
		result.Error = StdErrorsGo_New("stored peer key is invalid")
		return result
	}
	result.Value = PublicKey(key)
	result.Found = true
	return result
}
