// Code generated by zi2go from rate_limit_test.zi. DO NOT EDIT.
package main

import (
	http "net/http"
	httptest "net/http/httptest"
	testing "testing"
)

// #import std_go_types
type AddressCase struct {
	Name      string
	Remote    string
	Forwarded string
	Want      string
}

type CapturedAddressCase func(AddressCase, *Test)

func RateLimitTest_SetRemoteRaw(Request *Request, Value string) {
	Request.RemoteAddr = Value
}

func RateLimitTest_HeaderRaw(Request *Request) Header {
	return Request.Header
}

func RateLimitTest_CaptureCaseRaw(Callback CapturedAddressCase, Value AddressCase) TestCase {
	return func(argument0 *Test) {
		Callback(Value, argument0)
	}
}

func RateLimitTest_CheckAddress(value AddressCase, test *Test) {
	var body Reader = *new(Reader)
	request := httptest.NewRequest("GET", "/healthz", body)
	RateLimitTest_SetRemoteRaw(request, value.Remote)
	if value.Forwarded != "" {
		(http.Header).Set(RateLimitTest_HeaderRaw(request), "X-Forwarded-For", value.Forwarded)
	}
	got := ClientAddress_FromRequest(request)
	if got != value.Want {
		var value_0 [4]Any
		value_0[0] = value.Remote
		value_0[1] = value.Forwarded
		value_0[2] = got
		value_0[3] = value.Want
		arguments := value_0
		_ = arguments
		TestingTest_Fatalf(test, "ClientAddress_FromRequest(%q, %q) = %q, want %q", arguments[0:4:4])
	}
}

func RateLimitTest_ClientAddressForwardedForTrust(test *Test) {
	var value_0 [7]AddressCase
	var value_1 AddressCase = AddressCase{Name: "loopback trusts proxy header", Remote: "127.0.0.1:8080", Forwarded: "203.0.113.9", Want: "203.0.113.9"}
	value_0[0] = value_1
	var value_2 AddressCase = AddressCase{Name: "loopback uses first hop only", Remote: "127.0.0.1:8080", Forwarded: "203.0.113.9, 198.51.100.7", Want: "203.0.113.9"}
	value_0[1] = value_2
	var value_3 AddressCase = AddressCase{Name: "loopback ignores garbage header", Remote: "127.0.0.1:8080", Forwarded: "not-an-ip", Want: "127.0.0.1"}
	value_0[2] = value_3
	value_0[3] = AddressCase{Name: "loopback without header", Remote: "[::1]:9000", Forwarded: "", Want: "::1"}
	var value_4 AddressCase = AddressCase{Name: "remote peer ignores header", Remote: "203.0.113.50:5555", Forwarded: "198.51.100.7", Want: "203.0.113.50"}
	value_0[4] = value_4
	value_0[5] = AddressCase{Name: "no port", Remote: "203.0.113.50", Forwarded: "", Want: "203.0.113.50"}
	value_0[6] = AddressCase{Name: "empty address", Remote: "", Forwarded: "", Want: "unknown"}
	cases := value_0
	_ = cases
	{
		value_5 := cases[0:7:7][:]
		if int64(0) < 0 || int64(int64(len(value_5))) < int64(0) || int64(int64(len(value_5))) > int64(len(value_5)) {
			panic("slice range out of bounds")
		}
		loop_view_1 := value_5[0:int64(len(value_5)):int64(len(value_5))]
		loop_count_1 := int64(len(loop_view_1))
		var loop_cursor_1 int64 = 0
		for loop_cursor_1 < loop_count_1 {
			loop_index_1 := loop_cursor_1
			value := loop_view_1[loop_index_1]
			var value_6 *Test = test
			var value_7 string = value.Name
			var value_10 CapturedAddressCase = func(value_8 AddressCase, value_9 *Test) { RateLimitTest_CheckAddress(value_8, value_9) }
			TestingTest_Run(value_6, value_7, RateLimitTest_CaptureCaseRaw(value_10, value))
			loop_cursor_1++
		}
	}
}

func TestClientAddressForwardedForTrust(export_arg_0 *testing.T) {
	RateLimitTest_ClientAddressForwardedForTrust(export_arg_0)
}

func RateLimitTest_RateLimiterWindow(test *Test) {
	limiter := RateLimit_New()
	hour := Duration(3600000000000)
	for index := int64(0); index <= 2; index++ {
		var value_0 bool = RateLimit_Allow(limiter, "bucket", 3, hour)
		if !value_0 {
			var value_1 [1]Any
			value_1[0] = index + 1
			arguments := value_1
			_ = arguments
			TestingTest_Fatalf(test, "request %d denied inside limit", arguments[0:1:1])
		}
	}
	if RateLimit_Allow(limiter, "bucket", 3, hour) {
		TestingTest_Fatal(test, "4th request allowed past limit")
	}
	var value_2 bool = RateLimit_Allow(limiter, "other-bucket", 3, hour)
	if !value_2 {
		TestingTest_Fatal(test, "unrelated bucket denied")
	}
	var value_3 bool = RateLimit_Allow(limiter, "", 3, hour)
	var value_4 bool = !value_3
	if !value_4 {
		var value_5 bool = RateLimit_Allow(limiter, "bucket", 0, hour)
		value_4 = !value_5
	}
	if value_4 {
		TestingTest_Fatal(test, "degenerate parameters should bypass limiting")
	}
}

func TestRateLimiterWindow(export_arg_0 *testing.T) {
	RateLimitTest_RateLimiterWindow(export_arg_0)
}
