// Code generated by zi2go from rate_limit.zi. DO NOT EDIT.
package main

// #import std_map_go
// #import std_sync_go
type RateWindow struct {
	ResetAt Time
	Count   int
}

type __type_3055c5f47fd94de8 = map[string]RateWindow

type RateLimiter struct {
	Mu      Mutex
	Windows __type_3055c5f47fd94de8
}

func RateLimit_Prune(limiter *RateLimiter, now Time) {
	var value_0 __type_3055c5f47fd94de8 = limiter.Windows
	var value_1 []string = make([]string, 0, len(value_0))
	for value_2 := range value_0 {
		value_1 = append(value_1, value_2)
	}
	keys := value_1
	for _, key := range keys {
		var value_3 __type_3055c5f47fd94de8 = limiter.Windows
		var value_4 string = key
		var value_5 RateWindow = value_3[value_4]
		item := value_5
		if StdTimeGo_After(now, item.ResetAt) {
			var value_6 __type_3055c5f47fd94de8 = limiter.Windows
			var value_7 string = key
			delete(value_6, value_7)
		}
	}
}

func RateLimit_Record(limiter *RateLimiter, key string, limit int, window Duration, now Time) bool {
	StdSyncGo_Lock(&(limiter.Mu))
	var value_0 __type_3055c5f47fd94de8 = limiter.Windows
	var value_1 string = key
	var value_2 RateWindow = value_0[value_1]
	item := value_2
	if StdTimeGo_After(now, item.ResetAt) {
		var value_3 Time = StdTimeGo_Add(now, window)
		item.ResetAt = value_3
		item.Count = 0
	}
	item.Count++
	var value_4 *__type_3055c5f47fd94de8 = &(limiter.Windows)
	var value_5 string = key
	var value_6 RateWindow = item
	if (*value_4) == nil {
		(*value_4) = make(__type_3055c5f47fd94de8)
	}
	(*value_4)[value_5] = value_6
	var value_7 __type_3055c5f47fd94de8 = limiter.Windows
	var value_8 int64 = int64(len(value_7))
	if value_8 > 8192 {
		RateLimit_Prune(limiter, now)
	}
	cleanup_return_0 := item.Count <= limit
	StdSyncGo_Unlock(&(limiter.Mu))
	return cleanup_return_0
}

func RateLimit_New() *RateLimiter {
	limiter := new(RateLimiter)
	var value_0 *__type_3055c5f47fd94de8 = &(limiter.Windows)
	if (*value_0) == nil {
		(*value_0) = make(__type_3055c5f47fd94de8)
	}
	return limiter
}

func RateLimit_Allow(limiter *RateLimiter, key string, limit int, window Duration) bool {
	if key == "" || limit <= 0 || int64(window) <= 0 {
		return true
	}
	return RateLimit_Record(limiter, key, limit, window, StdTimeGo_Now())
}
