// Code generated by zi2go from request_rate.zi. DO NOT EDIT.
package main

func RequestRate_Allow(limiter *RateLimiter, counters *ServerMetrics, key string, limit int, window Duration) bool {
	if limiter == nil {
		return true
	}
	allowed := RateLimit_Allow(limiter, key, limit, window)
	if !allowed {
		StdAtomicGo_Add(&(counters.RateLimitedRequests), 1)
	}
	return allowed
}
