// Code generated by zi2go from response.zi. DO NOT EDIT.
package main

// #import std_go_types
type ErrorResponse struct {
	Message string "json:\"error\""
}

func Response_JSON(writer ResponseWriter, status int, value Any) {
	StdHttpGo_SetHeader(StdHttpGo_ResponseHeaders(writer), "Content-Type", "application/json")
	StdHttpGo_WriteHeader(writer, status)
	StdJsonGo_Encode(StdJsonGo_NewEncoder(Writer(writer)), value)
}

func Response_Error(writer ResponseWriter, status int, message string) {
	var value ErrorResponse = ErrorResponse{}
	value.Message = message
	Response_JSON(writer, status, value)
}
