// Code generated by zi2go from server.zi. DO NOT EDIT.
package main

import http "net/http"

// #import std_go_types
type Server struct {
	Cfg                 Config
	Store               *Store
	Challenges          *ChallengeStore
	Verifier            *Verifier
	SyncHub             *SyncHub
	Limiter             *RateLimiter
	Metrics             *ServerMetrics
	Node                NodeIdentity
	MoneroAddressLocks  ConcurrentMap
	MoneroStuckNotified ConcurrentMap
	Signer              SignPrivateKey
}

type Mux = http.ServeMux

type HTTPCallback func(ResponseWriter, *Request)

type ServerHandler func(*Server, ResponseWriter, *Request)

type ServerVerifier func(*Server, []uint8, []uint8, []uint8) bool

type ServerStats func(*Server, Context, string) PublicStatsResult

type zir_cc7033b09d2a8784_Results__string__Error struct {
	Value0 string
	Value1 Error
}

type Results__string__bool struct {
	Value0 string
	Value1 bool
}

type Results__a_u8__Error struct {
	Value0 []uint8
	Value1 Error
}

type Results__protocol_NodeUsage__Error struct {
	Value0 NodeUsage
	Value1 Error
}

func Server_BindHandler(Callback ServerHandler, Server *Server) HTTPCallback {
	return func(argument0 ResponseWriter, argument1 *Request) {
		Callback(Server, argument0, argument1)
	}
}

func Server_BindVerifier(Callback ServerVerifier, Server *Server) VerifySignature {
	return func(argument0 []uint8, argument1 []uint8, argument2 []uint8) bool {
		return Callback(Server, argument0, argument1, argument2)
	}
}

func Server_BindStats(Callback ServerStats, Server *Server) ReadPublicStats {
	return func(argument0 Context, argument1 string) PublicStatsResult {
		return Callback(Server, argument0, argument1)
	}
}

func Server_RetainPath(Value string) string {
	return Value
}

func Server_RetainIdentity(Value NodeIdentity) NodeIdentity {
	return Value
}

const daochiSignatureContext = "daochi-sync-v1"
const legacySyncSignatureContext = "ksync-sync-v1"
const legacyInbeSignatureContext = "inbe-sync-v1"

var errSignedTxReplay Error
var errAppScopeNotOwned Error

func Server_Verify(server *Server, publicKey []uint8, message []uint8, signature []uint8) bool {
	var value_0 VerifySignature = server.Verifier.Verify
	return value_0(publicKey, message, signature)
}

func Server_PublicStats(server *Server, context Context, databasePath string) PublicStatsResult {
	results_1_ := Store_PublicStats(server.Store, context, databasePath)
	value := results_1_.Value0
	error := results_1_.Value1
	var result PublicStatsResult = PublicStatsResult{}
	result.Value = value
	result.Error = error
	return result
}

func Server_Route(mux *Mux, pattern string, server *Server, handler ServerHandler) {
	(*http.ServeMux).HandleFunc(mux, pattern, Server_BindHandler(handler, server))
}

func Server_New(configuration Config, store *Store, verifier *Verifier, signer SignPrivateKey) *Server {
	identity := NodeIdentity_New(configuration.NodeIdentityPrivateKey)
	if identity.Error != nil {
		panic(identity.Error)
	}
	server := new(Server)
	server.Cfg = configuration
	server.Store = store
	var value_0 *ChallengeStore = Challenge_New(configuration.ChallengeTTL)
	server.Challenges = value_0
	server.Verifier = verifier
	var value_1 *SyncHub = SyncHub_New()
	server.SyncHub = value_1
	var value_2 *RateLimiter = RateLimit_New()
	server.Limiter = value_2
	var value_3 *ServerMetrics = new(ServerMetrics)
	server.Metrics = value_3
	server.Node = identity.Value
	server.Signer = signer
	return server
}

func Server_Access(server *Server) AccountAccess {
	var result AccountAccess = AccountAccess{}
	result.Database = server.Store.Database
	result.Configuration = &(server.Cfg)
	result.Challenges = server.Challenges
	result.Limiter = server.Limiter
	result.Counters = server.Metrics
	var value_4 ServerVerifier = func(value_0 *Server, value_1 []uint8, value_2 []uint8, value_3 []uint8) bool {
		return Server_Verify(value_0, value_1, value_2, value_3)
	}
	var value_5 VerifySignature = Server_BindVerifier(value_4, server)
	result.Verify = value_5
	result.Sign = server.Signer
	return result
}

func (receiver *Server) access() AccountAccess {
	return Server_Access(receiver)
}

func Server_Operations(server *Server) Operations {
	var result Operations = Operations{}
	result.Database = server.Store.Database
	var value_0 string = Server_RetainPath(server.Store.Path)
	result.Path = value_0
	result.Configuration = &(server.Cfg)
	result.Identity = &(server.Node)
	result.Notifications = server.SyncHub
	result.Counters = server.Metrics
	result.VerifierAvailable = server.Verifier != nil
	return result
}

func (receiver *Server) operations() Operations {
	return Server_Operations(receiver)
}

func Server_Tokens(server *Server) Tokens {
	var result Tokens = Tokens{}
	result.Database = server.Store.Database
	result.Configuration = &(server.Cfg)
	result.Counters = server.Metrics
	result.Limiter = server.Limiter
	result.Verify = server.Verifier.Verify
	result.ReplayError = errSignedTxReplay
	result.IssuerUnavailable = errTokenIssuerReadOnly
	return result
}

func (receiver *Server) tokens() Tokens {
	return Server_Tokens(receiver)
}

func Server_Monero(server *Server) Monero {
	var result Monero = Monero{}
	result.Database = server.Store.Database
	result.Configuration = &(server.Cfg)
	result.Counters = server.Metrics
	result.Limiter = server.Limiter
	result.AddressLocks = &(server.MoneroAddressLocks)
	result.StuckNotified = &(server.MoneroStuckNotified)
	result.Verify = server.Verifier.Verify
	result.ReplayError = errSignedTxReplay
	result.Unavailable = errPaymentUnavailable
	result.IssuerUnavailable = errTokenIssuerReadOnly
	result.MissingUser = ErrSyncUserNotFound
	return result
}

func (receiver *Server) monero() Monero {
	return Server_Monero(receiver)
}

func Server_Accounts(server *Server) Accounts {
	var result Accounts = Accounts{}
	result.Database = server.Store.Database
	result.Configuration = &(server.Cfg)
	result.Counters = server.Metrics
	result.MissingUser = ErrSyncUserNotFound
	return result
}

func (receiver *Server) accounts() Accounts {
	return Server_Accounts(receiver)
}

func Server_Social(server *Server) Social {
	var result Social = Social{}
	result.Accounts = Server_Accounts(server)
	result.Notifications = server.SyncHub
	return result
}

func (receiver *Server) social() Social {
	return Server_Social(receiver)
}

func Server_AppRegistry(server *Server) Registry {
	var result Registry = Registry{}
	result.Database = server.Store.Database
	result.Configuration = &(server.Cfg)
	result.Counters = server.Metrics
	result.Verify = server.Verifier.Verify
	result.ReplayError = errSignedTxReplay
	result.MissingUser = ErrSyncUserNotFound
	result.ScopeNotOwned = errAppScopeNotOwned
	return result
}

func (receiver *Server) appRegistry() Registry {
	return Server_AppRegistry(receiver)
}

func Server_Devices(server *Server) Devices {
	var result Devices = Devices{}
	result.Database = server.Store.Database
	result.Configuration = &(server.Cfg)
	result.Counters = server.Metrics
	result.Verify = server.Verifier.Verify
	result.ReplayError = errSignedTxReplay
	return result
}

func (receiver *Server) devices() Devices {
	return Server_Devices(receiver)
}

func Server_Trust(server *Server) Trust {
	var result Trust = Trust{}
	result.Database = server.Store.Database
	result.Configuration = &(server.Cfg)
	var value_0 NodeIdentity = Server_RetainIdentity(server.Node)
	result.Identity = value_0
	return result
}

func (receiver *Server) trust() Trust {
	return Server_Trust(receiver)
}

func Server_Mesh(server *Server) Mesh {
	var result Mesh = Mesh{}
	result.Database = server.Store.Database
	result.Configuration = &(server.Cfg)
	result.Identity = &(server.Node)
	var value_1 ConvertError = func(value_0 AuthenticationResult) Error { return AuthenticationError_Convert(value_0) }
	result.ConvertError = value_1
	return result
}

func (receiver *Server) mesh() Mesh {
	return Server_Mesh(receiver)
}

func Server_AuthenticateToken(server *Server, request *Request) zir_cc7033b09d2a8784_Results__string__Error {
	result := HttpAuth_AuthenticateToken(server.Store.Database, request, server.Cfg.TokenSecret)
	var value_2 zir_cc7033b09d2a8784_Results__string__Error = zir_cc7033b09d2a8784_Results__string__Error{}
	value_2.Value0 = result.Value
	var value_3 Error = AuthenticationError_Convert(result.Authentication)
	value_2.Value1 = value_3
	return value_2
}

func (receiver *Server) authenticateToken(argument1 *Request) (string, Error) {
	result := Server_AuthenticateToken(receiver, argument1)
	return result.Value0, result.Value1
}

func Server_BearerUser(server *Server, writer ResponseWriter, request *Request) Results__string__bool {
	result := HttpAuth_BearerUser(server.Store.Database, request, server.Cfg.TokenSecret)
	if result.Authentication.Error != nil || result.Authentication.Status != 0 {
		HttpAuth_Respond(writer, server.Metrics, result.Authentication)
		return Results__string__bool{Value0: "", Value1: false}
	}
	return Results__string__bool{Value0: result.Value, Value1: true}
}

func (receiver *Server) bearerUser(argument1 ResponseWriter, argument2 *Request) (string, bool) {
	result := Server_BearerUser(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Server_Synchronization(server *Server) Synchronization {
	var result Synchronization = Synchronization{}
	result.Database = server.Store.Database
	result.Configuration = &(server.Cfg)
	result.Counters = server.Metrics
	result.Notifications = server.SyncHub
	var value_4 ServerVerifier = func(value_0 *Server, value_1 []uint8, value_2 []uint8, value_3 []uint8) bool {
		return Server_Verify(value_0, value_1, value_2, value_3)
	}
	var value_5 VerifySignature = Server_BindVerifier(value_4, server)
	result.Verify = value_5
	result.ReplayError = errSignedTxReplay
	result.MissingUser = ErrSyncUserNotFound
	return result
}

func (receiver *Server) synchronization() Synchronization {
	return Server_Synchronization(receiver)
}

func Server_AuthenticateSignature(server *Server, context Context, userID string, publicKey string, signed string, signatureContext string, method string, path string, payload []uint8) Results__a_u8__Error {
	var value_2 *Database = server.Store.Database
	var value_3 *ChallengeStore = server.Challenges
	var value_4 AccountAccess = Server_Access(server)
	result := AccountSignature_Authenticate(value_2, value_3, value_4.Verify, context, userID, publicKey, signed, signatureContext, method, path, payload)
	var value_5 Results__a_u8__Error = Results__a_u8__Error{}
	value_5.Value0 = result.Value
	var value_6 Error = AuthenticationError_Convert(result.Authentication)
	value_5.Value1 = value_6
	return value_5
}

func (receiver *Server) authenticateSignature(argument1 Context, argument2 string, argument3 string, argument4 string, argument5 string, argument6 string, argument7 string, argument8 []uint8) ([]uint8, Error) {
	result := Server_AuthenticateSignature(receiver, argument1, argument2, argument3, argument4, argument5, argument6, argument7, argument8)
	return result.Value0, result.Value1
}

func Server_WithCommonHeaders(server *Server, next Handler) Handler {
	return Middleware_New(&(server.Metrics), next)
}

func (receiver *Server) withCommonHeaders(argument1 Handler) Handler {
	return Server_WithCommonHeaders(receiver, argument1)
}

func Server_AllowRequest(server *Server, request *Request, key string, limit int, window Duration) bool {
	return RequestRate_Allow(server.Limiter, server.Metrics, key, limit, window)
}

func (receiver *Server) allowRequest(argument1 *Request, argument2 string, argument3 int, argument4 Duration) bool {
	return Server_AllowRequest(receiver, argument1, argument2, argument3, argument4)
}

func Server_SyncSocket(server *Server) SyncSocket {
	var result SyncSocket = SyncSocket{}
	result.Database = server.Store.Database
	result.Configuration = &(server.Cfg)
	result.Counters = server.Metrics
	result.Limiter = server.Limiter
	result.Hub = server.SyncHub
	return result
}

func (receiver *Server) syncSocket() SyncSocket {
	return Server_SyncSocket(receiver)
}

func Server_NodeUsage(server *Server, context Context) Results__protocol_NodeUsage__Error {
	result := OperationalHttp_Usage(Server_Operations(server), context)
	return Results__protocol_NodeUsage__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Server) nodeUsage(argument1 Context) (NodeUsage, Error) {
	result := Server_NodeUsage(receiver, argument1)
	return result.Value0, result.Value1
}

func Server_Routes(server *Server) Handler {
	mux := http.NewServeMux()
	Server_Route(mux, "GET /", server, func(value_0 *Server, value_1 ResponseWriter, value_2 *Request) {
		Server_HandleDocs(value_0, value_1, value_2)
	})
	Server_Route(mux, "GET /openapi.json", server, func(value_3 *Server, value_4 ResponseWriter, value_5 *Request) {
		Server_HandleOpenAPI(value_3, value_4, value_5)
	})
	Server_Route(mux, "GET /healthz", server, func(value_6 *Server, value_7 ResponseWriter, value_8 *Request) {
		Server_HandleHealth(value_6, value_7, value_8)
	})
	Server_Route(mux, "GET /readyz", server, func(value_9 *Server, value_10 ResponseWriter, value_11 *Request) {
		Server_HandleReady(value_9, value_10, value_11)
	})
	Server_Route(mux, "GET /api/v1/node", server, func(value_12 *Server, value_13 ResponseWriter, value_14 *Request) {
		Server_HandleNodeInfo(value_12, value_13, value_14)
	})
	var value_18 ServerHandler = func(value_15 *Server, value_16 ResponseWriter, value_17 *Request) {
		Server_HandleTrustHttpCreateInvite(value_15, value_16, value_17)
	}
	Server_Route(mux, "POST /api/v1/node/pairing/invites", server, value_18)
	var value_22 ServerHandler = func(value_19 *Server, value_20 ResponseWriter, value_21 *Request) {
		Server_HandleTrustHttpAcceptInvite(value_19, value_20, value_21)
	}
	Server_Route(mux, "POST /api/v1/node/pairing/accept", server, value_22)
	var value_26 ServerHandler = func(value_23 *Server, value_24 ResponseWriter, value_25 *Request) {
		Server_HandleTrustHttpCompletePairing(value_23, value_24, value_25)
	}
	Server_Route(mux, "POST /api/v1/node/pairing/complete", server, value_26)
	var value_30 ServerHandler = func(value_27 *Server, value_28 ResponseWriter, value_29 *Request) {
		Server_HandleTrustHttpListPeers(value_27, value_28, value_29)
	}
	Server_Route(mux, "GET /api/v1/node/peers", server, value_30)
	var value_34 ServerHandler = func(value_31 *Server, value_32 ResponseWriter, value_33 *Request) {
		Server_HandleTrustHttpCreateSpace(value_31, value_32, value_33)
	}
	Server_Route(mux, "POST /api/v1/namespaces", server, value_34)
	var value_38 ServerHandler = func(value_35 *Server, value_36 ResponseWriter, value_37 *Request) {
		Server_HandleTrustHttpRegisterName(value_35, value_36, value_37)
	}
	Server_Route(mux, "POST /api/v1/namespaces/claims", server, value_38)
	var value_42 ServerHandler = func(value_39 *Server, value_40 ResponseWriter, value_41 *Request) {
		Server_HandleTrustHttpResolveName(value_39, value_40, value_41)
	}
	Server_Route(mux, "GET /api/v1/namespaces/resolve", server, value_42)
	Server_Route(mux, "POST /api/v1/node/mesh/export", server, func(value_43 *Server, value_44 ResponseWriter, value_45 *Request) {
		Server_HandleMeshExport(value_43, value_44, value_45)
	})
	Server_Route(mux, "POST /api/v1/node/mesh/import", server, func(value_46 *Server, value_47 ResponseWriter, value_48 *Request) {
		Server_HandleMeshImport(value_46, value_47, value_48)
	})
	Server_Route(mux, "GET /metrics", server, func(value_49 *Server, value_50 ResponseWriter, value_51 *Request) {
		Server_HandleMetrics(value_49, value_50, value_51)
	})
	Server_Route(mux, "GET /api/v1/apps", server, func(value_52 *Server, value_53 ResponseWriter, value_54 *Request) {
		Server_HandleAppHttpList(value_52, value_53, value_54)
	})
	Server_Route(mux, "POST /api/v1/apps", server, func(value_55 *Server, value_56 ResponseWriter, value_57 *Request) {
		Server_HandleAppHttpList(value_55, value_56, value_57)
	})
	var value_61 ServerHandler = func(value_58 *Server, value_59 ResponseWriter, value_60 *Request) {
		Server_HandleAppHttpRegisterSigned(value_58, value_59, value_60)
	}
	Server_Route(mux, "POST /api/v1/apps/register-signed", server, value_61)
	Server_Route(mux, "GET /api/v1/apps/", server, func(value_62 *Server, value_63 ResponseWriter, value_64 *Request) {
		Server_HandleAppHttpRoute(value_62, value_63, value_64)
	})
	Server_Route(mux, "PUT /api/v1/apps/", server, func(value_65 *Server, value_66 ResponseWriter, value_67 *Request) {
		Server_HandleAppHttpRoute(value_65, value_66, value_67)
	})
	var value_71 ServerHandler = func(value_68 *Server, value_69 ResponseWriter, value_70 *Request) {
		Server_HandleTokenHttpAssets(value_68, value_69, value_70)
	}
	Server_Route(mux, "GET /api/v1/tokens/assets", server, value_71)
	var value_75 ServerHandler = func(value_72 *Server, value_73 ResponseWriter, value_74 *Request) {
		Server_HandleTokenHttpProducts(value_72, value_73, value_74)
	}
	Server_Route(mux, "GET /api/v1/tokens/products", server, value_75)
	var value_79 ServerHandler = func(value_76 *Server, value_77 ResponseWriter, value_78 *Request) {
		Server_HandleTokenHttpIssuer(value_76, value_77, value_78)
	}
	Server_Route(mux, "GET /api/v1/tokens/issuer", server, value_79)
	var value_83 ServerHandler = func(value_80 *Server, value_81 ResponseWriter, value_82 *Request) {
		Server_HandleTokenHttpBalance(value_80, value_81, value_82)
	}
	Server_Route(mux, "GET /api/v1/tokens/balance", server, value_83)
	var value_87 ServerHandler = func(value_84 *Server, value_85 ResponseWriter, value_86 *Request) {
		Server_HandleTokenHttpLedger(value_84, value_85, value_86)
	}
	Server_Route(mux, "GET /api/v1/tokens/ledger", server, value_87)
	var value_91 ServerHandler = func(value_88 *Server, value_89 ResponseWriter, value_90 *Request) {
		Server_HandleTokenHttpSpend(value_88, value_89, value_90)
	}
	Server_Route(mux, "POST /api/v1/tokens/spend", server, value_91)
	var value_95 ServerHandler = func(value_92 *Server, value_93 ResponseWriter, value_94 *Request) {
		Server_HandleGooglePlayHttpVerify(value_92, value_93, value_94)
	}
	Server_Route(mux, "POST /api/v1/tokens/purchases/google/verify", server, value_95)
	var value_99 ServerHandler = func(value_96 *Server, value_97 ResponseWriter, value_98 *Request) {
		Server_HandleMoneroInvoicesCreate(value_96, value_97, value_98)
	}
	Server_Route(mux, "POST /api/v1/tokens/purchases/monero/invoices", server, value_99)
	var value_103 ServerHandler = func(value_100 *Server, value_101 ResponseWriter, value_102 *Request) {
		Server_HandleMoneroInvoicesRead(value_100, value_101, value_102)
	}
	Server_Route(mux, "GET /api/v1/tokens/purchases/monero/invoices/", server, value_103)
	var value_107 ServerHandler = func(value_104 *Server, value_105 ResponseWriter, value_106 *Request) {
		Server_HandleMoneroDepositsAddress(value_104, value_105, value_106)
	}
	Server_Route(mux, "GET /api/v1/tokens/purchases/monero/address", server, value_107)
	var value_111 ServerHandler = func(value_108 *Server, value_109 ResponseWriter, value_110 *Request) {
		Server_HandleMoneroDepositsAddress(value_108, value_109, value_110)
	}
	Server_Route(mux, "GET /api/v1/tokens/purchases/monero/address/", server, value_111)
	var value_115 ServerHandler = func(value_112 *Server, value_113 ResponseWriter, value_114 *Request) {
		Server_HandleMoneroDepositsDeposits(value_112, value_113, value_114)
	}
	Server_Route(mux, "GET /api/v1/tokens/purchases/monero/deposits", server, value_115)
	var value_119 ServerHandler = func(value_116 *Server, value_117 ResponseWriter, value_118 *Request) {
		Server_HandleTokenHttpLatestCheckpoint(value_116, value_117, value_118)
	}
	Server_Route(mux, "GET /api/v1/tokens/checkpoints/latest", server, value_119)
	var value_123 ServerHandler = func(value_120 *Server, value_121 ResponseWriter, value_122 *Request) {
		Server_HandleTokenHttpReceipt(value_120, value_121, value_122)
	}
	Server_Route(mux, "GET /api/v1/tokens/receipts/", server, value_123)
	var value_127 ServerHandler = func(value_124 *Server, value_125 ResponseWriter, value_126 *Request) {
		Server_HandleTokenHttpManualCredit(value_124, value_125, value_126)
	}
	Server_Route(mux, "POST /api/v1/admin/tokens/manual-credit", server, value_127)
	var value_131 ServerHandler = func(value_128 *Server, value_129 ResponseWriter, value_130 *Request) {
		Server_HandleTokenHttpCreateCheckpoint(value_128, value_129, value_130)
	}
	Server_Route(mux, "POST /api/v1/admin/tokens/checkpoint", server, value_131)
	var value_135 ServerHandler = func(value_132 *Server, value_133 ResponseWriter, value_134 *Request) {
		Server_HandleSyncDiagnostics(value_132, value_133, value_134)
	}
	Server_Route(mux, "GET /api/v1/sync/diagnostics", server, value_135)
	var value_139 ServerHandler = func(value_136 *Server, value_137 ResponseWriter, value_138 *Request) {
		Server_HandleChallenge(value_136, value_137, value_138)
	}
	Server_Route(mux, "GET /api/v1/sync/challenge", server, value_139)
	var value_143 ServerHandler = func(value_140 *Server, value_141 ResponseWriter, value_142 *Request) {
		Server_HandleSyncWebSocket(value_140, value_141, value_142)
	}
	Server_Route(mux, "GET /api/v1/sync/ws", server, value_143)
	Server_Route(mux, "POST /api/v1/sync/login", server, func(value_144 *Server, value_145 ResponseWriter, value_146 *Request) {
		Server_HandleLogin(value_144, value_145, value_146)
	})
	Server_Route(mux, "POST /api/v1/sync", server, func(value_147 *Server, value_148 ResponseWriter, value_149 *Request) {
		Server_HandleSync(value_147, value_148, value_149)
	})
	var value_153 ServerHandler = func(value_150 *Server, value_151 ResponseWriter, value_152 *Request) {
		Server_HandleAccountHttpAlias(value_150, value_151, value_152)
	}
	Server_Route(mux, "POST /api/v1/account/alias", server, value_153)
	var value_157 ServerHandler = func(value_154 *Server, value_155 ResponseWriter, value_156 *Request) {
		Server_HandleAccountHttpProfileIcon(value_154, value_155, value_156)
	}
	Server_Route(mux, "POST /api/v1/account/profile-icon", server, value_157)
	var value_161 ServerHandler = func(value_158 *Server, value_159 ResponseWriter, value_160 *Request) {
		Server_HandleAccountHttpExport(value_158, value_159, value_160)
	}
	Server_Route(mux, "GET /api/v1/account/export", server, value_161)
	var value_165 ServerHandler = func(value_162 *Server, value_163 ResponseWriter, value_164 *Request) {
		Server_HandleDeviceHttpRoute(value_162, value_163, value_164)
	}
	Server_Route(mux, "GET /api/v1/account/devices", server, value_165)
	var value_169 ServerHandler = func(value_166 *Server, value_167 ResponseWriter, value_168 *Request) {
		Server_HandleDeviceHttpRoute(value_166, value_167, value_168)
	}
	Server_Route(mux, "POST /api/v1/account/devices", server, value_169)
	var value_173 ServerHandler = func(value_170 *Server, value_171 ResponseWriter, value_172 *Request) {
		Server_HandleDeviceHttpRoute(value_170, value_171, value_172)
	}
	Server_Route(mux, "DELETE /api/v1/account/devices", server, value_173)
	var value_177 ServerHandler = func(value_174 *Server, value_175 ResponseWriter, value_176 *Request) {
		Server_HandleAppHttpGrants(value_174, value_175, value_176)
	}
	Server_Route(mux, "GET /api/v1/account/app-grants", server, value_177)
	var value_181 ServerHandler = func(value_178 *Server, value_179 ResponseWriter, value_180 *Request) {
		Server_HandleAppHttpGrants(value_178, value_179, value_180)
	}
	Server_Route(mux, "POST /api/v1/account/app-grants", server, value_181)
	var value_185 ServerHandler = func(value_182 *Server, value_183 ResponseWriter, value_184 *Request) {
		Server_HandleAppHttpGrantSigned(value_182, value_183, value_184)
	}
	Server_Route(mux, "POST /api/v1/account/app-grants/signed", server, value_185)
	var value_189 ServerHandler = func(value_186 *Server, value_187 ResponseWriter, value_188 *Request) {
		Server_HandleAppHttpGrantRoute(value_186, value_187, value_188)
	}
	Server_Route(mux, "DELETE /api/v1/account/app-grants/", server, value_189)
	var value_193 ServerHandler = func(value_190 *Server, value_191 ResponseWriter, value_192 *Request) {
		Server_HandleAppHttpRecords(value_190, value_191, value_192)
	}
	Server_Route(mux, "GET /api/v1/account/app-records", server, value_193)
	var value_197 ServerHandler = func(value_194 *Server, value_195 ResponseWriter, value_196 *Request) {
		Server_HandleDeleteAccount(value_194, value_195, value_196)
	}
	Server_Route(mux, "DELETE /api/v1/account", server, value_197)
	var value_201 ServerHandler = func(value_198 *Server, value_199 ResponseWriter, value_200 *Request) {
		Server_HandleDeleteAccount(value_198, value_199, value_200)
	}
	Server_Route(mux, "POST /api/v1/account/delete", server, value_201)
	var value_205 ServerHandler = func(value_202 *Server, value_203 ResponseWriter, value_204 *Request) {
		Server_HandleDeleteAccountWithKey(value_202, value_203, value_204)
	}
	Server_Route(mux, "POST /api/v1/account/delete-with-key", server, value_205)
	var value_209 ServerHandler = func(value_206 *Server, value_207 ResponseWriter, value_208 *Request) {
		Server_HandleSocialHttpFriends(value_206, value_207, value_208)
	}
	Server_Route(mux, "GET /api/v1/friends", server, value_209)
	var value_213 ServerHandler = func(value_210 *Server, value_211 ResponseWriter, value_212 *Request) {
		Server_HandleSocialHttpRemoveFriend(value_210, value_211, value_212)
	}
	Server_Route(mux, "DELETE /api/v1/friends/", server, value_213)
	var value_217 ServerHandler = func(value_214 *Server, value_215 ResponseWriter, value_216 *Request) {
		Server_HandleSocialHttpRequests(value_214, value_215, value_216)
	}
	Server_Route(mux, "GET /api/v1/friends/requests", server, value_217)
	var value_221 ServerHandler = func(value_218 *Server, value_219 ResponseWriter, value_220 *Request) {
		Server_HandleSocialHttpCreateRequest(value_218, value_219, value_220)
	}
	Server_Route(mux, "POST /api/v1/friends/requests", server, value_221)
	var value_225 ServerHandler = func(value_222 *Server, value_223 ResponseWriter, value_224 *Request) {
		Server_HandleSocialHttpRequestAction(value_222, value_223, value_224)
	}
	Server_Route(mux, "POST /api/v1/friends/requests/", server, value_225)
	var value_229 ServerHandler = func(value_226 *Server, value_227 ResponseWriter, value_228 *Request) {
		Server_HandleSocialHttpPutStats(value_226, value_227, value_228)
	}
	Server_Route(mux, "PUT /api/v1/profile/stats", server, value_229)
	var value_233 ServerHandler = func(value_230 *Server, value_231 ResponseWriter, value_232 *Request) {
		Server_HandleSocialHttpFriendStats(value_230, value_231, value_232)
	}
	Server_Route(mux, "GET /api/v1/friends/stats", server, value_233)
	var value_237 ServerHandler = func(value_234 *Server, value_235 ResponseWriter, value_236 *Request) {
		Server_HandleBundleHttpRoute(value_234, value_235, value_236)
	}
	Server_Route(mux, "GET /api/v1/packages/", server, value_237)
	return Server_WithCommonHeaders(server, Handler(mux))
}

func (receiver *Server) Routes() Handler {
	return Server_Routes(receiver)
}

func Server_HandleDocs(server *Server, writer ResponseWriter, request *Request) {
	var value_0 string = server.Cfg.DBPath
	var value_4 ServerStats = func(value_1 *Server, value_2 Context, value_3 string) PublicStatsResult {
		return Server_PublicStats(value_1, value_2, value_3)
	}
	Docs_Handle(writer, request, value_0, Server_BindStats(value_4, server))
}

func Server_HandleOpenAPI(server *Server, writer ResponseWriter, request *Request) {
	Docs_OpenAPI(writer, request)
}

func Server_HandleTrustHttpCreateInvite(server *Server, writer ResponseWriter, request *Request) {
	TrustHttp_CreateInvite(Server_Trust(server), writer, request)
}

func Server_HandleTrustHttpAcceptInvite(server *Server, writer ResponseWriter, request *Request) {
	TrustHttp_AcceptInvite(Server_Trust(server), writer, request)
}

func Server_HandleTrustHttpCompletePairing(server *Server, writer ResponseWriter, request *Request) {
	TrustHttp_CompletePairing(Server_Trust(server), writer, request)
}

func Server_HandleTrustHttpListPeers(server *Server, writer ResponseWriter, request *Request) {
	TrustHttp_ListPeers(Server_Trust(server), writer, request)
}

func Server_HandleTrustHttpCreateSpace(server *Server, writer ResponseWriter, request *Request) {
	TrustHttp_CreateSpace(Server_Trust(server), writer, request)
}

func Server_HandleTrustHttpRegisterName(server *Server, writer ResponseWriter, request *Request) {
	TrustHttp_RegisterName(Server_Trust(server), writer, request)
}

func Server_HandleTrustHttpResolveName(server *Server, writer ResponseWriter, request *Request) {
	TrustHttp_ResolveName(Server_Trust(server), writer, request)
}

func Server_HandleMeshExport(server *Server, writer ResponseWriter, request *Request) {
	Mesh_Export(Server_Mesh(server), writer, request)
}

func Server_HandleMeshImport(server *Server, writer ResponseWriter, request *Request) {
	Mesh_Import(Server_Mesh(server), writer, request)
}

func Server_HandleAppHttpList(server *Server, writer ResponseWriter, request *Request) {
	AppHttp_List(Server_AppRegistry(server), writer, request)
}

func Server_HandleBundleHttpRoute(server *Server, writer ResponseWriter, request *Request) {
	BundleHttp_Route(Server_AppRegistry(server), writer, request)
}

func Server_HandleAppHttpRegisterSigned(server *Server, writer ResponseWriter, request *Request) {
	AppHttp_RegisterSigned(Server_AppRegistry(server), writer, request)
}

func Server_HandleAppHttpRoute(server *Server, writer ResponseWriter, request *Request) {
	AppHttp_Route(Server_AppRegistry(server), writer, request)
}

func Server_HandleTokenHttpAssets(server *Server, writer ResponseWriter, request *Request) {
	TokenHttp_Assets(Server_Tokens(server), writer, request)
}

func Server_HandleTokenHttpProducts(server *Server, writer ResponseWriter, request *Request) {
	TokenHttp_Products(Server_Tokens(server), writer, request)
}

func Server_HandleTokenHttpIssuer(server *Server, writer ResponseWriter, request *Request) {
	TokenHttp_Issuer(Server_Tokens(server), writer, request)
}

func Server_HandleTokenHttpBalance(server *Server, writer ResponseWriter, request *Request) {
	TokenHttp_Balance(Server_Tokens(server), writer, request)
}

func Server_HandleTokenHttpLedger(server *Server, writer ResponseWriter, request *Request) {
	TokenHttp_Ledger(Server_Tokens(server), writer, request)
}

func Server_HandleTokenHttpSpend(server *Server, writer ResponseWriter, request *Request) {
	TokenHttp_Spend(Server_Tokens(server), writer, request)
}

func Server_HandleGooglePlayHttpVerify(server *Server, writer ResponseWriter, request *Request) {
	GooglePlayHttp_Verify(Server_Tokens(server), writer, request)
}

func Server_HandleMoneroInvoicesCreate(server *Server, writer ResponseWriter, request *Request) {
	MoneroInvoices_Create(Server_Monero(server), writer, request)
}

func Server_HandleMoneroInvoicesRead(server *Server, writer ResponseWriter, request *Request) {
	MoneroInvoices_Read(Server_Monero(server), writer, request)
}

func Server_HandleMoneroDepositsAddress(server *Server, writer ResponseWriter, request *Request) {
	MoneroDeposits_Address(Server_Monero(server), writer, request)
}

func Server_HandleMoneroDepositsDeposits(server *Server, writer ResponseWriter, request *Request) {
	MoneroDeposits_Deposits(Server_Monero(server), writer, request)
}

func Server_HandleTokenHttpLatestCheckpoint(server *Server, writer ResponseWriter, request *Request) {
	TokenHttp_LatestCheckpoint(Server_Tokens(server), writer, request)
}

func Server_HandleTokenHttpReceipt(server *Server, writer ResponseWriter, request *Request) {
	TokenHttp_Receipt(Server_Tokens(server), writer, request)
}

func Server_HandleTokenHttpManualCredit(server *Server, writer ResponseWriter, request *Request) {
	TokenHttp_ManualCredit(Server_Tokens(server), writer, request)
}

func Server_HandleTokenHttpCreateCheckpoint(server *Server, writer ResponseWriter, request *Request) {
	TokenHttp_CreateCheckpoint(Server_Tokens(server), writer, request)
}

func Server_HandleAccountHttpAlias(server *Server, writer ResponseWriter, request *Request) {
	AccountHttp_Alias(Server_Accounts(server), writer, request)
}

func Server_HandleAccountHttpProfileIcon(server *Server, writer ResponseWriter, request *Request) {
	AccountHttp_ProfileIcon(Server_Accounts(server), writer, request)
}

func Server_HandleAccountHttpExport(server *Server, writer ResponseWriter, request *Request) {
	AccountHttp_Export(Server_Accounts(server), writer, request)
}

func Server_HandleDeviceHttpRoute(server *Server, writer ResponseWriter, request *Request) {
	DeviceHttp_Route(Server_Devices(server), writer, request)
}

func Server_HandleAppHttpGrants(server *Server, writer ResponseWriter, request *Request) {
	AppHttp_Grants(Server_AppRegistry(server), writer, request)
}

func Server_HandleAppHttpGrantSigned(server *Server, writer ResponseWriter, request *Request) {
	AppHttp_GrantSigned(Server_AppRegistry(server), writer, request)
}

func Server_HandleAppHttpGrantRoute(server *Server, writer ResponseWriter, request *Request) {
	AppHttp_GrantRoute(Server_AppRegistry(server), writer, request)
}

func Server_HandleAppHttpRecords(server *Server, writer ResponseWriter, request *Request) {
	AppHttp_Records(Server_AppRegistry(server), writer, request)
}

func Server_HandleSocialHttpFriends(server *Server, writer ResponseWriter, request *Request) {
	SocialHttp_Friends(Server_Social(server), writer, request)
}

func Server_HandleSocialHttpRemoveFriend(server *Server, writer ResponseWriter, request *Request) {
	SocialHttp_RemoveFriend(Server_Social(server), writer, request)
}

func Server_HandleSocialHttpRequests(server *Server, writer ResponseWriter, request *Request) {
	SocialHttp_Requests(Server_Social(server), writer, request)
}

func Server_HandleSocialHttpCreateRequest(server *Server, writer ResponseWriter, request *Request) {
	SocialHttp_CreateRequest(Server_Social(server), writer, request)
}

func Server_HandleSocialHttpRequestAction(server *Server, writer ResponseWriter, request *Request) {
	SocialHttp_RequestAction(Server_Social(server), writer, request)
}

func Server_HandleSocialHttpPutStats(server *Server, writer ResponseWriter, request *Request) {
	SocialHttp_PutStats(Server_Social(server), writer, request)
}

func Server_HandleSocialHttpFriendStats(server *Server, writer ResponseWriter, request *Request) {
	SocialHttp_FriendStats(Server_Social(server), writer, request)
}

func Server_HandleHealth(server *Server, writer ResponseWriter, request *Request) {
	OperationalHttp_Health(writer, request)
}

func (receiver *Server) handleHealth(argument1 ResponseWriter, argument2 *Request) {
	Server_HandleHealth(receiver, argument1, argument2)
}

func Server_HandleReady(server *Server, writer ResponseWriter, request *Request) {
	OperationalHttp_Ready(Server_Operations(server), writer, request)
}

func (receiver *Server) handleReady(argument1 ResponseWriter, argument2 *Request) {
	Server_HandleReady(receiver, argument1, argument2)
}

func Server_HandleNodeInfo(server *Server, writer ResponseWriter, request *Request) {
	OperationalHttp_Node(Server_Operations(server), writer, request)
}

func (receiver *Server) handleNodeInfo(argument1 ResponseWriter, argument2 *Request) {
	Server_HandleNodeInfo(receiver, argument1, argument2)
}

func Server_HandleMetrics(server *Server, writer ResponseWriter, request *Request) {
	OperationalHttp_Metrics(Server_Operations(server), writer, request)
}

func (receiver *Server) handleMetrics(argument1 ResponseWriter, argument2 *Request) {
	Server_HandleMetrics(receiver, argument1, argument2)
}

func Server_HandleSyncDiagnostics(server *Server, writer ResponseWriter, request *Request) {
	OperationalHttp_Diagnostics(Server_Operations(server), writer, request)
}

func (receiver *Server) handleSyncDiagnostics(argument1 ResponseWriter, argument2 *Request) {
	Server_HandleSyncDiagnostics(receiver, argument1, argument2)
}

func Server_HandleChallenge(server *Server, writer ResponseWriter, request *Request) {
	AccountAccess_Challenge(Server_Access(server), writer, request)
}

func (receiver *Server) handleChallenge(argument1 ResponseWriter, argument2 *Request) {
	Server_HandleChallenge(receiver, argument1, argument2)
}

func Server_HandleSync(server *Server, writer ResponseWriter, request *Request) {
	SyncHttp_Handle(Server_Synchronization(server), writer, request)
}

func (receiver *Server) handleSync(argument1 ResponseWriter, argument2 *Request) {
	Server_HandleSync(receiver, argument1, argument2)
}

func Server_HandleLogin(server *Server, writer ResponseWriter, request *Request) {
	AccountAccess_Login(Server_Access(server), writer, request)
}

func (receiver *Server) handleLogin(argument1 ResponseWriter, argument2 *Request) {
	Server_HandleLogin(receiver, argument1, argument2)
}

func Server_HandleDeleteAccount(server *Server, writer ResponseWriter, request *Request) {
	AccountAccess_Delete(Server_Access(server), writer, request)
}

func (receiver *Server) handleDeleteAccount(argument1 ResponseWriter, argument2 *Request) {
	Server_HandleDeleteAccount(receiver, argument1, argument2)
}

func Server_HandleDeleteAccountWithKey(server *Server, writer ResponseWriter, request *Request) {
	AccountAccess_DeleteWithKey(Server_Access(server), writer, request)
}

func (receiver *Server) handleDeleteAccountWithKey(argument1 ResponseWriter, argument2 *Request) {
	Server_HandleDeleteAccountWithKey(receiver, argument1, argument2)
}

func Server_HandleSyncWebSocket(server *Server, writer ResponseWriter, request *Request) {
	SyncWs_Handle(Server_SyncSocket(server), writer, request)
}

func (receiver *Server) handleSyncWebSocket(argument1 ResponseWriter, argument2 *Request) {
	Server_HandleSyncWebSocket(receiver, argument1, argument2)
}

func Server_GlobalInit00() {
	errSignedTxReplay = StdErrorsGo_New("signed transaction replay")
}

func Server_GlobalInit10() {
	errAppScopeNotOwned = StdErrorsGo_New("app does not own collection scope")
}

var Server_ziranInitState uint8

func Server_ziranInit() {
	if Server_ziranInitState == 2 {
		return
	}
	if Server_ziranInitState == 1 {
		panic("cyclic module startup")
	}
	Server_ziranInitState = 1
	Store_ziranInit()
	Verifier_ziranInit()
	GooglePlayHttp_ziranInit()
	Docs_ziranInit()
	PaymentState_ziranInit()
	Server_GlobalInit00()
	Server_GlobalInit10()
	Server_ziranInitState = 2
}

func init() { Server_ziranInit() }
