// Code generated by zi2go from session.zi. DO NOT EDIT.
package main

import (
	strconv "strconv"
	strings "strings"
)

// #import std_go_types
type SessionChallenge struct {
	GrantID   string "json:\"grant_id\""
	Challenge string "json:\"challenge\""
	NodeID    string "json:\"node_id\""
	Audience  string "json:\"audience\""
	ExpiresAt int64  "json:\"expires_at\""
}

type SessionRequest struct {
	GrantID   string "json:\"grant_id\""
	Challenge string "json:\"challenge\""
	Signature string "json:\"signature\""
}

type SessionCredential struct {
	SessionID string "json:\"session_id\""
	GrantID   string "json:\"grant_id\""
	Challenge string "json:\"challenge\""
	ExpiresAt int64  "json:\"expires_at\""
}

type RequestProof struct {
	Version    int    "json:\"version\""
	GrantID    string "json:\"grant_id\""
	SessionID  string "json:\"session_id\""
	AccountID  string "json:\"account_id\""
	AppID      string "json:\"app_id\""
	ClientID   string "json:\"client_id\""
	NodeID     string "json:\"node_id\""
	Audience   string "json:\"audience\""
	Challenge  string "json:\"challenge\""
	Method     string "json:\"method\""
	Path       string "json:\"path\""
	Query      string "json:\"query\""
	BodySHA256 string "json:\"body_sha256\""
	ExpiresAt  int64  "json:\"expires_at\""
	Nonce      string "json:\"nonce\""
	Signature  string "json:\"signature\""
}

type ScopedPrincipal struct {
	Grant          Grant
	ExpiresAt      int64
	Authentication AuthenticationResult
}

func Session_RawQuery(Value *URL) string {
	return Value.RawQuery
}

func Session_ChallengeMessage(value SessionChallenge) string {
	var value_0 [7]string
	value_0[0] = "daochi-session-v1"
	value_0[1] = value.GrantID
	value_0[2] = value.Challenge
	value_0[3] = value.NodeID
	value_0[4] = value.Audience
	var value_1 string = strconv.FormatInt(int64(value.ExpiresAt), int(10))
	value_0[5] = value_1
	value_0[6] = ""
	fields := value_0
	_ = fields
	return strings.Join(fields[0:7:7], "\n")
}

func Session_ProofMessage(proof RequestProof) string {
	var value_0 [18]string
	value_0[0] = "daochi-delegate-request-v1"
	value_0[1] = "1"
	value_0[2] = proof.GrantID
	value_0[3] = proof.SessionID
	value_0[4] = proof.AccountID
	value_0[5] = proof.AppID
	value_0[6] = proof.ClientID
	value_0[7] = proof.NodeID
	value_0[8] = proof.Audience
	value_0[9] = proof.Challenge
	value_0[10] = proof.Method
	value_0[11] = proof.Path
	value_0[12] = proof.Query
	value_0[13] = proof.BodySHA256
	var value_1 string = strconv.FormatInt(int64(proof.ExpiresAt), int(10))
	value_0[14] = value_1
	value_0[15] = proof.Nonce
	value_0[16] = ""
	value_0[17] = ""
	fields := value_0
	_ = fields
	return strings.Join(fields[0:17:17], "\n")
}

func Session_VerifyKeyProof(publicKey string, message string, signatureText string) bool {
	var value_0 bool = Authorization_HexID(publicKey, 64)
	var value_1 bool = !value_0
	if !value_1 {
		var value_2 bool = Authorization_HexID(signatureText, 128)
		value_1 = !value_2
	}
	if value_1 {
		return false
	}
	key := Codec_DecodeBinaryField(publicKey)
	signature := Codec_DecodeBinaryField(signatureText)
	var value_3 bool = key.Error == "" && signature.Error == ""
	if value_3 {
		var value_4 []uint8 = StdTextGo_ToBytes(key.Value)
		var value_5 bool = StdEd25519Go_Verify(PublicKey(value_4), StdTextGo_ToBytes(message), StdTextGo_ToBytes(signature.Value))
		value_3 = value_5
	}
	return value_3
}

func Session_ValidQuery(request *Request, query string) bool {
	if query != Session_RawQuery(StdHttpGo_RequestURL(request)) {
		return false
	}
	if StdUrlGo_Path(StdHttpGo_RequestURL(request)) != "/api/v1/delegated/ws" {
		return query == ""
	}
	collection := StdUrlGo_Value(StdUrlGo_Query(StdHttpGo_RequestURL(request)), "collection")
	var value_0 [2]string
	value_0[0] = "collection="
	value_0[1] = collection
	fields := value_0
	_ = fields
	var value_1 bool = Identity_ValidEncryptedHierarchyCollection(collection)
	var value_2 bool = value_1
	if value_2 {
		var value_3 bool = query == strings.Join(fields[0:2:2], "")
		value_2 = value_3
	}
	return value_2
}

func Session_SocketHeaders(request *Request) bool {
	headers := StdHttpGo_Headers(request)
	proof := StdHttpGo_HeaderValue(headers, "X-Daochi-Delegate")
	credential := StdHttpGo_HeaderValue(headers, "Authorization")
	{
		var value_0 []string = strings.Split(StdHttpGo_HeaderValue(headers, "Sec-WebSocket-Protocol"), ",")
		if int64(0) < 0 || int64(int64(len(value_0))) < int64(0) || int64(int64(len(value_0))) > int64(len(value_0)) {
			panic("slice range out of bounds")
		}
		loop_view_3 := value_0[0:int64(len(value_0)):int64(len(value_0))]
		loop_count_3 := int64(len(loop_view_3))
		var loop_cursor_3 int64 = 0
		for loop_cursor_3 < loop_count_3 {
			loop_index_3 := loop_cursor_3
			protocol := loop_view_3[loop_index_3]
			fields := strings.Split(strings.TrimSpace(protocol), ".")
			if int64(len(fields)) == 3 && fields[0] == "daochi" && fields[1] == "delegate" {
				decoded := Codec_DecodeBase64(fields[2], true, false)
				if decoded.Error != "" || proof != "" || int64(len(decoded.Value)) > 4096 {
					return false
				}
				proof = decoded.Value
			} else if int64(len(fields)) == 3 && fields[0] == "daochi" && fields[1] == "session" {
				var value_2 bool = Authorization_HexID(fields[2], 32)
				if !value_2 || credential != "" {
					return false
				}
				var value_3 [2]string
				value_3[0] = "Delegate ds1."
				value_3[1] = fields[2]
				parts := value_3
				_ = parts
				credential = strings.Join(parts[0:2:2], "")
			}
			loop_cursor_3++
		}
	}
	StdHttpGo_SetHeader(headers, "X-Daochi-Delegate", proof)
	StdHttpGo_SetHeader(headers, "Authorization", credential)
	return proof != "" && credential != ""
}

func Session_AuthenticateTx(transaction *Transaction, context Context, request *Request, body []uint8, nodeID string, audience string) ScopedPrincipal {
	var result ScopedPrincipal = ScopedPrincipal{}
	headers := StdHttpGo_Headers(request)
	header := StdHttpGo_HeaderValue(headers, "X-Daochi-Delegate")
	var proof RequestProof = RequestProof{}
	now := StdTimeGo_Unix(StdTimeGo_Now())
	var value_0 bool = int64(len(header)) == 0 || int64(len(header)) > 4096
	if !value_0 {
		var value_1 Error = StrictJson_Decode(StdTextGo_ToBytes(header), &(proof))
		value_0 = (value_1 != nil)
	}
	var value_2 bool = value_0 || proof.Version != 1
	var value_3 bool = value_2
	if !value_3 {
		var value_4 bool = Authorization_HexID(proof.SessionID, 32)
		value_3 = !value_4
	}
	var value_5 bool = value_3
	var value_6 bool = value_5
	if !value_6 {
		var value_7 bool = Authorization_HexID(proof.GrantID, 32)
		value_6 = !value_7
	}
	var value_8 bool = value_6
	var value_9 bool = value_8
	if !value_9 {
		var value_10 bool = Authorization_HexID(proof.Nonce, 32)
		value_9 = !value_10
	}
	var value_11 bool = value_9 || proof.NodeID != nodeID || proof.Audience != audience || proof.ExpiresAt <= now || proof.ExpiresAt > now+60
	var value_12 bool = value_11
	var value_13 bool = value_12
	if !value_13 {
		var value_14 string = proof.Method
		var value_15 bool = value_14 != StdHttpGo_Method(request)
		value_13 = value_15
	}
	var value_16 bool = value_13
	var value_17 bool = value_16
	if !value_17 {
		var value_18 string = proof.Path
		var value_19 bool = value_18 != StdUrlGo_Path(StdHttpGo_RequestURL(request))
		value_17 = value_19
	}
	var value_20 bool = value_17
	var value_21 bool = value_20
	if !value_21 {
		var value_22 string = StdUrlGo_EscapedPath(StdHttpGo_RequestURL(request))
		value_21 = (value_22 != proof.Path)
	}
	var value_23 bool = value_21
	var value_24 bool = value_23
	if !value_24 {
		var value_25 bool = Session_ValidQuery(request, proof.Query)
		value_24 = !value_25
	}
	var value_26 bool = value_24
	var value_27 bool = value_26
	if !value_27 {
		var value_28 string = proof.BodySHA256
		var value_29 bool = value_28 != Signing_SHA256Hex(body)
		value_27 = value_29
	}
	if value_27 {
		var value_30 AuthenticationResult = Authentication_Failure(401, "invalid delegate request proof")
		result.Authentication = value_30
		return result
	}
	var value_31 [2]string
	value_31[0] = "Delegate ds1."
	value_31[1] = proof.SessionID
	credential := value_31
	_ = credential
	if StdHttpGo_HeaderValue(headers, "Authorization") != strings.Join(credential[0:2:2], "") {
		var value_32 AuthenticationResult = Authentication_Failure(401, "delegate session required")
		result.Authentication = value_32
		return result
	}
	var value_33 [3]Any
	value_33[0] = proof.SessionID
	value_33[1] = proof.GrantID
	value_33[2] = now
	arguments := value_33
	var value_34 string = "UPDATE server_authorization_sessions SET expires_at=expires_at WHERE session_id=?1 AND grant_id=?2 AND expires_at>?3"
	locked := StdSqlGo_ExecTx(transaction, context, value_34, arguments[0:3:3])
	if locked.Error != nil {
		var value_35 AuthenticationResult = Authentication_NativeFailure(locked.Error)
		result.Authentication = value_35
		return result
	}
	changed := StdSqlGo_RowsAffected(locked.Value)
	if changed.Error != nil || changed.Value != 1 {
		var value_36 AuthenticationResult = Authentication_Failure(401, "delegate session expired")
		result.Authentication = value_36
		return result
	}
	var challenge string = ""
	var value_37 [2]Any
	value_37[0] = &(challenge)
	value_37[1] = &(result.ExpiresAt)
	destinations := value_37
	_ = destinations
	var value_38 string = "SELECT challenge,expires_at FROM server_authorization_sessions WHERE session_id=?1 AND grant_id=?2"
	row := StdSqlGo_QueryRowTx(transaction, context, value_38, arguments[0:2:2])
	var value_39 Error = StdSqlGo_ScanRow(row, destinations[0:2:2])
	if value_39 != nil || proof.Challenge != challenge || proof.ExpiresAt > result.ExpiresAt {
		var value_40 AuthenticationResult = Authentication_Failure(401, "delegate session mismatch")
		result.Authentication = value_40
		return result
	}
	active := Authorization_ActiveGrant(transaction, context, proof.GrantID, nodeID, audience, now)
	result.Authentication = active.Authentication
	if result.Authentication.Error != nil || result.Authentication.Status != 0 {
		return result
	}
	grant := active.Value
	var value_41 bool = proof.AccountID != grant.AccountID || proof.AppID != grant.AppID || proof.ClientID != grant.ClientID
	var value_42 bool = value_41
	var value_43 bool = value_42
	if !value_43 {
		var value_44 string = Session_ProofMessage(proof)
		var value_45 bool = Session_VerifyKeyProof(grant.SigningKey, value_44, proof.Signature)
		value_43 = !value_45
	}
	if value_43 {
		var value_46 AuthenticationResult = Authentication_Failure(401, "delegate signature rejected")
		result.Authentication = value_46
		return result
	}
	userHeader := StdHttpGo_HeaderValue(headers, "X-Daochi-User")
	if userHeader != "" && userHeader != grant.AccountID {
		var value_47 AuthenticationResult = Authentication_Failure(401, "delegate account mismatch")
		result.Authentication = value_47
		return result
	}
	arguments[0] = grant.GrantID
	arguments[1] = proof.Nonce
	arguments[2] = proof.ExpiresAt
	var value_48 [1]Any
	value_48[0] = now
	cutoff := value_48
	_ = cutoff
	pruned := StdSqlGo_ExecTx(transaction, context, "DELETE FROM server_authorization_nonces WHERE expires_at<?1", cutoff[0:1:1])
	if pruned.Error != nil {
		var value_49 AuthenticationResult = Authentication_NativeFailure(pruned.Error)
		result.Authentication = value_49
		return result
	}
	var value_50 string = "INSERT INTO server_authorization_nonces(grant_id,nonce,expires_at) VALUES(?1,?2,?3) ON CONFLICT(grant_id,nonce) DO NOTHING"
	claimed := StdSqlGo_ExecTx(transaction, context, value_50, arguments[0:3:3])
	if claimed.Error != nil {
		var value_51 AuthenticationResult = Authentication_NativeFailure(claimed.Error)
		result.Authentication = value_51
		return result
	}
	changed = StdSqlGo_RowsAffected(claimed.Value)
	if changed.Error != nil {
		var value_52 AuthenticationResult = Authentication_NativeFailure(changed.Error)
		result.Authentication = value_52
		return result
	}
	if changed.Value != 1 {
		var value_53 AuthenticationResult = Authentication_Failure(409, "delegate request replayed")
		result.Authentication = value_53
		return result
	}
	result.Grant = grant
	return result
}
