// Code generated by zi2go from sets.zi. DO NOT EDIT.
package main

import strings "strings"

// #import map_go
type StringSet = map[string]bool

func Sets_FromEnvironment(raw string) StringSet {
	var result StringSet = *new(StringSet)
	var value_0 *StringSet = &(result)
	if (*value_0) == nil {
		(*value_0) = make(StringSet)
	}
	values := strings.Split(raw, ",")
	for _, value := range values {
		item := strings.TrimSpace(value)
		if item != "" {
			var value_1 *StringSet = &(result)
			var value_2 string = item
			var value_3 bool = true
			if (*value_1) == nil {
				(*value_1) = make(StringSet)
			}
			(*value_1)[value_2] = value_3
		}
	}
	return result
}

func Sets_Normalize(values []string) StringSet {
	var result StringSet = *new(StringSet)
	var value_0 *StringSet = &(result)
	if (*value_0) == nil {
		(*value_0) = make(StringSet)
	}
	for _, value := range values {
		item := strings.ToLower(strings.TrimSpace(value))
		if item != "" {
			var value_1 *StringSet = &(result)
			var value_2 string = item
			var value_3 bool = true
			if (*value_1) == nil {
				(*value_1) = make(StringSet)
			}
			(*value_1)[value_2] = value_3
		}
	}
	return result
}
