// Code generated by zi2go from signing_test.zi. DO NOT EDIT.
package main

import (
	sha256 "crypto/sha256"
	hex "encoding/hex"
	fmt "fmt"
	testing "testing"
)

// #import std_go_types
func SigningTest_CanonicalMessageSignsRawBodyHash(test *Test) {
	nonce := StdTextGo_ToBytes("01234567890123456789012345678901")
	body := StdTextGo_ToBytes("{\"user_id_hash\":\"u\",\"habits\":[{\"id\":\"habit-1\",\"name\":\"Meditate\"}]}")
	bodyHash := sha256.Sum256(body)
	_ = bodyHash
	got := Signing_CanonicalMessage(nonce, "post", "/api/v1/sync", body)
	want := fmt.Sprintf("ksync-sync-v1\nPOST\n/api/v1/sync\n%s\n%s\n", hex.EncodeToString(bodyHash[0:32:32]), hex.EncodeToString(nonce))
	if got != want {
		var value_0 [2]Any
		value_0[0] = got
		value_0[1] = want
		arguments := value_0
		_ = arguments
		TestingTest_Fatalf(test, "message mismatch\n got: %q\nwant: %q", arguments[0:2:2])
	}
}

func TestCanonicalMessageSignsRawBodyHash(export_arg_0 *testing.T) {
	SigningTest_CanonicalMessageSignsRawBodyHash(export_arg_0)
}
