// Code generated by zi2go from signing.zi. DO NOT EDIT.
package main

import (
	sha256 "crypto/sha256"
	hex "encoding/hex"
	strings "strings"
)

func Signing_CanonicalMessage(nonce []uint8, method string, path string, payload []uint8) string {
	return Signing_CanonicalMessageWithContext("ksync-sync-v1", nonce, method, path, payload)
}

func Signing_CanonicalMessageWithContext(context string, nonce []uint8, method string, path string, payload []uint8) string {
	sum := sha256.Sum256(payload)
	_ = sum
	var value_0 string = strings.ToUpper(method)
	var value_1 string = hex.EncodeToString(sum[0:32:32])
	var value_2 string = hex.EncodeToString(nonce)
	parts := [6]string{context, value_0, path, value_1, value_2, ""}
	_ = parts
	return strings.Join(parts[0:6:6], "\n")
}
