// Code generated by zi2go from signed_tx.zi. DO NOT EDIT.
package main

import (
	sql "database/sql"
	strings "strings"
)

// #import std_go_types
// #import transaction
type SignedHeaderResult struct {
	Value          SignedTxEnvelope
	Authentication AuthenticationResult
}

type zir_773b400a7b2b4942_ExecResult struct {
	Value Result
	Error Error
}

func SignedTx_DeleteExpired(Database *Database, Context Context, Query string, Now int64) zir_773b400a7b2b4942_ExecResult {
	var result zir_773b400a7b2b4942_ExecResult
	result.Value, result.Error = (*sql.DB).ExecContext(Database, Context, Query, Now)
	return result
}

func SignedTx_Insert(Database *Database, Context Context, Query string, AccountID string, TxID string, AppID string, Nonce string, Expiry int64) zir_773b400a7b2b4942_ExecResult {
	var result zir_773b400a7b2b4942_ExecResult
	result.Value, result.Error = (*sql.DB).ExecContext(Database, Context, Query, AccountID, TxID, AppID, Nonce, Expiry)
	return result
}

func SignedTx_Delete(Database *Database, Context Context, Query string, AccountID string, TxID string, AppID string, Nonce string) zir_773b400a7b2b4942_ExecResult {
	var result zir_773b400a7b2b4942_ExecResult
	result.Value, result.Error = (*sql.DB).ExecContext(Database, Context, Query, AccountID, TxID, AppID, Nonce)
	return result
}

const TransactionContext = "daochi-tx-v1"
const AppManifestContext = "daochi-app-manifest-v1"
const AppApprovalContext = "daochi-app-approval-v1"
const MaxFutureSkew = 900000000000

func SignedTx_ReadHeader(request *Request) SignedHeaderResult {
	var result SignedHeaderResult = SignedHeaderResult{}
	value := strings.TrimSpace(StdHttpGo_HeaderValue(StdHttpGo_Headers(request), "X-Daochi-Tx"))
	if value == "" {
		var value_0 AuthenticationResult = Authentication_Failure(int(401), "signed transaction required")
		result.Authentication = value_0
		return result
	}
	raw := value
	var value_1 bool = strings.HasPrefix(value, "{")
	if !value_1 {
		decoded := Codec_DecodeBase64(value, true, false)
		if decoded.Error != "" {
			decoded = Codec_DecodeBase64(value, true, true)
		}
		if decoded.Error != "" {
			var value_2 AuthenticationResult = Authentication_Failure(int(400), "invalid signed transaction")
			result.Authentication = value_2
			return result
		}
		raw = decoded.Value
	}
	var tx SignedTxEnvelope = SignedTxEnvelope{}
	var value_3 Error = StdJsonGo_Unmarshal(StdTextGo_ToBytes(raw), &(tx))
	if value_3 != nil {
		var value_4 AuthenticationResult = Authentication_Failure(int(400), "invalid signed transaction")
		result.Authentication = value_4
		return result
	}
	Transaction_Normalize(&(tx))
	result.Value = tx
	return result
}

func SignedTx_Verify(database *Database, context Context, request *Request, body []uint8, tx SignedTxEnvelope, accountID string, appID string, verifySignature VerifySignature, replay Error) AuthenticationResult {
	accountID = strings.ToLower(strings.TrimSpace(accountID))
	appID = strings.TrimSpace(appID)
	if tx.ProtocolVersion < 6 {
		return Authentication_Failure(int(400), "signed transaction protocol too old")
	}
	if tx.SignatureContext != "" && tx.SignatureContext != "daochi-tx-v1" {
		return Authentication_Failure(int(400), "invalid signed transaction context")
	}
	var value_0 bool = Identity_ValidClientID(tx.TxID)
	var value_1 bool = !value_0
	if !value_1 {
		var value_2 bool = Identity_ValidClientID(tx.Nonce)
		value_1 = !value_2
	}
	if value_1 {
		return Authentication_Failure(int(400), "invalid signed transaction id")
	}
	var value_3 bool = Identity_ValidUserID(tx.AccountID)
	if !value_3 || tx.AccountID != accountID {
		return Authentication_Failure(int(401), "signed transaction account mismatch")
	}
	var value_4 bool = Identity_ValidNamespace(tx.AppID)
	if !value_4 || tx.AppID != appID {
		return Authentication_Failure(int(401), "signed transaction app mismatch")
	}
	var value_5 bool = tx.Method != StdHttpGo_Method(request)
	var value_6 bool = value_5
	if !value_6 {
		var value_7 bool = tx.Path != StdUrlGo_Path(StdHttpGo_RequestURL(request))
		value_6 = value_7
	}
	if value_6 {
		return Authentication_Failure(int(401), "signed transaction route mismatch")
	}
	if tx.BodySHA256 != Signing_SHA256Hex(body) {
		return Authentication_Failure(int(401), "signed transaction body mismatch")
	}
	now := StdTimeGo_Now()
	var value_8 bool = tx.ExpiresAt <= StdTimeGo_Unix(now)
	var value_9 bool = value_8
	if !value_9 {
		var value_10 bool = StdTimeGo_After(StdTimeGo_FromUnix(tx.ExpiresAt, 0), StdTimeGo_Add(now, Duration(900000000000)))
		value_9 = value_10
	}
	if value_9 {
		return Authentication_Failure(int(401), "signed transaction expired")
	}
	account := AccountKeys_PublicKey(database, context, tx.AccountID)
	if account.Error != nil {
		return Authentication_NativeFailure(account.Error)
	}
	if !account.Found {
		return Authentication_Failure(int(401), "sync account not found")
	}
	signature := Codec_DecodeBinaryField(tx.Signature)
	if signature.Error != "" || int64(len(signature.Value)) != 2420 {
		return Authentication_Failure(int(400), "invalid signed transaction signature")
	}
	message := StdTextGo_ToBytes(Transaction_CanonicalMessage("daochi-tx-v1", tx))
	var value_11 VerifySignature = verifySignature
	var value_12 bool = value_11(account.Value, message, StdTextGo_ToBytes(signature.Value))
	if !value_12 {
		return Authentication_Failure(int(401), "signed transaction rejected")
	}
	device := SignedTx_VerifyDevice(database, context, tx, message)
	if device.Status != 0 || device.Error != nil {
		return device
	}
	recorded := SignedTx_Record(database, context, tx, replay)
	if recorded != nil {
		if StdErrorsGo_Is(recorded, replay) {
			return Authentication_Failure(int(409), "signed transaction replay")
		}
		return Authentication_NativeFailure(recorded)
	}
	var value_13 AuthenticationResult = Authentication_NativeFailure(DeviceKeys_Touch(database, context, tx.AccountID, tx.AppID, tx.DeviceKeyID))
	return value_13
}

func SignedTx_VerifyDevice(database *Database, context Context, tx SignedTxEnvelope, message []uint8) AuthenticationResult {
	var value_0 bool = Identity_ValidClientID(tx.DeviceKeyID)
	if !value_0 {
		return Authentication_Failure(int(400), "invalid device key id")
	}
	device := DeviceKeys_Active(database, context, tx.AccountID, tx.AppID, tx.DeviceKeyID)
	if device.Error != nil {
		return Authentication_NativeFailure(device.Error)
	}
	if !device.Found {
		return Authentication_Failure(int(401), "device key not registered")
	}
	publicKey := Codec_DecodeBinaryField(device.Value.PublicKey)
	if publicKey.Error != "" || int64(len(publicKey.Value)) != 32 {
		return Authentication_Failure(int(401), "invalid app public key")
	}
	signature := Codec_DecodeBinaryField(tx.DeviceSignature)
	if signature.Error != "" || int64(len(signature.Value)) != 64 {
		return Authentication_Failure(int(400), "invalid device signature")
	}
	var value_1 []uint8 = StdTextGo_ToBytes(publicKey.Value)
	var value_2 bool = StdEd25519Go_Verify(PublicKey(value_1), message, StdTextGo_ToBytes(signature.Value))
	if !value_2 {
		return Authentication_Failure(int(401), "device signature rejected")
	}
	return Authentication_NativeFailure(nil)
}

func SignedTx_Record(database *Database, context Context, tx SignedTxEnvelope, replay Error) Error {
	var value_0 zir_773b400a7b2b4942_ExecResult = SignedTx_DeleteExpired(database, context, "DELETE FROM server_signed_transactions WHERE expires_at<?1", int64(StdTimeGo_Unix(StdTimeGo_Now())))
	deleted := value_0
	if deleted.Error != nil {
		return deleted.Error
	}
	var value_1 string = "INSERT INTO server_signed_transactions(account_id,tx_id,app_id,nonce,expires_at) VALUES(?1,?2,?3,?4,?5)"
	var value_2 zir_773b400a7b2b4942_ExecResult = SignedTx_Insert(database, context, value_1, tx.AccountID, tx.TxID, tx.AppID, tx.Nonce, int64(tx.ExpiresAt))
	inserted := value_2
	var value_3 bool = inserted.Error != nil
	var value_4 bool = value_3
	if value_4 {
		var value_5 bool = strings.Contains(StdErrorsGo_Message(inserted.Error), "UNIQUE")
		value_4 = value_5
	}
	if value_4 {
		return replay
	}
	return inserted.Error
}

func SignedTx_Forget(database *Database, context Context, tx SignedTxEnvelope) {
	var value_0 string = "DELETE FROM server_signed_transactions WHERE account_id=?1 AND tx_id=?2 AND app_id=?3 AND nonce=?4"
	SignedTx_Delete(database, context, value_0, tx.AccountID, tx.TxID, tx.AppID, tx.Nonce)
}
