// Code generated by zi2go from startup.zi. DO NOT EDIT.
package main

import (
	log "log"
	slog "log/slog"
	net "net"
	http "net/http"
	os "os"
	signal "os/signal"
	strings "strings"
	sync "sync"
	syscall "syscall"
)

// #import std_go_types
type HTTPServer = http.Server

type WorkerGroup = sync.WaitGroup

type Worker func(*Server, Context)

type Workers struct {
	Invoices  Worker
	Mesh      Worker
	Discovery Worker
}

type VerifierFactory func() VerifierResult

type Listen func(*HTTPServer) Error

type Shutdown func(*HTTPServer, Context) Error

type Signal = os.Signal

type Logger = log.Logger

type zir_c4d9a008fd698927_CancelCallback func(CancelFunc)

type CloseCallback func(*Store)

type WorkerTask struct {
	Group    *WorkerGroup
	Callback Worker
	Server   *Server
	Context  Context
}

type ShutdownTask struct {
	Server   *HTTPServer
	Context  Context
	Shutdown Shutdown
}

type WorkerCallback func(WorkerTask)

type ShutdownCallback func(ShutdownTask)

func Startup_Arguments() []string {
	return os.Args
}

func Startup_Interrupt() Signal {
	return os.Interrupt
}

func Startup_Terminate() Signal {
	return syscall.SIGTERM
}

func Startup_NotifyContext(Parent Context, Interrupt Signal, Terminate Signal) Cancellation {
	var result Cancellation
	result.Value, result.Cancel = signal.NotifyContext(Parent, Interrupt, Terminate)
	return result
}

func Startup_CancelAtReturn(Callback zir_c4d9a008fd698927_CancelCallback, Cancel CancelFunc) {
	Callback(Cancel)
}

func Startup_CloseAtReturn(Callback CloseCallback, Store *Store) {
	Callback(Store)
}

func Startup_SpawnWorker(Callback WorkerCallback, Task WorkerTask) {
	go Callback(Task)
}

func Startup_SpawnShutdown(Callback ShutdownCallback, Task ShutdownTask) {
	go Callback(Task)
}

func Startup_SetAddress(Server *HTTPServer, Address string) {
	Server.Addr = Address
}

func Startup_SetHandler(Server *HTTPServer, Handler Handler) {
	Server.Handler = Handler
}

func Startup_SetReadHeaderTimeout(Server *HTTPServer, Duration Duration) {
	Server.ReadHeaderTimeout = Duration
}

func Startup_SetReadTimeout(Server *HTTPServer, Duration Duration) {
	Server.ReadTimeout = Duration
}

func Startup_SetWriteTimeout(Server *HTTPServer, Duration Duration) {
	Server.WriteTimeout = Duration
}

func Startup_SetIdleTimeout(Server *HTTPServer, Duration Duration) {
	Server.IdleTimeout = Duration
}

func Startup_SetErrorLog(Server *HTTPServer, Logger *Logger) {
	Server.ErrorLog = Logger
}

func Startup_StandardError() Writer {
	return os.Stderr
}

func Startup_StandardLogFlags() int {
	return log.LstdFlags
}

func Startup_ServerClosed() Error {
	return http.ErrServerClosed
}

const zir_d_2f7872f771b12738 = 60000000000
const Second = 1000000000

func Startup_CloseStore(store *Store) {
	Store_Close(store)
}

func Startup_RunWorker(task WorkerTask) {
	defer (*sync.WaitGroup).Done(task.Group)
	var value_0 Worker = task.Callback
	value_0(task.Server, task.Context)
}

func Startup_StartWorker(group *WorkerGroup, callback Worker, server *Server, context Context) {
	var task WorkerTask = WorkerTask{}
	task.Group = group
	task.Callback = callback
	task.Server = server
	task.Context = context
	(*sync.WaitGroup).Add(group, int(int(1)))
	Startup_SpawnWorker(func(value_0 WorkerTask) { Startup_RunWorker(value_0) }, task)
}

func Startup_RunShutdown(task ShutdownTask) {
	Startup_ShutdownOnCancel(task.Server, task.Context, task.Shutdown)
}

func Startup_ListenNative(server *HTTPServer) Error {
	return (*http.Server).ListenAndServe(server)
}

func Startup_ShutdownNative(server *HTTPServer, context Context) Error {
	return (*http.Server).Shutdown(server, context)
}

func Startup_RunInvoices(server *Server, context Context) {
	MoneroInvoices_Run(Server_Monero(server), context, Duration(60000000000))
}

func Startup_RunMesh(server *Server, context Context) {
	Mesh_Run(Server_Mesh(server), context)
}

func Startup_RunDiscovery(server *Server, context Context) {
	var value_6 RegisterService = func(value_0 string, value_1 string, value_2 string, value_3 int, value_4 []string, value_5 []Interface) RegistrationResult {
		return Discovery_Register(value_0, value_1, value_2, value_3, value_4, value_5)
	}
	Discovery_Run(&(server.Cfg), &(server.Node), context, value_6, func(value_7 *Advertiser) { Discovery_Shutdown(value_7) })
}

func Startup_LocalHTTPURL(address string) string {
	split := StdNetGo_SplitHostPort(address)
	host := split.Host
	if split.Error != nil {
		var value_0 [2]string
		value_0[0] = "http://"
		value_0[1] = address
		parts := value_0
		_ = parts
		return strings.Join(parts[0:2:2], "")
	}
	if host == "" || host == "0.0.0.0" || host == "::" {
		host = "127.0.0.1"
	}
	var value_1 [2]string
	value_1[0] = "http://"
	var value_2 string = net.JoinHostPort(host, split.Port)
	value_1[1] = value_2
	parts := value_1
	_ = parts
	return strings.Join(parts[0:2:2], "")
}

func Startup_NativeWorkers() Workers {
	var result Workers = Workers{}
	var value_2 Worker = func(value_0 *Server, value_1 Context) { Startup_RunInvoices(value_0, value_1) }
	result.Invoices = value_2
	var value_5 Worker = func(value_3 *Server, value_4 Context) { Startup_RunMesh(value_3, value_4) }
	result.Mesh = value_5
	var value_8 Worker = func(value_6 *Server, value_7 Context) { Startup_RunDiscovery(value_6, value_7) }
	result.Discovery = value_8
	return result
}

func Startup_StartWorkers(server *Server, context Context, group *WorkerGroup, workers Workers) {
	var value_0 bool = server.Cfg.TokenDirectPurchasesEnabled
	var value_1 bool = value_0
	if !value_1 {
		var value_2 bool = strings.TrimSpace(server.Cfg.MoneroWalletRPCURL) != ""
		value_1 = value_2
	}
	if value_1 {
		Startup_StartWorker(group, workers.Invoices, server, context)
	}
	Startup_StartWorker(group, workers.Mesh, server, context)
	Startup_StartWorker(group, workers.Discovery, server, context)
}

func Startup_NewHTTPServer(address string, handler Handler) *HTTPServer {
	server := new(HTTPServer)
	Startup_SetAddress(server, address)
	Startup_SetHandler(server, handler)
	Startup_SetReadHeaderTimeout(server, Duration(5000000000))
	Startup_SetReadTimeout(server, Duration(15000000000))
	Startup_SetWriteTimeout(server, Duration(15000000000))
	Startup_SetIdleTimeout(server, Duration(60000000000))
	Startup_SetErrorLog(server, log.New(Startup_StandardError(), "http: ", int(Startup_StandardLogFlags())))
	return server
}

func Startup_ShutdownOnCancel(server *HTTPServer, context Context, shutdown Shutdown) {
	var cases [1]Case
	var value_0 Case = StdSelectGo_Receive(StdContextGo_Done(context))
	cases[0] = value_0
	StdSelectGo_Select(cases[0:1:1])
	deadline := StdContextGo_WithTimeout(StdContextGo_Background(), Duration(15000000000))
	var value_2 zir_c4d9a008fd698927_CancelCallback = func(value_1 CancelFunc) { StdContextGo_Cancel(value_1) }
	defer Startup_CancelAtReturn(value_2, deadline.Cancel)
	var value_3 Shutdown = shutdown
	error := value_3(server, deadline.Value)
	if error != nil {
		slog.Error("HTTP shutdown failed", "error", error)
	}
}

func Startup_Serve(server *HTTPServer, configuration Config, context Context, stop CancelFunc, group *WorkerGroup, listen Listen, shutdown Shutdown) {
	var task ShutdownTask = ShutdownTask{}
	task.Server = server
	task.Context = context
	task.Shutdown = shutdown
	Startup_SpawnShutdown(func(value_0 ShutdownTask) { Startup_RunShutdown(value_0) }, task)
	slog.Info("Daochi sync server listening", "url", Startup_LocalHTTPURL(configuration.Addr), "addr", configuration.Addr, "base_url", configuration.BaseURL, "db", configuration.DBPath)
	var value_1 Listen = listen
	error := value_1(server)
	var value_2 bool = error != nil
	var value_3 bool = value_2
	if value_3 {
		var value_4 bool = error != Startup_ServerClosed()
		value_3 = value_4
	}
	if value_3 {
		slog.Error("serve failed", "error", error)
	}
	StdContextGo_Cancel(stop)
	(*sync.WaitGroup).Wait(group)
}

func Startup_WithNodeKey(configuration Config) Config {
	privateKey := []uint8(configuration.NodeIdentityPrivateKey)
	if int64(len(privateKey)) == 0 {
		key := NodeIdentity_LoadOrCreateKey(configuration.NodeIdentityKeyFile)
		if key.Error != nil {
			log.Fatalf("load node identity: %v", key.Error)
		}
		configuration.NodeIdentityPrivateKey = key.Value
	}
	return configuration
}

func Startup_RunPrepared(configuration Config, arguments []string, createVerifier VerifierFactory, signer SignPrivateKey) {
	if int64(len(arguments)) > 1 && arguments[1] == "inspect" {
		var options InspectOptions = InspectOptions{}
		options.DBPath = configuration.DBPath
		var value_0 Context = StdContextGo_Background()
		if int64(2) < 0 || int64(int64(len(arguments))) < int64(2) || int64(int64(len(arguments))) > int64(len(arguments)) {
			panic("slice range out of bounds")
		}
		error := Inspect_Run(value_0, arguments[2:int64(len(arguments)):int64(len(arguments))], options)
		if error != nil {
			log.Fatalf("inspect: %v", error)
		}
		return
	}
	opened := Store_Open(configuration.DBPath)
	if opened.Error != nil {
		log.Fatalf("open store: %v", opened.Error)
	}
	store := opened.Value
	var value_3 CloseCallback = func(value_2 *Store) { Startup_CloseStore(value_2) }
	defer Startup_CloseAtReturn(value_3, store)
	var value_4 VerifierFactory = createVerifier
	verifier := value_4()
	if verifier.Error != nil {
		if StdErrorsGo_Is(verifier.Error, ErrVerifierUnavailable) {
			log.Fatal("ML-DSA-44 verifier unavailable: build with CGO_ENABLED=1 and liboqs installed")
		}
		log.Fatalf("create verifier: %v", verifier.Error)
	}
	server := Server_New(configuration, store, verifier.Value, signer)
	runtime := Startup_NotifyContext(StdContextGo_Background(), Startup_Interrupt(), Startup_Terminate())
	var value_6 zir_c4d9a008fd698927_CancelCallback = func(value_5 CancelFunc) { StdContextGo_Cancel(value_5) }
	defer Startup_CancelAtReturn(value_6, runtime.Cancel)
	var group WorkerGroup = *new(WorkerGroup)
	var value_7 *Server = server
	var value_8 Context = runtime.Value
	Startup_StartWorkers(value_7, value_8, &(group), Startup_NativeWorkers())
	var value_9 string = configuration.Addr
	http := Startup_NewHTTPServer(value_9, Server_Routes(server))
	var value_11 Listen = func(value_10 *HTTPServer) Error { return Startup_ListenNative(value_10) }
	var value_14 Shutdown = func(value_12 *HTTPServer, value_13 Context) Error { return Startup_ShutdownNative(value_12, value_13) }
	Startup_Serve(http, configuration, runtime.Value, runtime.Cancel, &(group), value_11, value_14)
}

func Startup_Run(configuration Config, arguments []string, createVerifier VerifierFactory, signer SignPrivateKey) {
	Startup_RunPrepared(Startup_WithNodeKey(configuration), arguments, createVerifier, signer)
}

func Startup_Main(createVerifier VerifierFactory, signer SignPrivateKey) {
	configuration := Startup_WithNodeKey(Config_Load())
	Startup_RunPrepared(configuration, Startup_Arguments(), createVerifier, signer)
}

var Startup_ziranInitState uint8

func Startup_ziranInit() {
	if Startup_ziranInitState == 2 {
		return
	}
	if Startup_ziranInitState == 1 {
		panic("cyclic module startup")
	}
	Startup_ziranInitState = 1
	Store_ziranInit()
	Verifier_ziranInit()
	Server_ziranInit()
	Startup_ziranInitState = 2
}
