// Code generated by zi2go from std_time_go.zi. DO NOT EDIT.
package main

import time "time"

// #import std_go_types
type Time = time.Time

type Duration = time.Duration

type ParseResult struct {
	Value Time
	Error Error
}

func StdTimeGo_ParseRaw(Layout string, Value string) ParseResult {
	var result ParseResult
	result.Value, result.Error = time.Parse(Layout, Value)
	return result
}

func StdTimeGo_Now() Time {
	return time.Now()
}

func StdTimeGo_After(value Time, other Time) bool {
	return (time.Time).After(value, other)
}

func StdTimeGo_Add(value Time, duration Duration) Time {
	return (time.Time).Add(value, duration)
}

func StdTimeGo_Parse(layout string, value string) ParseResult {
	return StdTimeGo_ParseRaw(layout, value)
}

func StdTimeGo_UTC(value Time) Time {
	return (time.Time).UTC(value)
}

func StdTimeGo_Format(value Time, layout string) string {
	return (time.Time).Format(value, layout)
}

func StdTimeGo_Unix(value Time) int64 {
	return (time.Time).Unix(value)
}

func StdTimeGo_FromUnix(seconds int64, nanos int64) Time {
	return time.Unix(int64(seconds), int64(nanos))
}

func StdTimeGo_Until(value Time) Duration {
	return time.Until(value)
}
