// Code generated by zi2go from std_context_go.zi. DO NOT EDIT.
package main

import (
	context "context"
	reflect "reflect"
)

// #import std_go_types
type Context = context.Context

type CancelFunc = context.CancelFunc

type Cancellation struct {
	Value  Context
	Cancel CancelFunc
}

type FunctionValue = reflect.Value

func StdContextGo_CanceledRaw() Error {
	return context.Canceled
}

func StdContextGo_DeadlineExceededRaw() Error {
	return context.DeadlineExceeded
}

func StdContextGo_WithCancelRaw(Value Context) Cancellation {
	var result Cancellation
	result.Value, result.Cancel = context.WithCancel(Value)
	return result
}

func StdContextGo_WithTimeoutRaw(Value Context, Duration Duration) Cancellation {
	var result Cancellation
	result.Value, result.Cancel = context.WithTimeout(Value, Duration)
	return result
}

func StdContextGo_Background() Context {
	return context.Background()
}

func StdContextGo_Canceled() Error {
	return StdContextGo_CanceledRaw()
}

func StdContextGo_DeadlineExceeded() Error {
	return StdContextGo_DeadlineExceededRaw()
}

func StdContextGo_Done(value Context) Any {
	return (context.Context).Done(value)
}

func StdContextGo_WithCancel(value Context) Cancellation {
	return StdContextGo_WithCancelRaw(value)
}

func StdContextGo_WithTimeout(value Context, duration Duration) Cancellation {
	return StdContextGo_WithTimeoutRaw(value, duration)
}

func StdContextGo_Cancel(callback CancelFunc) {
	var arguments []FunctionValue = nil
	(reflect.Value).Call(reflect.ValueOf(callback), arguments)
}
