// Code generated by zi2go from store.zi. DO NOT EDIT.
package main

// #import std_go_types
// #import protocol
// #import sync_types
// #import types
type Store struct {
	Database *Database
	Path     string
}

type StoreResult struct {
	Value *Store
	Error Error
}

type Results__SyncResult__Error struct {
	Value0 SyncResult
	Value1 Error
}

type Results__SyncResult__a_string__Error struct {
	Value0 SyncResult
	Value1 []string
	Value2 Error
}

type Results__string__Error struct {
	Value0 string
	Value1 Error
}

type Results__isize__Error struct {
	Value0 int
	Value1 Error
}

type Results__string__bool__Error struct {
	Value0 string
	Value1 bool
	Value2 Error
}

type Results__FriendRequest__Error struct {
	Value0 FriendRequest
	Value1 Error
}

type Results__FriendRequest__bool__Error struct {
	Value0 FriendRequest
	Value1 bool
	Value2 Error
}

type Results__a_FriendRequest__a_FriendRequest__Error struct {
	Value0 []FriendRequest
	Value1 []FriendRequest
	Value2 Error
}

type Results__a_Friend__Error struct {
	Value0 []Friend
	Value1 Error
}

type Results__a_SocialSnapshot__Error struct {
	Value0 []SocialSnapshot
	Value1 Error
}

type Results__a_FriendStatRow__Error struct {
	Value0 []FriendStatRow
	Value1 Error
}

type Results__s64__Error struct {
	Value0 int64
	Value1 Error
}

type Results__a_EncryptedPayload__bool__Error struct {
	Value0 []EncryptedPayload
	Value1 bool
	Value2 Error
}

type Results__a_EncryptedPayload__Error struct {
	Value0 []EncryptedPayload
	Value1 Error
}

type Results__payloads_EncryptedPayloadPruneResult__Error struct {
	Value0 EncryptedPayloadPruneResult
	Value1 Error
}

type Results__a_SyncAuditEntry__Error struct {
	Value0 []SyncAuditEntry
	Value1 Error
}

type Results__bool__s64__Error struct {
	Value0 bool
	Value1 int64
	Value2 Error
}

type Results__PublicStats__Error struct {
	Value0 PublicStats
	Value1 Error
}

type Results__SyncChanges__s64__Error struct {
	Value0 SyncChanges
	Value1 int64
	Value2 Error
}

type Results__a_SyncOp__Error struct {
	Value0 []SyncOp
	Value1 Error
}

type Results__pCleanData__Error struct {
	Value0 *CleanData
	Value1 Error
}

type Results__a_SyncLog__Error struct {
	Value0 []SyncLog
	Value1 Error
}

type Results__a_string__Error struct {
	Value0 []string
	Value1 Error
}

type Results__NodeUsage__Error struct {
	Value0 NodeUsage
	Value1 Error
}

type Results__NodeStorageUsage__Error struct {
	Value0 NodeStorageUsage
	Value1 Error
}

type Results__SyncDiagnosticReport__Error struct {
	Value0 SyncDiagnosticReport
	Value1 Error
}

var ErrSyncUserNotFound Error

func Store_Open(path string) StoreResult {
	openedStore := StoreOpen_Open(path)
	var result StoreResult = StoreResult{}
	if openedStore.Error != nil {
		result.Error = openedStore.Error
		return result
	}
	var value_0 *Store = new(Store)
	result.Value = value_0
	result.Value.Database = openedStore.Value
	result.Value.Path = path
	return result
}

func Store_Close(store *Store) Error {
	return StoreOpen_Close(store.Database)
}

func (receiver *Store) Close() Error {
	return Store_Close(receiver)
}

func Store_ApplySync(store *Store, context Context, req SyncRequest, publicKey []uint8) Results__SyncResult__Error {
	results_1_ := Store_ApplySyncDetailed(store, context, req, publicKey)
	result := results_1_.Value0
	err := results_1_.Value2
	return Results__SyncResult__Error{Value0: result, Value1: err}
}

func (receiver *Store) ApplySync(argument1 Context, argument2 SyncRequest, argument3 []uint8) (SyncResult, Error) {
	result := Store_ApplySync(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1
}

func Store_ApplySyncDetailed(store *Store, context Context, req SyncRequest, publicKey []uint8) Results__SyncResult__a_string__Error {
	result := SyncApplication_Apply(store.Database, context, req, publicKey, ErrSyncUserNotFound)
	var value_3 Results__SyncResult__a_string__Error = Results__SyncResult__a_string__Error{Value0: result.Value, Value1: result.Accepted, Value2: result.Error}
	return value_3
}

func (receiver *Store) ApplySyncDetailed(argument1 Context, argument2 SyncRequest, argument3 []uint8) (SyncResult, []string, Error) {
	result := Store_ApplySyncDetailed(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1, result.Value2
}

func Store_RegisterUser(store *Store, context Context, userID string, publicKey []uint8) Error {
	return AccountState_Register(store.Database, context, userID, publicKey)
}

func (receiver *Store) RegisterUser(argument1 Context, argument2 string, argument3 []uint8) Error {
	return Store_RegisterUser(receiver, argument1, argument2, argument3)
}

func Store_AccountAlias(store *Store, context Context, userID string) Results__string__Error {
	result := AccountProfile_Alias(store.Database, context, userID)
	return Results__string__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) AccountAlias(argument1 Context, argument2 string) (string, Error) {
	result := Store_AccountAlias(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Store_SetAccountAlias(store *Store, context Context, userID string, alias string) Error {
	return AccountProfile_SetAlias(store.Database, context, userID, alias, ErrSyncUserNotFound)
}

func (receiver *Store) SetAccountAlias(argument1 Context, argument2 string, argument3 string) Error {
	return Store_SetAccountAlias(receiver, argument1, argument2, argument3)
}

func Store_AccountProfileIcon(store *Store, context Context, userID string) Results__isize__Error {
	result := AccountProfile_Icon(store.Database, context, userID)
	return Results__isize__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) AccountProfileIcon(argument1 Context, argument2 string) (int, Error) {
	result := Store_AccountProfileIcon(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Store_SetAccountProfileIcon(store *Store, context Context, userID string, profileIcon int) Error {
	return AccountProfile_SetIcon(store.Database, context, userID, profileIcon, ErrSyncUserNotFound)
}

func (receiver *Store) SetAccountProfileIcon(argument1 Context, argument2 string, argument3 int) Error {
	return Store_SetAccountProfileIcon(receiver, argument1, argument2, argument3)
}

func Store_ResolveAccountRef(store *Store, context Context, ref string) Results__string__bool__Error {
	result := AccountLookup_Resolve(store.Database, context, ref)
	return Results__string__bool__Error{Value0: result.Value, Value1: result.Found, Value2: result.Error}
}

func (receiver *Store) ResolveAccountRef(argument1 Context, argument2 string) (string, bool, Error) {
	result := Store_ResolveAccountRef(receiver, argument1, argument2)
	return result.Value0, result.Value1, result.Value2
}

func Store_CreateFriendRequest(store *Store, context Context, id string, requester string, target string) Results__FriendRequest__Error {
	result := FriendStore_CreateRequest(store.Database, context, id, requester, target)
	return Results__FriendRequest__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) CreateFriendRequest(argument1 Context, argument2 string, argument3 string, argument4 string) (FriendRequest, Error) {
	result := Store_CreateFriendRequest(receiver, argument1, argument2, argument3, argument4)
	return result.Value0, result.Value1
}

func Store_FriendRequest(store *Store, context Context, id string) Results__FriendRequest__bool__Error {
	result := FriendStore_Request(store.Database, context, id)
	var value_3 Results__FriendRequest__bool__Error = Results__FriendRequest__bool__Error{Value0: result.Value, Value1: result.Found, Value2: result.Error}
	return value_3
}

func (receiver *Store) FriendRequest(argument1 Context, argument2 string) (FriendRequest, bool, Error) {
	result := Store_FriendRequest(receiver, argument1, argument2)
	return result.Value0, result.Value1, result.Value2
}

func Store_ListFriendRequests(store *Store, context Context, userID string) Results__a_FriendRequest__a_FriendRequest__Error {
	result := FriendStore_Requests(store.Database, context, userID)
	var value_3 Results__a_FriendRequest__a_FriendRequest__Error = Results__a_FriendRequest__a_FriendRequest__Error{Value0: result.Incoming, Value1: result.Outgoing, Value2: result.Error}
	return value_3
}

func (receiver *Store) ListFriendRequests(argument1 Context, argument2 string) ([]FriendRequest, []FriendRequest, Error) {
	result := Store_ListFriendRequests(receiver, argument1, argument2)
	return result.Value0, result.Value1, result.Value2
}

func Store_AcceptFriendRequest(store *Store, context Context, userID string, id string) Results__FriendRequest__Error {
	result := FriendStore_Accept(store.Database, context, userID, id, ErrSyncUserNotFound)
	return Results__FriendRequest__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) AcceptFriendRequest(argument1 Context, argument2 string, argument3 string) (FriendRequest, Error) {
	result := Store_AcceptFriendRequest(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1
}

func Store_DeclineFriendRequest(store *Store, context Context, userID string, id string) Results__FriendRequest__Error {
	result := FriendStore_Decline(store.Database, context, userID, id, ErrSyncUserNotFound)
	return Results__FriendRequest__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) DeclineFriendRequest(argument1 Context, argument2 string, argument3 string) (FriendRequest, Error) {
	result := Store_DeclineFriendRequest(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1
}

func Store_ListFriends(store *Store, context Context, userID string) Results__a_Friend__Error {
	result := FriendStore_Friends(store.Database, context, userID)
	return Results__a_Friend__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) ListFriends(argument1 Context, argument2 string) ([]Friend, Error) {
	result := Store_ListFriends(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Store_AuthoritativeSocial(store *Store, context Context, userID string) Results__a_SocialSnapshot__Error {
	result := FriendStore_Authoritative(store.Database, context, userID)
	return Results__a_SocialSnapshot__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) AuthoritativeSocial(argument1 Context, argument2 string) ([]SocialSnapshot, Error) {
	result := Store_AuthoritativeSocial(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Store_RemoveFriend(store *Store, context Context, userID string, friendID string) Error {
	return FriendStore_Remove(store.Database, context, userID, friendID)
}

func (receiver *Store) RemoveFriend(argument1 Context, argument2 string, argument3 string) Error {
	return Store_RemoveFriend(receiver, argument1, argument2, argument3)
}

func Store_UpsertProfileStats(store *Store, context Context, userID string, app string, metrics []ProfileMetric) Results__isize__Error {
	result := FriendStore_UpsertStats(store.Database, context, userID, app, metrics)
	return Results__isize__Error{Value0: result.Applied, Value1: result.Error}
}

func (receiver *Store) UpsertProfileStats(argument1 Context, argument2 string, argument3 string, argument4 []ProfileMetric) (int, Error) {
	result := Store_UpsertProfileStats(receiver, argument1, argument2, argument3, argument4)
	return result.Value0, result.Value1
}

func Store_FriendStats(store *Store, context Context, userID string, app string, practice string, metric string) Results__a_FriendStatRow__Error {
	result := Leaderboard_Friends(store.Database, context, userID, app, practice, metric)
	return Results__a_FriendStatRow__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) FriendStats(argument1 Context, argument2 string, argument3 string, argument4 string, argument5 string) ([]FriendStatRow, Error) {
	result := Store_FriendStats(receiver, argument1, argument2, argument3, argument4, argument5)
	return result.Value0, result.Value1
}

func Store_RecordClientLogin(store *Store, context Context, userID string, clientID string) Error {
	return SyncClients_RecordLogin(store.Database, context, userID, clientID)
}

func (receiver *Store) RecordClientLogin(argument1 Context, argument2 string, argument3 string) Error {
	return Store_RecordClientLogin(receiver, argument1, argument2, argument3)
}

func Store_RecordClientSync(store *Store, context Context, userID string, clientID string, sinceVersion int64, serverVersion int64, protocolVersion int, clientClock int64) Error {
	var value_0 Error = SyncClients_RecordSync(store.Database, context, userID, clientID, sinceVersion, serverVersion, protocolVersion, clientClock)
	return value_0
}

func (receiver *Store) RecordClientSync(argument1 Context, argument2 string, argument3 string, argument4 int64, argument5 int64, argument6 int, argument7 int64) Error {
	return Store_RecordClientSync(receiver, argument1, argument2, argument3, argument4, argument5, argument6, argument7)
}

func Store_StoreEncryptedPayload(store *Store, context Context, userID string, clientID string, payload []uint8) Results__s64__Error {
	result := EncryptedPayloads_Store(store.Database, context, userID, clientID, payload, ErrSyncUserNotFound)
	return Results__s64__Error{Value0: result.Version, Value1: result.Error}
}

func (receiver *Store) StoreEncryptedPayload(argument1 Context, argument2 string, argument3 string, argument4 []uint8) (int64, Error) {
	result := Store_StoreEncryptedPayload(receiver, argument1, argument2, argument3, argument4)
	return result.Value0, result.Value1
}

func Store_EncryptedPayloadsSince(store *Store, context Context, userID string, sinceVersion int64, limit int) Results__a_EncryptedPayload__bool__Error {
	result := EncryptedPayloads_Since(store.Database, context, userID, sinceVersion, limit)
	var value_3 Results__a_EncryptedPayload__bool__Error = Results__a_EncryptedPayload__bool__Error{Value0: result.Value, Value1: result.Truncated, Value2: result.Error}
	return value_3
}

func (receiver *Store) EncryptedPayloadsSince(argument1 Context, argument2 string, argument3 int64, argument4 int) ([]EncryptedPayload, bool, Error) {
	result := Store_EncryptedPayloadsSince(receiver, argument1, argument2, argument3, argument4)
	return result.Value0, result.Value1, result.Value2
}

func Store_RecentEncryptedPayloads(store *Store, context Context, userID string, limit int) Results__a_EncryptedPayload__Error {
	result := EncryptedPayloads_Recent(store.Database, context, userID, limit)
	return Results__a_EncryptedPayload__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) RecentEncryptedPayloads(argument1 Context, argument2 string, argument3 int) ([]EncryptedPayload, Error) {
	result := Store_RecentEncryptedPayloads(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1
}

func Store_EncryptedPayloadBytes(store *Store, context Context, userID string) Results__s64__Error {
	result := EncryptedPayloads_Bytes(store.Database, context, userID)
	return Results__s64__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) EncryptedPayloadBytes(argument1 Context, argument2 string) (int64, Error) {
	result := Store_EncryptedPayloadBytes(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Store_PruneEncryptedPayloads(store *Store, context Context, userID string, maxAge Duration, maxBytes int64) Results__payloads_EncryptedPayloadPruneResult__Error {
	result := EncryptedPayloads_Prune(store.Database, context, userID, maxAge, maxBytes)
	return Results__payloads_EncryptedPayloadPruneResult__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) PruneEncryptedPayloads(argument1 Context, argument2 string, argument3 Duration, argument4 int64) (EncryptedPayloadPruneResult, Error) {
	result := Store_PruneEncryptedPayloads(receiver, argument1, argument2, argument3, argument4)
	return result.Value0, result.Value1
}

func Store_RecordSyncAudit(store *Store, context Context, entry SyncAuditEntry) Error {
	return SyncAudit_Record(store.Database, context, entry)
}

func (receiver *Store) RecordSyncAudit(argument1 Context, argument2 SyncAuditEntry) Error {
	return Store_RecordSyncAudit(receiver, argument1, argument2)
}

func Store_RecentSyncAudit(store *Store, context Context, userID string, limit int) Results__a_SyncAuditEntry__Error {
	result := SyncAudit_Recent(store.Database, context, userID, limit)
	return Results__a_SyncAuditEntry__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) RecentSyncAudit(argument1 Context, argument2 string, argument3 int) ([]SyncAuditEntry, Error) {
	result := Store_RecentSyncAudit(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1
}

func Store_SyncOpsCompacted(store *Store, context Context, userID string, clientClock int64) Results__bool__s64__Error {
	result := SyncClients_Compacted(store.Database, context, userID, clientClock)
	var value_3 Results__bool__s64__Error = Results__bool__s64__Error{Value0: result.Compacted, Value1: result.Through, Value2: result.Error}
	return value_3
}

func (receiver *Store) SyncOpsCompacted(argument1 Context, argument2 string, argument3 int64) (bool, int64, Error) {
	result := Store_SyncOpsCompacted(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1, result.Value2
}

func Store_CompactSyncOps(store *Store, context Context, userID string) Error {
	return SyncClients_Compact(store.Database, context, userID)
}

func (receiver *Store) CompactSyncOps(argument1 Context, argument2 string) Error {
	return Store_CompactSyncOps(receiver, argument1, argument2)
}

func Store_DeleteAccount(store *Store, context Context, userID string) Error {
	return AccountState_Delete(store.Database, context, userID)
}

func (receiver *Store) DeleteAccount(argument1 Context, argument2 string) Error {
	return Store_DeleteAccount(receiver, argument1, argument2)
}

func Store_PublicStats(store *Store, context Context, dbPath string) Results__PublicStats__Error {
	result := StoreStats_Public(store.Database, context, dbPath)
	return Results__PublicStats__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) PublicStats(argument1 Context, argument2 string) (PublicStats, Error) {
	result := Store_PublicStats(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Store_ChangesSince(store *Store, context Context, userID string, sinceVersion int64) Results__SyncChanges__s64__Error {
	result := SyncViews_Changes(store.Database, context, userID, sinceVersion)
	var value_3 Results__SyncChanges__s64__Error = Results__SyncChanges__s64__Error{Value0: result.Value, Value1: result.Version, Value2: result.Error}
	return value_3
}

func (receiver *Store) ChangesSince(argument1 Context, argument2 string, argument3 int64) (SyncChanges, int64, Error) {
	result := Store_ChangesSince(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1, result.Value2
}

func Store_OpsSince(store *Store, context Context, userID string, sinceVersion int64) Results__a_SyncOp__Error {
	result := SyncViews_OperationsSince(store.Database, context, userID, sinceVersion)
	return Results__a_SyncOp__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) OpsSince(argument1 Context, argument2 string, argument3 int64) ([]SyncOp, Error) {
	result := Store_OpsSince(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1
}

func Store_CleanData(store *Store, context Context, userID string) Results__pCleanData__Error {
	result := SyncViews_Clean(store.Database, context, userID)
	return Results__pCleanData__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) CleanData(argument1 Context, argument2 string) (*CleanData, Error) {
	result := Store_CleanData(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Store_SyncLogs(store *Store, context Context, userID string, sinceVersion int64) Results__a_SyncLog__Error {
	result := SyncAudit_Logs(store.Database, context, userID, sinceVersion)
	return Results__a_SyncLog__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) SyncLogs(argument1 Context, argument2 string, argument3 int64) ([]SyncLog, Error) {
	result := Store_SyncLogs(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1
}

func Store_DeleteLogs(store *Store, context Context, userID string, sinceVersion int64) Results__a_SyncLog__Error {
	result := SyncAudit_Deletes(store.Database, context, userID, sinceVersion)
	return Results__a_SyncLog__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) DeleteLogs(argument1 Context, argument2 string, argument3 int64) ([]SyncLog, Error) {
	result := Store_DeleteLogs(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1
}

func Store_LegacyClients(store *Store, context Context, userID string, minProtocol int) Results__a_string__Error {
	result := SyncClients_Legacy(store.Database, context, userID, minProtocol)
	return Results__a_string__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) LegacyClients(argument1 Context, argument2 string, argument3 int) ([]string, Error) {
	result := Store_LegacyClients(receiver, argument1, argument2, argument3)
	return result.Value0, result.Value1
}

func Store_LegacyWritePolicy(store *Store, context Context, userID string) Results__bool__s64__Error {
	result := SyncClients_LegacyWritePolicy(store.Database, context, userID)
	return Results__bool__s64__Error{Value0: result.Required, Value1: result.Epoch, Value2: result.Error}
}

func (receiver *Store) LegacyWritePolicy(argument1 Context, argument2 string) (bool, int64, Error) {
	result := Store_LegacyWritePolicy(receiver, argument1, argument2)
	return result.Value0, result.Value1, result.Value2
}

func Store_CleanupOrphanHabitDays(store *Store, context Context, userID string) Error {
	return HabitMigration_Cleanup(store.Database, context, userID)
}

func (receiver *Store) CleanupOrphanHabitDays(argument1 Context, argument2 string) Error {
	return Store_CleanupOrphanHabitDays(receiver, argument1, argument2)
}

func Store_AutoMigrateAccountForProtocol(store *Store, context Context, userID string, protocol int) Error {
	return HabitMigration_ForProtocol(store.Database, context, userID, protocol)
}

func (receiver *Store) AutoMigrateAccountForProtocol(argument1 Context, argument2 string, argument3 int) Error {
	return Store_AutoMigrateAccountForProtocol(receiver, argument1, argument2, argument3)
}

func Store_AutoMigrateAllAccounts(store *Store, context Context) Error {
	return HabitMigration_AllAccounts(store.Database, context)
}

func (receiver *Store) AutoMigrateAllAccounts(argument1 Context) Error {
	return Store_AutoMigrateAllAccounts(receiver, argument1)
}

func Store_StateHash(store *Store, context Context, userID string) Results__string__Error {
	result := StateHash_State(store.Database, context, userID)
	return Results__string__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) StateHash(argument1 Context, argument2 string) (string, Error) {
	result := Store_StateHash(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Store_SetSocialCacheJSON(store *Store, context Context, userID string, kind string, payload []uint8) Results__isize__Error {
	result := SocialCache_Set(store.Database, context, userID, kind, payload)
	return Results__isize__Error{Value0: result.Applied, Value1: result.Error}
}

func (receiver *Store) SetSocialCacheJSON(argument1 Context, argument2 string, argument3 string, argument4 []uint8) (int, Error) {
	result := Store_SetSocialCacheJSON(receiver, argument1, argument2, argument3, argument4)
	return result.Value0, result.Value1
}

func Store_CurrentVersion(store *Store, context Context, userID string) Results__s64__Error {
	result := AccountState_CurrentVersion(store.Database, context, userID)
	return Results__s64__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) currentUserVersion(argument1 Context, argument2 string) (int64, Error) {
	result := Store_CurrentVersion(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Store_Health(store *Store, context Context) Error {
	return StoreDiagnostics_Health(store.Database, context)
}

func (receiver *Store) Health(argument1 Context) Error {
	return Store_Health(receiver, argument1)
}

func Store_NodeUsage(store *Store, context Context, now Time) Results__NodeUsage__Error {
	result := StoreStats_Usage(store.Database, context, now)
	return Results__NodeUsage__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) NodeUsage(argument1 Context, argument2 Time) (NodeUsage, Error) {
	result := Store_NodeUsage(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Store_NodeStorageUsage(store *Store, context Context) Results__NodeStorageUsage__Error {
	result := StoreStats_Storage(store.Database, context, store.Path)
	return Results__NodeStorageUsage__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) NodeStorageUsage(argument1 Context) (NodeStorageUsage, Error) {
	result := Store_NodeStorageUsage(receiver, argument1)
	return result.Value0, result.Value1
}

func Store_SyncDiagnosticReport(store *Store, context Context, userID string) Results__SyncDiagnosticReport__Error {
	result := StoreDiagnostics_Report(store.Database, context, userID)
	return Results__SyncDiagnosticReport__Error{Value0: result.Value, Value1: result.Error}
}

func (receiver *Store) SyncDiagnosticReport(argument1 Context, argument2 string) (SyncDiagnosticReport, Error) {
	result := Store_SyncDiagnosticReport(receiver, argument1, argument2)
	return result.Value0, result.Value1
}

func Store_GlobalInit00() {
	ErrSyncUserNotFound = StdErrorsGo_New("sync user not found")
}

var Store_ziranInitState uint8

func Store_ziranInit() {
	if Store_ziranInitState == 2 {
		return
	}
	if Store_ziranInitState == 1 {
		panic("cyclic module startup")
	}
	Store_ziranInitState = 1
	Store_GlobalInit00()
	Store_ziranInitState = 2
}

func init() { Store_ziranInit() }
