// Code generated by zi2go from sync_ws.zi. DO NOT EDIT.
package main

import (
	sql "database/sql"
	net "net"
	reflect "reflect"
	time "time"
)

// #import std_go_types
// #import config
// #import metrics
// #import sync_hub
type SyncSocket struct {
	Database      *Database
	Configuration *Config
	Counters      *ServerMetrics
	Limiter       *RateLimiter
	Hub           *SyncHub
}

type zir_913e21b3089659fb_VersionResult struct {
	Value int64
	Error Error
}

type EventResult struct {
	Value   SyncEvent
	Present bool
}

type ReaderWorker func(Connection, *BufferedReader, CancelFunc)

type CancelCallback func(CancelFunc)

type UnsubscribeCallback func(*SyncHub, string, *Subscription)

func SyncWs_CancelAtReturn(Callback CancelCallback, Cancel CancelFunc) {
	Callback(Cancel)
}

func SyncWs_UnsubscribeAtReturn(Callback UnsubscribeCallback, Hub *SyncHub, UserID string, Subscription *Subscription) {
	Callback(Hub, UserID, Subscription)
}

func SyncWs_SpawnReader(Callback ReaderWorker, Connection Connection, Reader *BufferedReader, Cancel CancelFunc) {
	go Callback(Connection, Reader, Cancel)
}

func SyncWs_Reader(Buffer *BufferedConnection) *BufferedReader {
	return Buffer.Reader
}

func SyncWs_AsEvent(Value Any) EventResult {
	var result EventResult
	result.Value, result.Present = Value.(SyncEvent)
	return result
}

const Minute = 60000000000
const ReadWindow = 90000000000
const WriteWindow = 10000000000
const PingInterval = 30000000000

func SyncWs_Allow(value SyncSocket, key string, limit int) bool {
	if value.Limiter == nil {
		return true
	}
	allowed := RateLimit_Allow(value.Limiter, key, limit, Duration(60000000000))
	if !allowed {
		StdAtomicGo_Add(&(value.Counters.RateLimitedRequests), 1)
	}
	return allowed
}

func SyncWs_CurrentVersion(value SyncSocket, context Context, userID string) zir_913e21b3089659fb_VersionResult {
	var result zir_913e21b3089659fb_VersionResult = zir_913e21b3089659fb_VersionResult{}
	var value_0 *Row = (*sql.DB).QueryRowContext(value.Database, context, "\nSELECT server_version\nFROM server_sync_state\nWHERE user_id_hash=?1", userID)
	var value_1 Error = (*sql.Row).Scan(value_0, &(result.Value))
	result.Error = value_1
	var value_2 Error = result.Error
	if StdErrorsGo_Is(value_2, StdSqlGo_NoRows()) {
		result.Value = 0
		result.Error = nil
	}
	return result
}

func SyncWs_ReadLoop(connection Connection, reader *BufferedReader, cancel CancelFunc) {
	for true {
		(net.Conn).SetReadDeadline(connection, StdTimeGo_Add(StdTimeGo_Now(), Duration(90000000000)))
		frame := Websocket_ReadClientFrame(reader)
		if frame.Error != nil {
			StdContextGo_Cancel(cancel)
			return
		}
	}
}

func SyncWs_Authenticate(value SyncSocket, request *Request) UserAuthenticationResult {
	var result UserAuthenticationResult = UserAuthenticationResult{}
	if StdUrlGo_Value(StdUrlGo_Query(StdHttpGo_RequestURL(request)), "token") != "" {
		var value_0 AuthenticationResult = Authentication_Failure(int(401), "websocket query tokens are not accepted")
		result.Authentication = value_0
		return result
	}
	var value_1 string = Websocket_BearerToken(StdHttpGo_HeaderValue(StdHttpGo_Headers(request), "Sec-WebSocket-Protocol"))
	bearer := value_1
	if bearer != "" {
		var value_2 []uint8 = value.Configuration.TokenSecret
		verified := Token_VerifyAuthToken(value_2, bearer, StdTimeGo_Unix(StdTimeGo_Now()))
		if verified.Error != "" {
			var value_3 AuthenticationResult = Authentication_Failure(int(401), "invalid bearer token")
			result.Authentication = value_3
			return result
		}
		result.Value = verified.Value
		return result
	}
	return HttpAuth_AuthenticateToken(value.Database, request, value.Configuration.TokenSecret)
}

func SyncWs_Handle(value SyncSocket, writer ResponseWriter, request *Request) {
	if StdHttpGo_Method(request) != "GET" {
		Response_Error(writer, int(405), "method not allowed")
		return
	}
	authenticated := SyncWs_Authenticate(value, request)
	if authenticated.Authentication.Error != nil || authenticated.Authentication.Status != int(0) {
		Metrics_RecordWebSocketReject(value.Counters, "auth")
		HttpAuth_Respond(writer, value.Counters, authenticated.Authentication)
		return
	}
	userID := authenticated.Value
	var value_0 SyncSocket = value
	var value_1 bool = SyncWs_Allow(value_0, Websocket_AddText("ws:ip:", ClientAddress_FromRequest(request)), int(120))
	var value_2 bool = !value_1
	if !value_2 {
		var value_3 SyncSocket = value
		var value_4 bool = SyncWs_Allow(value_3, Websocket_AddText("ws:user:", userID), int(40))
		value_2 = !value_4
	}
	if value_2 {
		Metrics_RecordWebSocketReject(value.Counters, "rate_limited")
		Response_Error(writer, int(429), "rate limit exceeded")
		return
	}
	if SyncHub_Count(value.Hub, userID) >= 8 {
		Metrics_RecordWebSocketReject(value.Counters, "too_many_connections")
		Response_Error(writer, int(429), "too many websocket connections")
		return
	}
	accepted := Websocket_Accept(writer, request)
	if accepted.Error != nil {
		Metrics_RecordWebSocketReject(value.Counters, "handshake")
		return
	}
	StdAtomicGo_Add(&(value.Counters.WebSocketAccepted), 1)
	defer (net.Conn).Close(accepted.Connection)
	events := SyncHub_Subscribe(value.Hub, userID)
	var value_8 UnsubscribeCallback = func(value_5 *SyncHub, value_6 string, value_7 *Subscription) {
		SyncHub_Unsubscribe(value_5, value_6, value_7)
	}
	defer SyncWs_UnsubscribeAtReturn(value_8, value.Hub, userID, events)
	var value_9 SyncSocket = value
	var value_10 Context = StdHttpGo_Context(request)
	version := SyncWs_CurrentVersion(value_9, value_10, userID)
	if version.Error == nil {
		var ready SyncEvent = SyncEvent{}
		ready.Type = "sync_ready"
		ready.UserIDHash = userID
		ready.ServerVersion = version.Value
		Websocket_WriteJSON(accepted.Connection, ready)
	}
	child := StdContextGo_WithCancel(StdHttpGo_Context(request))
	var value_12 CancelCallback = func(value_11 CancelFunc) { StdContextGo_Cancel(value_11) }
	defer SyncWs_CancelAtReturn(value_12, child.Cancel)
	var value_16 ReaderWorker = func(value_13 Connection, value_14 *BufferedReader, value_15 CancelFunc) {
		SyncWs_ReadLoop(value_13, value_14, value_15)
	}
	var value_17 ReaderWorker = value_16
	var value_18 Connection = accepted.Connection
	var value_19 *BufferedReader = SyncWs_Reader(accepted.Buffer)
	SyncWs_SpawnReader(value_17, value_18, value_19, child.Cancel)
	ticker := StdTimeGo_NewTicker(Duration(30000000000))
	defer (*time.Ticker).Stop(ticker)
	for true {
		var cases [3]Case
		var value_20 Case = StdSelectGo_Receive(StdContextGo_Done(child.Value))
		cases[0] = value_20
		var value_21 Case = StdSelectGo_Receive(StdChannelGo_Interface(events.Channel))
		cases[1] = value_21
		var value_22 Case = StdSelectGo_Receive(StdTimeGo_TickerChannel(ticker))
		cases[2] = value_22
		chosen := StdSelectGo_Select(cases[0:3:3])
		if chosen.Chosen == int(0) {
			return
		}
		var value_23 Connection = accepted.Connection
		(net.Conn).SetWriteDeadline(value_23, StdTimeGo_Add(StdTimeGo_Now(), Duration(10000000000)))
		if chosen.Chosen == int(1) {
			event := SyncWs_AsEvent((reflect.Value).Interface(chosen.Value))
			var value_24 Error = Websocket_WriteJSON(accepted.Connection, event.Value)
			if value_24 != nil {
				return
			}
		} else {
			var payload []uint8 = nil
			var value_25 Error = Websocket_WriteFrame(accepted.Connection, 9, payload)
			if value_25 != nil {
				return
			}
		}
	}
}
