// Code generated by zi2go from sync_writes.zi. DO NOT EDIT.
package main

// #import std_go_types
// #import protocol
type SyncWriteResult struct {
	Applied int
	Error   Error
}

func SyncWrites_ReplaceData(transaction *Transaction, context Context, userID string) Error {
	var value_0 [8]string
	value_0[0] = "DELETE FROM server_session_rounds WHERE user_id_hash=?1"
	value_0[1] = "DELETE FROM server_sessions WHERE user_id_hash=?1"
	value_0[2] = "DELETE FROM server_habit_days WHERE user_id_hash=?1"
	value_0[3] = "DELETE FROM server_habits WHERE user_id_hash=?1"
	value_0[4] = "DELETE FROM server_meditation_logs WHERE user_id_hash=?1"
	value_0[5] = "DELETE FROM server_social_snapshots WHERE user_id_hash=?1"
	value_0[6] = "DELETE FROM server_encrypted_records WHERE user_id_hash=?1"
	value_0[7] = "DELETE FROM server_encrypted_payloads WHERE user_id_hash=?1"
	queries := value_0
	var value_1 [1]Any
	value_1[0] = userID
	arguments := value_1
	_ = arguments
	for _, query := range queries {
		removed := StdSqlGo_ExecTx(transaction, context, query, arguments[0:1:1])
		if removed.Error != nil {
			return removed.Error
		}
	}
	version := AccountState_NextVersion(transaction, context, userID)
	return version.Error
}

func SyncWrites_UpsertSession(transaction *Transaction, context Context, userID string, session Session) SyncWriteResult {
	var result SyncWriteResult = SyncWriteResult{}
	version := AccountState_NextVersion(transaction, context, userID)
	result.Error = version.Error
	if result.Error != nil {
		return result
	}
	var value_0 [17]Any
	value_0[0] = userID
	value_0[1] = session.ID
	var value_1 string = Timestamp_NormalizeTime(session.StartedAt, "")
	value_0[2] = value_1
	value_0[3] = session.LocalDate
	value_0[4] = session.Topic
	value_0[5] = session.Activity
	value_0[6] = session.Source
	value_0[7] = session.RoundsHash
	value_0[8] = session.MoodBefore
	value_0[9] = session.MoodAfter
	value_0[10] = session.Energy
	value_0[11] = session.Stress
	value_0[12] = session.Note
	value_0[13] = session.Tags
	value_0[14] = session.DeletedAt
	var value_2 string = Timestamp_NormalizeTime(session.UpdatedAt, "")
	value_0[15] = value_2
	value_0[16] = version.Value
	arguments := value_0
	_ = arguments
	var value_3 string = "\n\tINSERT INTO server_sessions(user_id_hash,id,started_at,local_date,topic,activity,source,\n\t\trounds_hash,mood_before,mood_after,energy,stress,note,tags,deleted_at,updated_at,server_version)\n\tVALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17)\n\tON CONFLICT(user_id_hash,id) DO UPDATE SET\n\t\tstarted_at=excluded.started_at,\n\t\tlocal_date=excluded.local_date,\n\t\ttopic=excluded.topic,\n\t\tactivity=excluded.activity,\n\t\tsource=excluded.source,\n\t\trounds_hash=excluded.rounds_hash,\n\t\tmood_before=excluded.mood_before,\n\t\tmood_after=excluded.mood_after,\n\t\tenergy=excluded.energy,\n\t\tstress=excluded.stress,\n\t\tnote=excluded.note,\n\t\ttags=excluded.tags,\n\t\tdeleted_at=excluded.deleted_at,\n\t\tupdated_at=excluded.updated_at,\n\t\tserver_version=excluded.server_version\n\tWHERE excluded.updated_at >= server_sessions.updated_at"
	written := StdSqlGo_ExecTx(transaction, context, value_3, arguments[0:17:17])
	result.Error = written.Error
	if result.Error != nil {
		return result
	}
	applied := AccountState_Affected(written.Value)
	if applied == int(0) || int64(len(session.Rounds)) == 0 {
		result.Applied = applied
		return result
	}
	var value_4 [2]Any
	value_4[0] = userID
	value_4[1] = session.ID
	identifiers := value_4
	_ = identifiers
	cleared := StdSqlGo_ExecTx(transaction, context, "DELETE FROM server_session_rounds WHERE user_id_hash=?1 AND session_id=?2", identifiers[0:2:2])
	result.Error = cleared.Error
	if result.Error != nil {
		return result
	}
	{
		value_5 := session.Rounds[:]
		if int64(0) < 0 || int64(int64(len(value_5))) < int64(0) || int64(int64(len(value_5))) > int64(len(value_5)) {
			panic("slice range out of bounds")
		}
		loop_view_23 := value_5[0:int64(len(value_5)):int64(len(value_5))]
		loop_count_23 := int64(len(loop_view_23))
		var loop_cursor_23 int64 = 0
		for loop_cursor_23 < loop_count_23 {
			loop_index_23 := loop_cursor_23
			round := loop_view_23[loop_index_23]
			var value_6 [5]Any
			value_6[0] = userID
			value_6[1] = session.ID
			value_6[2] = round.RoundIndex
			value_6[3] = round.Breaths
			value_6[4] = round.HoldSeconds
			values := value_6
			_ = values
			var value_7 string = "\nINSERT INTO server_session_rounds(user_id_hash,session_id,round_index,breaths,hold_seconds)\nVALUES(?1,?2,?3,?4,?5)"
			inserted := StdSqlGo_ExecTx(transaction, context, value_7, values[0:5:5])
			result.Error = inserted.Error
			if result.Error != nil {
				return result
			}
			loop_cursor_23++
		}
	}
	result.Applied = applied
	return result
}

func SyncWrites_UpsertRecord(transaction *Transaction, context Context, userID string, item EncryptedRecord) SyncWriteResult {
	var result SyncWriteResult = SyncWriteResult{}
	version := AccountState_NextVersion(transaction, context, userID)
	result.Error = version.Error
	if result.Error != nil {
		return result
	}
	var value_0 [12]Any
	value_0[0] = userID
	value_0[1] = item.Collection
	value_0[2] = item.ID
	value_0[3] = item.KeyID
	value_0[4] = item.Nonce
	value_0[5] = item.Ciphertext
	var value_1 string = Timestamp_NormalizeTime(item.UpdatedAt, "")
	value_0[6] = value_1
	value_0[7] = item.DeletedAt
	value_0[8] = item.ContentHash
	value_0[9] = item.SchemaVersion
	value_0[10] = item.ParentID
	value_0[11] = version.Value
	arguments := value_0
	_ = arguments
	var value_2 string = "\nINSERT INTO server_encrypted_records(user_id_hash,collection,id,key_id,nonce,ciphertext,updated_at,deleted_at,content_hash,schema_version,parent_id,server_version)\nVALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12)\nON CONFLICT(user_id_hash,collection,id) DO UPDATE SET\n\tkey_id=excluded.key_id,\n\tnonce=excluded.nonce,\n\tciphertext=excluded.ciphertext,\n\tupdated_at=excluded.updated_at,\n\tdeleted_at=excluded.deleted_at,\n\tcontent_hash=excluded.content_hash,\n\tschema_version=excluded.schema_version,\n\tparent_id=excluded.parent_id,\n\tserver_version=excluded.server_version\nWHERE excluded.updated_at >= server_encrypted_records.updated_at"
	written := StdSqlGo_ExecTx(transaction, context, value_2, arguments[0:12:12])
	result.Error = written.Error
	if result.Error == nil {
		result.Applied = AccountState_Affected(written.Value)
	}
	return result
}

func SyncWrites_DeleteHabit(transaction *Transaction, context Context, userID string, habit Habit) SyncWriteResult {
	var result SyncWriteResult = SyncWriteResult{}
	updatedAt := Timestamp_NormalizeTime(habit.UpdatedAt, "")
	var value_0 [3]Any
	value_0[0] = userID
	value_0[1] = habit.ID
	value_0[2] = updatedAt
	arguments := value_0
	_ = arguments
	removed := StdSqlGo_ExecTx(transaction, context, "\nDELETE FROM server_habits\nWHERE user_id_hash=?1 AND id=?2 AND updated_at<=?3", arguments[0:3:3])
	result.Error = removed.Error
	if result.Error != nil {
		return result
	}
	applied := AccountState_Affected(removed.Value)
	if applied == int(0) {
		return result
	}
	var value_1 [2]Any
	value_1[0] = userID
	value_1[1] = habit.ID
	identifiers := value_1
	_ = identifiers
	children := StdSqlGo_ExecTx(transaction, context, "\nDELETE FROM server_habit_days\nWHERE user_id_hash=?1 AND habit_id=?2", identifiers[0:2:2])
	result.Error = children.Error
	if result.Error != nil {
		return result
	}
	var value_2 int = applied
	var value_3 int = AccountState_Affected(children.Value)
	applied = value_2 + value_3
	version := AccountState_NextVersion(transaction, context, userID)
	result.Error = version.Error
	if result.Error == nil {
		result.Applied = applied
	}
	return result
}

func SyncWrites_DeleteHabitDay(transaction *Transaction, context Context, userID string, day HabitDay) SyncWriteResult {
	var result SyncWriteResult = SyncWriteResult{}
	updatedAt := Timestamp_NormalizeTime(day.UpdatedAt, "")
	var value_0 [4]Any
	value_0[0] = userID
	value_0[1] = day.HabitID
	value_0[2] = day.LocalDate
	value_0[3] = updatedAt
	arguments := value_0
	_ = arguments
	var value_1 string = "\nDELETE FROM server_habit_days\nWHERE user_id_hash=?1 AND habit_id=?2 AND local_date=?3 AND updated_at<=?4"
	removed := StdSqlGo_ExecTx(transaction, context, value_1, arguments[0:4:4])
	result.Error = removed.Error
	if result.Error != nil {
		return result
	}
	applied := AccountState_Affected(removed.Value)
	if applied == int(0) {
		return result
	}
	version := AccountState_NextVersion(transaction, context, userID)
	result.Error = version.Error
	if result.Error == nil {
		result.Applied = applied
	}
	return result
}

func SyncWrites_DeleteSession(transaction *Transaction, context Context, userID string, session Session) SyncWriteResult {
	var result SyncWriteResult = SyncWriteResult{}
	updatedAt := Timestamp_NormalizeTime(session.UpdatedAt, session.StartedAt)
	var value_0 [3]Any
	value_0[0] = userID
	value_0[1] = session.ID
	value_0[2] = updatedAt
	arguments := value_0
	_ = arguments
	removed := StdSqlGo_ExecTx(transaction, context, "\nDELETE FROM server_sessions\nWHERE user_id_hash=?1 AND id=?2 AND updated_at<=?3", arguments[0:3:3])
	result.Error = removed.Error
	if result.Error != nil {
		return result
	}
	applied := AccountState_Affected(removed.Value)
	if applied == int(0) {
		return result
	}
	var value_1 [2]Any
	value_1[0] = userID
	value_1[1] = session.ID
	identifiers := value_1
	_ = identifiers
	children := StdSqlGo_ExecTx(transaction, context, "\nDELETE FROM server_session_rounds\nWHERE user_id_hash=?1 AND session_id=?2", identifiers[0:2:2])
	result.Error = children.Error
	if result.Error != nil {
		return result
	}
	var value_2 int = applied
	var value_3 int = AccountState_Affected(children.Value)
	applied = value_2 + value_3
	version := AccountState_NextVersion(transaction, context, userID)
	result.Error = version.Error
	if result.Error == nil {
		result.Applied = applied
	}
	return result
}

func SyncWrites_CompletedValue(completed bool) int {
	if completed {
		return int(1)
	}
	return int(0)
}

func SyncWrites_NormalizedDayCount(day HabitDay) int {
	if !day.Completed {
		return int(0)
	}
	if day.Count > int(0) {
		return day.Count
	}
	return int(1)
}

func SyncWrites_UpsertMeditation(transaction *Transaction, context Context, userID string, item MeditationLog) SyncWriteResult {
	var result SyncWriteResult = SyncWriteResult{}
	version := AccountState_NextVersion(transaction, context, userID)
	result.Error = version.Error
	if result.Error != nil {
		return result
	}
	var value_0 [6]Any
	value_0[0] = userID
	value_0[1] = item.ID
	value_0[2] = item.SessionID
	value_0[3] = item.DurationSeconds
	var value_1 string = Timestamp_NormalizeTime(item.CompletedAt, item.Timestamp)
	value_0[4] = value_1
	value_0[5] = version.Value
	arguments := value_0
	_ = arguments
	var value_2 string = "\nINSERT INTO server_meditation_logs(user_id_hash,id,session_id,duration_seconds,completed_at,server_version)\nVALUES(?1,?2,?3,?4,?5,?6)\nON CONFLICT(user_id_hash,id) DO NOTHING"
	written := StdSqlGo_ExecTx(transaction, context, value_2, arguments[0:6:6])
	result.Error = written.Error
	if result.Error == nil {
		result.Applied = AccountState_Affected(written.Value)
	}
	return result
}

func SyncWrites_WriteHabit(transaction *Transaction, context Context, userID string, habit Habit, query string) SyncWriteResult {
	var result SyncWriteResult = SyncWriteResult{}
	version := AccountState_NextVersion(transaction, context, userID)
	result.Error = version.Error
	if result.Error != nil {
		return result
	}
	var value_0 [13]Any
	value_0[0] = userID
	value_0[1] = habit.ID
	value_0[2] = habit.Name
	value_0[3] = habit.ColorR
	value_0[4] = habit.ColorG
	value_0[5] = habit.ColorB
	value_0[6] = habit.SyncMode
	value_0[7] = habit.SyncActivity
	value_0[8] = habit.CounterEnabled
	value_0[9] = habit.SortOrder
	value_0[10] = habit.DeletedAt
	var value_1 string = Timestamp_NormalizeTime(habit.UpdatedAt, "")
	value_0[11] = value_1
	value_0[12] = version.Value
	arguments := value_0
	_ = arguments
	written := StdSqlGo_ExecTx(transaction, context, query, arguments[0:13:13])
	result.Error = written.Error
	if result.Error == nil {
		result.Applied = AccountState_Affected(written.Value)
	}
	return result
}

func SyncWrites_WriteDay(transaction *Transaction, context Context, userID string, day HabitDay, query string) SyncWriteResult {
	var result SyncWriteResult = SyncWriteResult{}
	version := AccountState_NextVersion(transaction, context, userID)
	result.Error = version.Error
	if result.Error != nil {
		return result
	}
	var value_0 [7]Any
	value_0[0] = userID
	value_0[1] = day.HabitID
	value_0[2] = day.LocalDate
	var value_1 int = SyncWrites_CompletedValue(day.Completed)
	value_0[3] = value_1
	var value_2 int = SyncWrites_NormalizedDayCount(day)
	value_0[4] = value_2
	var value_3 string = Timestamp_NormalizeTime(day.UpdatedAt, "")
	value_0[5] = value_3
	value_0[6] = version.Value
	arguments := value_0
	_ = arguments
	written := StdSqlGo_ExecTx(transaction, context, query, arguments[0:7:7])
	result.Error = written.Error
	if result.Error == nil {
		result.Applied = AccountState_Affected(written.Value)
	}
	return result
}

func SyncWrites_UpsertHabit(transaction *Transaction, context Context, userID string, habit Habit) SyncWriteResult {
	var value_0 string = "\nINSERT INTO server_habits(user_id_hash,id,name,color_r,color_g,color_b,sync_mode,sync_activity,counter_enabled,sort_order,deleted_at,updated_at,server_version)\nVALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13)\nON CONFLICT(user_id_hash,id) DO UPDATE SET\n\tname=excluded.name,\n\tcolor_r=excluded.color_r,\n\tcolor_g=excluded.color_g,\n\tcolor_b=excluded.color_b,\n\tsync_mode=excluded.sync_mode,\n\tsync_activity=excluded.sync_activity,\n\tcounter_enabled=excluded.counter_enabled,\n\tsort_order=excluded.sort_order,\n\tdeleted_at=excluded.deleted_at,\n\tupdated_at=excluded.updated_at,\n\tserver_version=excluded.server_version\nWHERE excluded.updated_at >= server_habits.updated_at"
	return SyncWrites_WriteHabit(transaction, context, userID, habit, value_0)
}

func SyncWrites_UpsertHabitOp(transaction *Transaction, context Context, userID string, habit Habit) SyncWriteResult {
	var value_0 string = "\nINSERT INTO server_habits(user_id_hash,id,name,color_r,color_g,color_b,sync_mode,sync_activity,counter_enabled,sort_order,deleted_at,updated_at,server_version)\nVALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13)\nON CONFLICT(user_id_hash,id) DO UPDATE SET\n\tname=excluded.name,color_r=excluded.color_r,color_g=excluded.color_g,color_b=excluded.color_b,\n\tsync_mode=excluded.sync_mode,sync_activity=excluded.sync_activity,counter_enabled=excluded.counter_enabled,\n\tsort_order=excluded.sort_order,deleted_at=excluded.deleted_at,updated_at=excluded.updated_at,\n\tserver_version=excluded.server_version\nWHERE excluded.updated_at >= server_habits.updated_at"
	return SyncWrites_WriteHabit(transaction, context, userID, habit, value_0)
}

func SyncWrites_UpsertDay(transaction *Transaction, context Context, userID string, day HabitDay) SyncWriteResult {
	var value_0 string = "\nINSERT INTO server_habit_days(user_id_hash,habit_id,local_date,completed,count,updated_at,server_version)\nVALUES(?1,?2,?3,?4,?5,?6,?7)\nON CONFLICT(user_id_hash,habit_id,local_date) DO UPDATE SET\n\tcompleted=excluded.completed,\n\tcount=excluded.count,\n\tupdated_at=excluded.updated_at,\n\tserver_version=excluded.server_version\nWHERE excluded.updated_at >= server_habit_days.updated_at"
	return SyncWrites_WriteDay(transaction, context, userID, day, value_0)
}

func SyncWrites_UpsertDayOp(transaction *Transaction, context Context, userID string, day HabitDay) SyncWriteResult {
	var value_0 string = "\nINSERT INTO server_habit_days(user_id_hash,habit_id,local_date,completed,count,updated_at,server_version)\nVALUES(?1,?2,?3,?4,?5,?6,?7)\nON CONFLICT(user_id_hash,habit_id,local_date) DO UPDATE SET\n\tcompleted=excluded.completed,count=excluded.count,updated_at=excluded.updated_at,server_version=excluded.server_version\nWHERE excluded.updated_at >= server_habit_days.updated_at"
	return SyncWrites_WriteDay(transaction, context, userID, day, value_0)
}
