// Code generated by zi2go from timestamp.zi. DO NOT EDIT.
package main

type TimestampResult struct {
	Value Time
	Valid bool
}

const CanonicalTimestampLayout = "2006-01-02T15:04:05.000000000Z07:00"
const MinCanonicalTimestamp = "0001-01-01T00:00:00.000000000Z"

func Timestamp_CanonicalNow() string {
	return Timestamp_CanonicalTimestamp(StdTimeGo_Now())
}

func Timestamp_CanonicalTimestamp(value Time) string {
	return StdTimeGo_Format(StdTimeGo_UTC(value), "2006-01-02T15:04:05.000000000Z07:00")
}

func Timestamp_ParseTimestamp(value string) TimestampResult {
	parsed := StdTimeGo_Parse("2006-01-02T15:04:05.999999999Z07:00", value)
	if parsed.Error == nil {
		var result TimestampResult = TimestampResult{}
		_ = result
		result.Value = parsed.Value
		result.Valid = true
		return result
	}
	parsed = StdTimeGo_Parse("2006-01-02 15:04:05", value)
	if parsed.Error == nil {
		var result TimestampResult = TimestampResult{}
		_ = result
		result.Value = parsed.Value
		result.Valid = true
		return result
	}
	var result TimestampResult = TimestampResult{}
	_ = result
	return result
}

func Timestamp_NormalizeTime(primary string, fallback string) string {
	value := primary
	if value == "" {
		value = fallback
	}
	if value == "" {
		return Timestamp_CanonicalNow()
	}
	parsed := Timestamp_ParseTimestamp(value)
	if parsed.Valid {
		return Timestamp_CanonicalTimestamp(parsed.Value)
	}
	return "0001-01-01T00:00:00.000000000Z"
}
