// Code generated by zi2go from token_checkpoint.zi. DO NOT EDIT.
package main

import (
	bytes "bytes"
	sql "database/sql"
	hex "encoding/hex"
	fmt "fmt"
)

// #import protocol
// #import std_go_types
type CheckpointResult struct {
	Value TokenCheckpoint
	Found bool
	Error Error
}

type Buffer = bytes.Buffer

type zir_f119c30711a2bf4c_RowsResult struct {
	Value *Rows
	Error Error
}

type zir_752ea6e2e5e596c8_ExecResult struct {
	Value Result
	Error Error
}

type zir_2a3e390cad4a8814_WriteResult struct {
	Count int
	Error Error
}

func TokenCheckpoint_QueryRows(Database *Database, Context Context, Query string, IssuerID string, AssetID string) zir_f119c30711a2bf4c_RowsResult {
	var result zir_f119c30711a2bf4c_RowsResult
	result.Value, result.Error = (*sql.DB).QueryContext(Database, Context, Query, IssuerID, AssetID)
	return result
}

func TokenCheckpoint_WriteString(Buffer *Buffer, Value string) zir_2a3e390cad4a8814_WriteResult {
	var result zir_2a3e390cad4a8814_WriteResult
	result.Count, result.Error = (*bytes.Buffer).WriteString(Buffer, Value)
	return result
}

func TokenCheckpoint_Insert(Database *Database, Context Context, Query string, Sequence int64, IssuerID string, AssetID string, Root string, Signature string) zir_752ea6e2e5e596c8_ExecResult {
	var result zir_752ea6e2e5e596c8_ExecResult
	result.Value, result.Error = (*sql.DB).ExecContext(Database, Context, Query, Sequence, IssuerID, AssetID, Root, Signature)
	return result
}

func TokenCheckpoint_Latest(database *Database, context Context) CheckpointResult {
	var result CheckpointResult = CheckpointResult{}
	var item TokenCheckpoint = TokenCheckpoint{}
	var value_0 string = "SELECT ledger_seq,issuer_id,asset_id,ledger_root,signature,created_at\nFROM token_checkpoints\nORDER BY ledger_seq DESC\nLIMIT 1"
	var value_1 Error = (*sql.Row).Scan((*sql.DB).QueryRowContext(database, context, value_0), &(item.LedgerSeq), &(item.IssuerID), &(item.AssetID), &(item.LedgerRoot), &(item.Signature), &(item.CreatedAt))
	result.Error = value_1
	var value_2 Error = result.Error
	if StdErrorsGo_Is(value_2, StdSqlGo_NoRows()) {
		result.Error = nil
		return result
	}
	if result.Error == nil {
		result.Value = item
		result.Found = true
	}
	return result
}

func TokenCheckpoint_Create(database *Database, context Context, signer PrivateKey, unavailable Error) CheckpointResult {
	var result CheckpointResult = CheckpointResult{}
	if len(signer) != int(64) {
		result.Error = unavailable
		return result
	}
	var value_0 string = "SELECT ledger_seq,event_hash\nFROM token_ledger\nWHERE issuer_id=?1 AND asset_id=?2\nORDER BY ledger_seq"
	queried := TokenCheckpoint_QueryRows(database, context, value_0, "waozi", "waozi:token")
	result.Error = queried.Error
	if result.Error != nil {
		return result
	}
	rows := queried.Value
	defer (*sql.Rows).Close(rows)
	var initial []uint8 = nil
	buffer := bytes.NewBuffer(initial)
	var sequence int64 = 0
	for StdSqlGo_Next(rows) {
		var hash string = ""
		var value_1 Error = (*sql.Rows).Scan(rows, &(sequence), &(hash))
		result.Error = value_1
		if result.Error != nil {
			return result
		}
		TokenCheckpoint_WriteString(buffer, hash)
		(*bytes.Buffer).WriteByte(buffer, uint8(10))
	}
	var value_2 Error = StdSqlGo_RowsError(rows)
	result.Error = value_2
	if result.Error != nil {
		return result
	}
	root := Signing_SHA256Hex((*bytes.Buffer).Bytes(buffer))
	var value_3 string = fmt.Sprintf("ksync-token-checkpoint-v1\n%s\n%s\n%d\n%s\n", "waozi", "waozi:token", int64(sequence), root)
	message := StdTextGo_ToBytes(value_3)
	signature := hex.EncodeToString(StdEd25519Go_Sign(signer, message))
	var value_4 string = "INSERT INTO token_checkpoints(ledger_seq,issuer_id,asset_id,ledger_root,signature)\nVALUES(?1,?2,?3,?4,?5)\nON CONFLICT(ledger_seq) DO UPDATE SET\nledger_root=excluded.ledger_root,\nsignature=excluded.signature,\ncreated_at=CURRENT_TIMESTAMP"
	var value_5 zir_752ea6e2e5e596c8_ExecResult = TokenCheckpoint_Insert(database, context, value_4, int64(sequence), "waozi", "waozi:token", root, signature)
	written := value_5
	result.Error = written.Error
	if result.Error != nil {
		return result
	}
	return TokenCheckpoint_Latest(database, context)
}
