// Code generated by zi2go from transaction.zi. DO NOT EDIT.
package main

import (
	strconv "strconv"
	strings "strings"
)

// #import protocol
type SignedTxEnvelope struct {
	ProtocolVersion  int    "json:\"protocol_version\""
	TxID             string "json:\"tx_id\""
	AccountID        string "json:\"account_id\""
	AppID            string "json:\"app_id\""
	DeviceKeyID      string "json:\"device_key_id\""
	Method           string "json:\"method\""
	Path             string "json:\"path\""
	BodySHA256       string "json:\"body_sha256\""
	Nonce            string "json:\"nonce\""
	ExpiresAt        int64  "json:\"expires_at\""
	SignatureContext string "json:\"signature_context,omitempty\""
	Signature        string "json:\"signature\""
	DeviceSignature  string "json:\"device_signature\""
}

type SignedAppGrantRequest struct {
	Tx    SignedTxEnvelope "json:\"tx\""
	Grant AppGrantRequest  "json:\"grant\""
}

func Transaction_Normalize(tx *SignedTxEnvelope) {
	var value_0 string = strings.TrimSpace(tx.TxID)
	tx.TxID = value_0
	var value_1 string = strings.ToLower(strings.TrimSpace(tx.AccountID))
	tx.AccountID = value_1
	var value_2 string = strings.TrimSpace(tx.AppID)
	tx.AppID = value_2
	var value_3 string = strings.TrimSpace(tx.DeviceKeyID)
	tx.DeviceKeyID = value_3
	var value_4 string = strings.ToUpper(strings.TrimSpace(tx.Method))
	tx.Method = value_4
	var value_5 string = strings.TrimSpace(tx.Path)
	tx.Path = value_5
	var value_6 string = strings.ToLower(strings.TrimSpace(tx.BodySHA256))
	tx.BodySHA256 = value_6
	var value_7 string = strings.TrimSpace(tx.Nonce)
	tx.Nonce = value_7
	var value_8 string = strings.TrimSpace(tx.SignatureContext)
	tx.SignatureContext = value_8
	var value_9 string = strings.TrimSpace(tx.Signature)
	tx.Signature = value_9
	var value_10 string = strings.TrimSpace(tx.DeviceSignature)
	tx.DeviceSignature = value_10
}

func Transaction_CanonicalMessage(context string, tx SignedTxEnvelope) string {
	var value_0 string = strconv.FormatInt(int64(int64(tx.ProtocolVersion)), int(int(10)))
	var value_1 string = strconv.FormatInt(int64(tx.ExpiresAt), int(int(10)))
	var value_2 [12]string = [12]string{context, value_0, tx.TxID, tx.AccountID, tx.AppID, tx.DeviceKeyID, tx.Method, tx.Path, tx.BodySHA256, tx.Nonce, value_1, ""}
	parts := value_2
	_ = parts
	return strings.Join(parts[0:12:12], "\n")
}
