// Code generated by zi2go from verifier.zi. DO NOT EDIT.
package main

// #import std_go_types
type Verifier struct {
	Verify VerifySignature
}

type VerifierResult struct {
	Value *Verifier
	Error Error
}

var ErrVerifierUnavailable Error

func Verifier_New(verify VerifySignature) *Verifier {
	verifier := new(Verifier)
	verifier.Verify = verify
	return verifier
}

func Verifier_GlobalInit00() {
	ErrVerifierUnavailable = StdErrorsGo_New("ML-DSA-44 verifier unavailable")
}

var Verifier_ziranInitState uint8

func Verifier_ziranInit() {
	if Verifier_ziranInitState == 2 {
		return
	}
	if Verifier_ziranInitState == 1 {
		panic("cyclic module startup")
	}
	Verifier_ziranInitState = 1
	Verifier_GlobalInit00()
	Verifier_ziranInitState = 2
}

func init() { Verifier_ziranInit() }
